// backend/utils/adidasProductsData.js
// 106 Unique, Non-Repeating Official Adidas Products (Ultraboost, Adizero, Samba OG, Gazelle, Spezial, Stan Smith, Predator, F50, Adicolor, Terrex Gore-Tex, Tiro & Equipment)

export const getAdidasProducts = (categoryId) => {
  return [
    // --- 1. ADIDAS RUNNING & INNOVATION PERFORMANCE (25 Models) ---
    {
      name: 'Adidas Ultraboost Light Running Shoes',
      slug: 'adidas-ultraboost-light-running-shoes',
      description: 'Experience epic energy with our lightest Ultraboost ever: 30% lighter Light BOOST midsole foam, Linear Energy Push (LEP) system, Primeknit+ textile upper made with ocean plastic, and Continental Better Rubber outsole.',
      price: 190,
      discount_price: 159,
      stock: 45,
      image_url: 'https://images.unsplash.com/photo-1587563871167-1ee9c731aefb?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1587563871167-1ee9c731aefb?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 620,
      is_featured: true,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Adidas', Midsole: 'Light BOOST (30% Lighter)', Upper: 'Primeknit+ Forged Textile', Outsole: 'Continental Better Rubber', Drop: '10 mm (Heel: 30 mm / Forefoot: 20 mm)' }
    },
    {
      name: 'Adidas Ultraboost 5X Performance Running Shoes',
      slug: 'adidas-ultraboost-5x-performance-running-shoes',
      description: 'High-rebound Light BOOST V2 cushioning, redesigned Primeknit upper with engineered breathability, external heel counter, and Continental rubber grip in wet and dry conditions.',
      price: 180,
      discount_price: 160,
      stock: 40,
      image_url: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 310,
      is_featured: true,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Adidas', Technology: 'Light BOOST V2', Upper: 'Adaptive Primeknit', Terrain: 'Road Running' }
    },
    {
      name: 'Adidas Ultraboost 1.0 DNA Lifestyle Shoes',
      slug: 'adidas-ultraboost-1-0-dna-lifestyle-shoes',
      description: 'From a morning 5K to city streets: Original 2015 Primeknit pattern, supportive midfoot cage, full-length BOOST midsole, and Stretchweb outsole with Continental Rubber.',
      price: 190,
      discount_price: 149,
      stock: 55,
      image_url: 'https://images.unsplash.com/photo-1587563871167-1ee9c731aefb?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1587563871167-1ee9c731aefb?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 980,
      is_featured: false,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Adidas', Heritage: 'Original 2015 Ultraboost 1.0 Weave', Cushioning: 'Full-Length BOOST' }
    },
    {
      name: 'Adidas Ultraboost 22 Women Running Shoes',
      slug: 'adidas-ultraboost-22-women-running-shoes',
      description: 'Created by women, for women: 360-degree female anatomical fit refinement, narrower heel cup, lower instep curve, and enhanced LEP torsion system.',
      price: 190,
      discount_price: 139,
      stock: 35,
      image_url: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 420,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Adidas', Gender: 'Women-Specific Anatomical Last', Midsole: 'BOOST Foam' }
    },
    {
      name: 'Adidas Adizero Adios Pro 3 Marathon Racing Shoes',
      slug: 'adidas-adizero-adios-pro-3-marathon-racing-shoes',
      description: 'The pinnacle of road racing: Dual-layer resilient Lightstrike Pro foam, carbon-infused ENERGYRODS 2.0 mirroring the foot’s metatarsal bones, synthetic mesh upper for featherlight race day speed.',
      price: 250,
      discount_price: 229,
      stock: 25,
      image_url: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80'],
      rating: 5.0,
      num_reviews: 280,
      is_featured: true,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Adidas', Foam: 'Dual Lightstrike Pro Cushioning', Carbon: 'ENERGYRODS 2.0 Carbon Rods', Weight: '215g (Size 9)' }
    },
    {
      name: 'Adidas Adizero Boston 12 Training Shoes',
      slug: 'adidas-adizero-boston-12-training-shoes',
      description: 'Mid-to-long distance tempo trainer: Lightstrike 2.0 and Lightstrike Pro layered foam, glass-fiber infused ENERGYRODS 2.0, lightweight mesh upper.',
      price: 160,
      discount_price: 139,
      stock: 35,
      image_url: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 195,
      is_featured: false,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Adidas', Technology: 'ENERGYRODS 2.0 Glass Fiber', Cushioning: 'Lightstrike Pro + Lightstrike 2.0' }
    },
    {
      name: 'Adidas Adizero Prime X 2 Strung Super Shoes',
      slug: 'adidas-adizero-prime-x-2-strung-super-shoes',
      description: 'Unregulated 50mm stack height super shoe: Triple layers of Lightstrike Pro foam, dual carbon-infused plates, data-driven STRUNG textile upper cocooning the foot.',
      price: 300,
      discount_price: 279,
      stock: 15,
      image_url: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80'],
      rating: 5.0,
      num_reviews: 140,
      is_featured: true,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Adidas', StackHeight: '50 mm Super-Stack', Carbon: 'Dual Carbon Plates', Upper: 'STRUNG Robotically Woven Upper' }
    },
    {
      name: 'Adidas Adizero Takumi Sen 10 5K/10K Racing Flats',
      slug: 'adidas-adizero-takumi-sen-10-racing-flats',
      description: 'Explosive speed for 5K to 10K road racing: Full-length Lightstrike Pro foam with glass-fiber ENERGYRODS, Continental rubber forefoot patch, ultra-breathable mesh.',
      price: 180,
      discount_price: 159,
      stock: 22,
      image_url: 'https://images.unsplash.com/photo-1587563871167-1ee9c731aefb?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1587563871167-1ee9c731aefb?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 110,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Adidas', Distance: '5K to 10K Racing', Weight: '166g Ultralight', Foam: 'Lightstrike Pro' }
    },
    {
      name: 'Adidas Adizero Adios 8 Fast Training Shoes',
      slug: 'adidas-adizero-adios-8-fast-training-shoes',
      description: 'Low-profile responsive racer: Lightstrike Pro in the forefoot, Lightstrike 2.0 in the heel, micro-fit mesh upper, and Continental rubber toe-off grip.',
      price: 130,
      discount_price: 109,
      stock: 30,
      image_url: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80'],
      rating: 4.7,
      num_reviews: 160,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Adidas', Weight: '200g', Foam: 'Lightstrike Pro & 2.0 Dual Layer' }
    },
    {
      name: 'Adidas Adizero SL2 Daily Speed Trainer',
      slug: 'adidas-adizero-sl2-daily-speed-trainer',
      description: 'Accessible elite speed trainer: Full Lightstrike 2.0 frame with embedded Lightstrike Pro puck in the forefoot for snappy toe-offs.',
      price: 130,
      discount_price: 119,
      stock: 45,
      image_url: 'https://images.unsplash.com/photo-1587563871167-1ee9c731aefb?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1587563871167-1ee9c731aefb?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 230,
      is_featured: false,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Adidas', Cushioning: 'Lightstrike Pro Drop-In Puck', Upper: 'Engineered Mesh' }
    },
    {
      name: 'Adidas 4DFWD 3 3D-Printed Running Shoes',
      slug: 'adidas-4dfwd-3-3d-printed-running-shoes',
      description: 'Lattice structure 3D-printed midsole compresses forward on impact to transform vertical braking forces into forward momentum: Primeknit+ sock-like fit.',
      price: 220,
      discount_price: 189,
      stock: 30,
      image_url: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 240,
      is_featured: false,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Adidas', Midsole: '3D-Printed 4DFWD Lattice', ForwardMotion: 'Redirects Impact Energy Forward' }
    },
    {
      name: 'Adidas 4D FWD 2 Core Black Running Shoes',
      slug: 'adidas-4d-fwd-2-core-black-running-shoes',
      description: 'Bow-tie lattice 3D printed sole, Primeknit collar, integrated TPU lacing cage, Continental rubber outsole.',
      price: 200,
      discount_price: 169,
      stock: 28,
      image_url: 'https://images.unsplash.com/photo-1587563871167-1ee9c731aefb?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1587563871167-1ee9c731aefb?auto=format&fit=crop&w=800&q=80'],
      rating: 4.7,
      num_reviews: 190,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Adidas', Sole: '4D Forward Lattice', Color: 'Core Black / Carbon' }
    },
    {
      name: 'Adidas Supernova Rise Daily Running Shoes',
      slug: 'adidas-supernova-rise-daily-running-shoes',
      description: 'Dreamstrike+ super-foam midsole tuned for daily training comfort: Support Rods system for smooth transitions, engineered sandwich mesh upper.',
      price: 140,
      discount_price: 119,
      stock: 50,
      image_url: 'https://images.unsplash.com/photo-1587563871167-1ee9c731aefb?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1587563871167-1ee9c731aefb?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 350,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Adidas', Foam: 'Dreamstrike+ Super Foam', System: 'Dense Foam Support Rods' }
    },
    {
      name: 'Adidas Supernova Solution Stability Running Shoes',
      slug: 'adidas-supernova-solution-stability-running-shoes',
      description: 'Daily stability running shoe featuring dual-density Dreamstrike+ foam, medial Stability Rods to guide overpronation, and Adiwear outsole.',
      price: 140,
      discount_price: 124,
      stock: 38,
      image_url: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80'],
      rating: 4.7,
      num_reviews: 180,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Adidas', Pronation: 'Stability / Overpronation Support', Cushioning: 'Dreamstrike+' }
    },
    {
      name: 'Adidas Supernova Stride Everyday Trainers',
      slug: 'adidas-supernova-stride-everyday-trainers',
      description: 'Engineered for beginner to intermediate runners: Forefoot Dreamstrike+ foam EVA carrier, durable Adiwear outsole, padded tongue and collar.',
      price: 110,
      discount_price: 94,
      stock: 55,
      image_url: 'https://images.unsplash.com/photo-1587563871167-1ee9c731aefb?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1587563871167-1ee9c731aefb?auto=format&fit=crop&w=800&q=80'],
      rating: 4.6,
      num_reviews: 290,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Adidas', Midsole: 'Dreamstrike+ Forefoot Insert', Outsole: 'Adiwear 600' }
    },
    {
      name: 'Adidas Solarboost 5 Distance Running Shoes',
      slug: 'adidas-solarboost-5-distance-running-shoes',
      description: 'Energy-returning BOOST midsole with Control Rail technology for neutral guidance: Continental rubber outsole, breathable engineered mesh upper.',
      price: 160,
      discount_price: 129,
      stock: 35,
      image_url: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 290,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Adidas', Cushioning: 'Full-Length BOOST', Stability: 'Control Rail Lateral Support' }
    },
    {
      name: 'Adidas Solarglide 6 Daily Distance Runners',
      slug: 'adidas-solarglide-6-daily-distance-runners',
      description: 'Reliable high-mileage shoe with BOOST cushioning and LEP 2.0 torsion system: Circular knit upper, Continental rubber traction.',
      price: 140,
      discount_price: 115,
      stock: 40,
      image_url: 'https://images.unsplash.com/photo-1587563871167-1ee9c731aefb?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1587563871167-1ee9c731aefb?auto=format&fit=crop&w=800&q=80'],
      rating: 4.7,
      num_reviews: 340,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Adidas', Cushioning: 'BOOST Midsole', Torsion: 'LEP 2.0' }
    },
    {
      name: 'Adidas Adistar 2.0 Long-Distance Running Shoes',
      slug: 'adidas-adistar-2-0-long-distance-running-shoes',
      description: 'Engineered for slow, steady long miles: Dual-density REPETITOR and REPETITOR+ firm cradle foam, rocker geometry for forward roll.',
      price: 130,
      discount_price: 109,
      stock: 42,
      image_url: 'https://images.unsplash.com/photo-1587563871167-1ee9c731aefb?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1587563871167-1ee9c731aefb?auto=format&fit=crop&w=800&q=80'],
      rating: 4.7,
      num_reviews: 210,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Adidas', Foam: 'Dual-Density REPETITOR & REPETITOR+', Geometry: 'Rocker Profile' }
    },
    {
      name: 'Adidas Adistar CS Stability Long-Distance Shoes',
      slug: 'adidas-adistar-cs-stability-shoes',
      description: 'Cushioned support for marathon training: REPETITOR+ stabilizing heel cage frame, internal support module, rocker toe-spring.',
      price: 160,
      discount_price: 129,
      stock: 30,
      image_url: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80'],
      rating: 4.7,
      num_reviews: 140,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Adidas', Type: 'Cushioned Support (CS)', Heel: 'Repetitor+ Firm Heel Frame' }
    },
    {
      name: 'Adidas Switch FWD Forward-Propulsion Shoes',
      slug: 'adidas-switch-fwd-forward-propulsion-shoes',
      description: 'Engineered EVA midsole voids that compress and expand to propel you forward: 3D-molded heel counter, Continental rubber outsole.',
      price: 140,
      discount_price: 119,
      stock: 35,
      image_url: 'https://images.unsplash.com/photo-1587563871167-1ee9c731aefb?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1587563871167-1ee9c731aefb?auto=format&fit=crop&w=800&q=80'],
      rating: 4.6,
      num_reviews: 170,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Adidas', Midsole: 'Engineered Void Forward Propulsion', Outsole: 'Continental' }
    },
    {
      name: 'Adidas Pureboost 23 Road Running Shoes',
      slug: 'adidas-pureboost-23-road-running-shoes',
      description: 'Responsive full-length BOOST midsole in a minimalist road shoe: Engineered mesh upper, Stretchweb rubber outsole.',
      price: 140,
      discount_price: 110,
      stock: 45,
      image_url: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80'],
      rating: 4.7,
      num_reviews: 310,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Adidas', Cushioning: 'Full-Length BOOST', Upper: 'Mesh' }
    },
    {
      name: 'Adidas Duramo Speed Lightweight Daily Runners',
      slug: 'adidas-duramo-speed-lightweight-daily-runners',
      description: 'Full-length Lightstrike cushioning in an accessible training package: breathable engineered mesh and durable Adiwear rubber.',
      price: 90,
      discount_price: 74,
      stock: 60,
      image_url: 'https://images.unsplash.com/photo-1587563871167-1ee9c731aefb?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1587563871167-1ee9c731aefb?auto=format&fit=crop&w=800&q=80'],
      rating: 4.6,
      num_reviews: 430,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Adidas', Midsole: 'Lightstrike Foam', Upper: 'Engineered Mesh' }
    },
    {
      name: 'Adidas Runfalcon 3.0 Wide Road Running Shoes',
      slug: 'adidas-runfalcon-3-0-wide-running-shoes',
      description: 'Cloudfoam midsole provides plush step-in comfort for gym workouts and neighborhood jogs: wide fit option.',
      price: 65,
      discount_price: 52,
      stock: 80,
      image_url: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80'],
      rating: 4.5,
      num_reviews: 820,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Adidas', Cushioning: 'Cloudfoam Midsole', Fit: 'Wide Fit Width' }
    },
    {
      name: 'Adidas Alphaboost V1 Performance Gym Shoes',
      slug: 'adidas-alphaboost-v1-performance-gym-shoes',
      description: 'Multi-directional training powerhouse: Dual BOOST and Bounce cushioning, Adiprene+ forefoot insert, Adiwear rubber.',
      price: 120,
      discount_price: 99,
      stock: 40,
      image_url: 'https://images.unsplash.com/photo-1587563871167-1ee9c731aefb?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1587563871167-1ee9c731aefb?auto=format&fit=crop&w=800&q=80'],
      rating: 4.7,
      num_reviews: 210,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Adidas', Cushioning: 'BOOST + Bounce + Adiprene+', Use: 'HIIT & Running' }
    },
    {
      name: 'Adidas Dropset 2 Strength Training Shoes',
      slug: 'adidas-dropset-2-strength-training-shoes',
      description: '6mm heel drop for stable deadlifts and squats: Dual-density EVA midsole, lateral TPU sidewalls, Traxion rubber outsole.',
      price: 130,
      discount_price: 110,
      stock: 35,
      image_url: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 180,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Adidas', Drop: '6mm Flat Platform', Support: 'TPU Locked-in Sidewalls' }
    },

    // --- 2. ADIDAS ORIGINALS & HERITAGE SNEAKERS (25 Models) ---
    {
      name: 'Adidas Samba OG Shoes (Cloud White / Core Black / Gum)',
      slug: 'adidas-samba-og-shoes-cloud-white-core-black-gum',
      description: 'The definitive streetwear icon: Full-grain leather upper with gritty suede T-toe overlay, serrated 3-Stripes, gold-foil Samba wordmark, and classic gum rubber cupsole.',
      price: 100,
      discount_price: 100,
      stock: 80,
      image_url: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80'],
      rating: 5.0,
      num_reviews: 3200,
      is_featured: true,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Adidas', Upper: 'Full-Grain Leather with Suede T-Toe', Outsole: 'Gum Rubber Cupsole', Logo: 'Gold Foil Samba Lettering' }
    },
    {
      name: 'Adidas Samba OG Shoes (Core Black / Cloud White / Gum)',
      slug: 'adidas-samba-og-shoes-core-black-cloud-white-gum',
      description: 'Stealth black edition of the legendary 1950 indoor football silhouette: soft leather, contrasting white 3-Stripes, and low-profile gum sole.',
      price: 100,
      discount_price: 100,
      stock: 75,
      image_url: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 2100,
      is_featured: true,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Adidas', Colorway: 'Core Black / Cloud White / Gum', Outsole: 'Low-Profile Gum Rubber' }
    },
    {
      name: 'Adidas Samba Decon Collapsible Leather Shoes',
      slug: 'adidas-samba-decon-collapsible-leather-shoes',
      description: 'Deconstructed version with ultra-soft unlined leather: Collapsible heel step-down design turns sneakers into effortless slip-ons.',
      price: 150,
      discount_price: 139,
      stock: 25,
      image_url: 'https://images.unsplash.com/photo-1587563871167-1ee9c731aefb?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1587563871167-1ee9c731aefb?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 320,
      is_featured: false,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Adidas', Construction: 'Deconstructed Unlined Premium Leather', Heel: 'Collapsible Step-Down Heel' }
    },
    {
      name: 'Adidas Samba Classic Indoor Soccer Shoes',
      slug: 'adidas-samba-classic-indoor-soccer-shoes',
      description: 'Original extended tongue profile, full-grain leather upper, EVA insole, non-marking gum rubber indoor court outsole.',
      price: 90,
      discount_price: 79,
      stock: 70,
      image_url: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 2900,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Adidas', Tongue: 'Extended Classic Fold-Over Tongue', Sole: 'Non-Marking Gum Rubber' }
    },
    {
      name: 'Adidas Gazelle Indoor Shoes (Blue Fusion / Gum)',
      slug: 'adidas-gazelle-indoor-shoes-blue-fusion-gum',
      description: 'Rich premium suede upper, translucent gum rubber outsole wrapping high on the sides, leather lining, and Trefoil tread pattern.',
      price: 120,
      discount_price: 110,
      stock: 50,
      image_url: 'https://images.unsplash.com/photo-1587563871167-1ee9c731aefb?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1587563871167-1ee9c731aefb?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 940,
      is_featured: true,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Adidas', Material: 'Premium Soft Suede', Outsole: 'Semi-Translucent Gum Rubber Wrap' }
    },
    {
      name: 'Adidas Gazelle Indoor Shoes (Collegiate Green / White)',
      slug: 'adidas-gazelle-indoor-shoes-collegiate-green',
      description: 'Lush green suede with bright white 3-Stripes and gold lettering: translucent gum sole and classic indoor cupsole structure.',
      price: 120,
      discount_price: 110,
      stock: 45,
      image_url: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 820,
      is_featured: false,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Adidas', Colorway: 'Collegiate Green / Cloud White / Gum' }
    },
    {
      name: 'Adidas Gazelle Classic Suede Shoes (Core Black / White)',
      slug: 'adidas-gazelle-classic-suede-shoes-core-black-white',
      description: 'Reissue of the 1991 Gazelle: Soft nubuck suede upper, synthetic leather overlays, rubber outsole, timeless minimalist terrace aesthetic.',
      price: 100,
      discount_price: 89,
      stock: 65,
      image_url: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 1850,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Adidas', Upper: 'Nubuck Suede', Heritage: '1991 Archive Reissue' }
    },
    {
      name: 'Adidas Gazelle 85 Vintage Suede Shoes',
      slug: 'adidas-gazelle-85-vintage-suede-shoes',
      description: 'Faithful reproduction of the 1985 Gazelle shape with refined toe box curve, foxing tape, and luxury hairy suede.',
      price: 130,
      discount_price: 115,
      stock: 25,
      image_url: 'https://images.unsplash.com/photo-1587563871167-1ee9c731aefb?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1587563871167-1ee9c731aefb?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 320,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Adidas', Year: '1985 Spec Reproduction', Upper: 'Hairy Vintage Suede' }
    },
    {
      name: 'Adidas Handball Spezial Shoes (Light Blue / Wonder Clay / Gum)',
      slug: 'adidas-handball-spezial-shoes-light-blue-gum',
      description: 'Originally released in 1979 for indoor handball players: velvety suede upper, soft leather heel tab, and iconic gum rubber sole.',
      price: 110,
      discount_price: 110,
      stock: 45,
      image_url: 'https://images.unsplash.com/photo-1587563871167-1ee9c731aefb?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1587563871167-1ee9c731aefb?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 1120,
      is_featured: true,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Adidas', Upper: 'Suede with Leather Accents', Origin: '1979 Indoor Handball Archive' }
    },
    {
      name: 'Adidas Handball Spezial Shoes (Night Cargo / Yellow / Gum)',
      slug: 'adidas-handball-spezial-shoes-night-cargo',
      description: 'Army green suede upper with contrasting solar yellow stripes and dark gum rubber traction sole.',
      price: 110,
      discount_price: 99,
      stock: 35,
      image_url: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 490,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Adidas', Colorway: 'Night Cargo / Solar Yellow / Gum' }
    },
    {
      name: 'Adidas Stan Smith Classic Tennis Shoes (White / Green)',
      slug: 'adidas-stan-smith-classic-tennis-shoes-white-green',
      description: 'Clean minimalist tennis icon: Vegan synthetic upper made with Primegreen recycled materials, perforated 3-Stripes, Stan Smith portrait on the tongue, and green heel tab.',
      price: 100,
      discount_price: 84,
      stock: 90,
      image_url: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 4200,
      is_featured: true,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Adidas', Upper: 'Primegreen Recycled Vegan Leather', Stripes: 'Perforated 3-Stripes', Tongue: 'Stan Smith Signature Portrait' }
    },
    {
      name: 'Adidas Stan Smith Lux Leather Sneakers (Off White / Cream)',
      slug: 'adidas-stan-smith-lux-leather-off-white',
      description: 'Elevated luxury version: Ultra-supple buttery full leather from tongue to lining, reinforced stitching, and gold embossed branding.',
      price: 140,
      discount_price: 125,
      stock: 30,
      image_url: 'https://images.unsplash.com/photo-1587563871167-1ee9c731aefb?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1587563871167-1ee9c731aefb?auto=format&fit=crop&w=800&q=80'],
      rating: 5.0,
      num_reviews: 290,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Adidas', Edition: 'Lux Heritage Tier', Material: 'Full Butter-Soft Leather Lining & Upper' }
    },
    {
      name: 'Adidas Superstar Shoes (Cloud White / Core Black Shell-Toe)',
      slug: 'adidas-superstar-shoes-cloud-white-core-black',
      description: 'Hip-hop and basketball royalty: Iconic rubber shell toe, serrated 3-Stripes, smooth leather upper, herringbone-pattern rubber cupsole.',
      price: 100,
      discount_price: 89,
      stock: 85,
      image_url: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 3600,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Adidas', Toe: 'Iconic Rubber Shell Toe', Material: 'Smooth Leather' }
    },
    {
      name: 'Adidas Superstar XLG Chunky Sneakers',
      slug: 'adidas-superstar-xlg-chunky-sneakers',
      description: 'Bold oversized proportions: Platform chunky midsole, enlarged 3-Stripes, full leather upper, and classic shell toe.',
      price: 110,
      discount_price: 94,
      stock: 45,
      image_url: 'https://images.unsplash.com/photo-1587563871167-1ee9c731aefb?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1587563871167-1ee9c731aefb?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 620,
      is_featured: false,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Adidas', Midsole: 'Elevated Chunky Platform XLG' }
    },
    {
      name: 'Adidas Campus 00s Skate Shoes (Core Black / White)',
      slug: 'adidas-campus-00s-skate-shoes-core-black-white',
      description: 'Chunky Y2K skateboarding proportion remix: Padded tongue and collar, oversized cotton fat laces, plush suede upper, and off-white vintage midsole.',
      price: 110,
      discount_price: 99,
      stock: 55,
      image_url: 'https://images.unsplash.com/photo-1587563871167-1ee9c731aefb?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1587563871167-1ee9c731aefb?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 1420,
      is_featured: true,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Adidas', Style: 'Y2K Padded Skate Fit', Laces: 'Oversized Chunky Fat Laces', Upper: 'Heavy Suede' }
    },
    {
      name: 'Adidas Campus 00s Skate Shoes (Grey Three / Cloud White)',
      slug: 'adidas-campus-00s-skate-shoes-grey-three',
      description: 'Neutral grey suede skate edition: puffy tongue with retro Trefoil logo, fat laces, textile lining, durable gum outsole.',
      price: 110,
      discount_price: 99,
      stock: 50,
      image_url: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 890,
      is_featured: false,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Adidas', Colorway: 'Grey Three / Cloud White / Off White' }
    },
    {
      name: 'Adidas Forum Low Classic Basketball Shoes',
      slug: 'adidas-forum-low-classic-basketball-shoes',
      description: '1984 hardwood legend: Removable crisscross ankle strap, layered leather panels, X-strap detail on the side, and durable rubber cupsole.',
      price: 100,
      discount_price: 85,
      stock: 40,
      image_url: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 860,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Adidas', Strap: 'Removable Hook-and-Loop Ankle Strap', Heritage: '1984 Hardwood Basketball' }
    },
    {
      name: 'Adidas Forum 84 High Vintage Basketball Shoes',
      slug: 'adidas-forum-84-high-vintage-basketball-shoes',
      description: 'High-top vintage tribute: Aged sail leather, yellowed retro midsole, padded collar, and authentic 1984 Forum proportions.',
      price: 130,
      discount_price: 114,
      stock: 25,
      image_url: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 420,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Adidas', Cut: 'High-Top Silhouette', Leather: 'Premium Full-Grain Vintage Leather' }
    },
    {
      name: 'Adidas Rivalry Low 86 Retro Basketball Shoes',
      slug: 'adidas-rivalry-low-86-retro-shoes',
      description: 'Old-school B-ball vibes: Layered leather and suede construction, classic perforated vamp, and retro color-blocked rubber cupsole.',
      price: 100,
      discount_price: 84,
      stock: 35,
      image_url: 'https://images.unsplash.com/photo-1587563871167-1ee9c731aefb?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1587563871167-1ee9c731aefb?auto=format&fit=crop&w=800&q=80'],
      rating: 4.7,
      num_reviews: 310,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Adidas', Year: '1986 Basketball Archive', Upper: 'Leather & Suede Overlays' }
    },
    {
      name: 'Adidas SL 72 OG Shoes (Blue / Solar Red / Gum)',
      slug: 'adidas-sl-72-og-shoes-blue-solar-red-gum',
      description: 'The 1972 Munich Olympic Games running silhouette: Nylon upper with suede overlays, Ecotex tongue, and saw-tooth rubber outsole.',
      price: 100,
      discount_price: 90,
      stock: 35,
      image_url: 'https://images.unsplash.com/photo-1587563871167-1ee9c731aefb?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1587563871167-1ee9c731aefb?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 580,
      is_featured: false,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Adidas', Heritage: '1972 Super Light Running', Materials: 'Nylon & Suede Overlays' }
    },
    {
      name: 'Adidas Country OG Leather Vintage Runners',
      slug: 'adidas-country-og-leather-vintage-runners',
      description: 'Cross-country trail runner from the 1970s: Soft leather upper, split gum sole wrapping the heel, suede T-toe.',
      price: 100,
      discount_price: 89,
      stock: 25,
      image_url: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 210,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Adidas', Origin: '1973 Cross-Country Runner', Heel: 'Extended Gum Wrap Heel' }
    },
    {
      name: 'Adidas Response CL Retro Trail Running Shoes',
      slug: 'adidas-response-cl-retro-trail-running-shoes',
      description: '2000s dad-shoe trail aesthetics: Layered mesh and synthetic suede upper, EVA midsole, Formotion technology, and Torsion System arch bridge.',
      price: 130,
      discount_price: 109,
      stock: 30,
      image_url: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 390,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Adidas', Arch: 'Torsion System Midfoot Bridge', Style: 'Y2K Retro Runner' }
    },
    {
      name: 'Adidas Ozweego Chunky Tech Runners',
      slug: 'adidas-ozweego-chunky-tech-runners',
      description: 'Late-90s futurism: Signature translucent nylon support tubing, Adiprene+ forefoot cushioning, EVA midsole, sculptured lines.',
      price: 120,
      discount_price: 99,
      stock: 45,
      image_url: 'https://images.unsplash.com/photo-1587563871167-1ee9c731aefb?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1587563871167-1ee9c731aefb?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 940,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Adidas', Cushioning: 'Adiprene & Adiprene+', Design: 'Translucent Nylon Tubing' }
    },
    {
      name: 'Adidas Nizza Platform Canvas Shoes (Cloud White)',
      slug: 'adidas-nizza-platform-canvas-shoes',
      description: 'Elevated vulcanized canvas skate shoe: Chunky platform rubber sole, rubber toe bumper, contrast heel pull tab.',
      price: 75,
      discount_price: 64,
      stock: 60,
      image_url: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80'],
      rating: 4.7,
      num_reviews: 580,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Adidas', Sole: 'Platform Vulcanized Rubber', Upper: 'Durable Canvas' }
    },
    {
      name: 'Adidas Astir Y2K Chunky Women Sneakers',
      slug: 'adidas-astir-y2k-chunky-women-sneakers',
      description: 'Dramatic oversized eyelets inspired by early 2000s excess: Layered mixed material upper, sculpted EVA midsole.',
      price: 100,
      discount_price: 84,
      stock: 40,
      image_url: 'https://images.unsplash.com/photo-1587563871167-1ee9c731aefb?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1587563871167-1ee9c731aefb?auto=format&fit=crop&w=800&q=80'],
      rating: 4.7,
      num_reviews: 310,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Adidas', Style: 'Y2K Oversized Eyelets', Cushioning: 'Sculpted EVA' }
    },

    // --- 3. ADIDAS FOOTBALL & ATHLETICS (20 Models) ---
    {
      name: 'Adidas Predator 24 Elite Firm Ground Football Boots (Tongue)',
      slug: 'adidas-predator-24-elite-fg-tongue-boots',
      description: 'Fold-over tongue with strap, Strikeskin rubber fins on the forefoot for pinpoint swerve and shooting accuracy, Hybridtouch 2.0 synthetic upper, Controlframe 2.0 outsole.',
      price: 280,
      discount_price: 259,
      stock: 20,
      image_url: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80'],
      rating: 5.0,
      num_reviews: 410,
      is_featured: true,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Adidas', Technology: 'Strikeskin Grip Fins', Tongue: 'Fold-Over Tongue with Strap', Sole: 'Controlframe 2.0 FG' }
    },
    {
      name: 'Adidas Predator 24 Pro Laceless Firm Ground Boots',
      slug: 'adidas-predator-24-pro-laceless-fg-boots',
      description: 'Laceless engineered Primeknit collar creates seamless strike zone: High-definition 3D Strikeskin grip texture, TPU firm ground outsole.',
      price: 150,
      discount_price: 135,
      stock: 28,
      image_url: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 260,
      is_featured: false,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Adidas', Type: 'Laceless Strike Zone', Sole: 'Firm Ground (FG)' }
    },
    {
      name: 'Adidas F50 Elite Fast Reborn FG Football Boots',
      slug: 'adidas-f50-elite-fast-reborn-fg-boots',
      description: 'The return of pure football speed: Fibertouch upper with Sprintweb 3D texture, Compression Fit Tunnel Tongue, and Sprintframe 360 outsole with anatomical spine.',
      price: 260,
      discount_price: 239,
      stock: 24,
      image_url: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80'],
      rating: 5.0,
      num_reviews: 340,
      is_featured: true,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Adidas', Upper: 'Fibertouch with Sprintweb', Outsole: 'Sprintframe 360 Outsole', Weight: '182g Ultra-Speed' }
    },
    {
      name: 'Adidas F50 Pro Artificial Grass Football Boots',
      slug: 'adidas-f50-pro-ag-football-boots',
      description: 'Engineered specifically for 3G/4G synthetic turf pitches: Fibertouch upper, Sprintgrid texture, multi-stud AG outsole reducing joint stress.',
      price: 150,
      discount_price: 135,
      stock: 22,
      image_url: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 140,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Adidas', Pitch: 'Artificial Grass (AG) Studs', Weight: '190g' }
    },
    {
      name: 'Adidas Copa Pure 2 Elite Firm Ground Boots',
      slug: 'adidas-copa-pure-2-elite-fg-boots',
      description: 'Silky Fusionskin leather upper seamlessly fused with Primeknit collar: Quilted forefoot cushioning for timeless ball touch and comfort.',
      price: 230,
      discount_price: 209,
      stock: 18,
      image_url: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 210,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Adidas', Leather: 'Fusionskin Calf Leather', Collar: 'Primeknit Textile Collar' }
    },
    {
      name: 'Adidas Copa Gloro II Leather Football Boots',
      slug: 'adidas-copa-gloro-ii-leather-football-boots',
      description: 'Classic cow leather forefoot with fold-over tongue and elastic strap: Traditional stitched lines and conical studs.',
      price: 100,
      discount_price: 89,
      stock: 35,
      image_url: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 480,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Adidas', Material: 'Premium Cow Leather', Tongue: 'Fold-Over Tongue with Elastic Strap' }
    },
    {
      name: 'Adidas Copa Mundial Classic Firm Ground Boots',
      slug: 'adidas-copa-mundial-classic-fg-boots',
      description: 'The best-selling football boot in world history: Crafted in Germany with genuine kangaroo leather upper, direct-injected dual-density polyurethane outsole.',
      price: 160,
      discount_price: 149,
      stock: 40,
      image_url: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80'],
      rating: 5.0,
      num_reviews: 5400,
      is_featured: true,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Adidas', Origin: 'Made in Germany', Upper: 'K-Leather (Kangaroo Leather)' }
    },
    {
      name: 'Adidas Mundial Team Turf Soccer Shoes',
      slug: 'adidas-mundial-team-turf-soccer-shoes',
      description: 'Premium kangaroo leather turf shoes: Suede toe cap for extra durability, EVA wedge midsole, multi-stud rubber turf outsole.',
      price: 110,
      discount_price: 99,
      stock: 45,
      image_url: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 2100,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Adidas', Surface: 'Artificial Turf (TF)', Leather: 'K-Leather' }
    },
    {
      name: 'Adidas UEFA Champions League Pro Official Match Ball',
      slug: 'adidas-uefa-champions-league-pro-official-match-ball',
      description: 'FIFA Quality Pro certified official match ball: Thermally bonded seamless surface, textured star panels for predictable flight, butyl bladder for maximum air retention.',
      price: 170,
      discount_price: 149,
      stock: 35,
      image_url: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=800&q=80'],
      rating: 5.0,
      num_reviews: 480,
      is_featured: true,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Adidas', Certification: 'FIFA Quality Pro Certified', Construction: 'Thermally Bonded Seamless Surface' }
    },
    {
      name: 'Adidas Predator Pro Goalkeeper Gloves with URG 2.0 Latex',
      slug: 'adidas-predator-pro-goalkeeper-gloves-urg-2-0',
      description: 'URG 2.0 latex palm with superior shock absorption and grip in all weather conditions, Demonskin silicone backhand spikes for punch control, strapless knit entry.',
      price: 130,
      discount_price: 115,
      stock: 25,
      image_url: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 190,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Adidas', Palm: 'URG 2.0 High-Tack Latex', Cut: 'Negative Cut with Strapless Entry' }
    },
    {
      name: 'Adidas Tiro 24 Competition Training Track Pants',
      slug: 'adidas-tiro-24-competition-training-track-pants',
      description: 'The world’s most popular soccer training pants: AEROREADY moisture-absorbing fabric, tapered athletic fit, ankle zips for quick on/off over boots, zipped side pockets.',
      price: 55,
      discount_price: 45,
      stock: 120,
      image_url: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 4800,
      is_featured: true,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Adidas', Fabric: '100% Recycled Polyester Doubleknit AEROREADY', Ankle: 'Leg Ankle Zips', Fit: 'Slim Tapered Cut' }
    },
    {
      name: 'Adidas Tiro 24 Competition Training Track Jacket',
      slug: 'adidas-tiro-24-competition-training-track-jacket',
      description: 'Full-zip training jacket with stand-up collar: AEROREADY moisture management, zip pockets, 3-Stripes shoulder detailing.',
      price: 65,
      discount_price: 52,
      stock: 80,
      image_url: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 1200,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Adidas', Technology: 'AEROREADY Moisture Absorption', Closure: 'Full Zip with Stand-Up Collar' }
    },
    {
      name: 'Adidas Tiro 24 All-Weather Rain Jacket',
      slug: 'adidas-tiro-24-all-weather-rain-jacket',
      description: 'Water-repellent woven shell with packable hood: breathable mesh lining, zipped storm pockets, elastic cuffs.',
      price: 80,
      discount_price: 68,
      stock: 50,
      image_url: 'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1556905055-8f358a7a47b2?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 340,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Adidas', Weatherproofing: 'Water-Repellent DWR Finish', Hood: 'Packable Collar Hood' }
    },
    {
      name: 'Adidas Squadra 21 Short Sleeve Match Jersey',
      slug: 'adidas-squadra-21-short-sleeve-jersey',
      description: 'Lightweight match jersey engineered for high-intensity games: AEROREADY fabric, 3-Stripes on sleeve panels.',
      price: 35,
      discount_price: 28,
      stock: 140,
      image_url: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=800&q=80'],
      rating: 4.7,
      num_reviews: 1800,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Adidas', Material: '100% Recycled Polyester Interlock', Technology: 'AEROREADY' }
    },
    {
      name: 'Adidas Squadra 21 Athletic Football Shorts',
      slug: 'adidas-squadra-21-football-shorts',
      description: 'Classic soccer shorts with elastic waistband and internal drawcord: AEROREADY wicking, embroidered logo.',
      price: 30,
      discount_price: 24,
      stock: 160,
      image_url: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 2200,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Adidas', Waist: 'Elastic with Drawcord', Material: 'AEROREADY Polyester' }
    },
    {
      name: 'Adidas Milano 23 High Football Socks',
      slug: 'adidas-milano-23-football-socks',
      description: 'Knee-high performance football socks with anatomical left/right cushioning, ribbed ankle and arch support.',
      price: 15,
      discount_price: 12,
      stock: 200,
      image_url: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 1450,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Adidas', Fit: 'Left/Right Specific Ergonomic', Length: 'Knee-High' }
    },
    {
      name: 'Adidas Tiro League Shin Guards with Compression Sleeves',
      slug: 'adidas-tiro-league-shin-guards',
      description: 'Hard flexible shield with molded EVA backing and separate compression sleeve for locked-in shin protection.',
      price: 25,
      discount_price: 20,
      stock: 90,
      image_url: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=800&q=80'],
      rating: 4.7,
      num_reviews: 620,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Adidas', Backing: 'Molded EVA Foam', Sleeve: 'Breathable Compression Retention Sleeve' }
    },
    {
      name: 'Adidas Conext 24 Pro Football',
      slug: 'adidas-conext-24-pro-football',
      description: 'Official match ball for international tournaments: FIFA Quality Pro, seamless thermal bonding.',
      price: 160,
      discount_price: 139,
      stock: 30,
      image_url: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 210,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Adidas', Grade: 'FIFA Quality Pro', Surface: 'Thermally Bonded' }
    },
    {
      name: 'Adidas Tiro Club Ball (Size 5)',
      slug: 'adidas-tiro-club-ball-size-5',
      description: 'Durable training ball: Machine-stitched TPU cover with butyl bladder for weekly scrimmages and drills.',
      price: 25,
      discount_price: 20,
      stock: 110,
      image_url: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=800&q=80'],
      rating: 4.7,
      num_reviews: 1320,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Adidas', Size: '5 Standard', Construction: 'Machine-Stitched 100% TPU' }
    },
    {
      name: 'Adidas Classic Captains Armband',
      slug: 'adidas-classic-captains-armband',
      description: 'Elastic armband with bold contrast "C" print and hook-and-loop closure for team leaders.',
      price: 15,
      discount_price: 12,
      stock: 150,
      image_url: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 540,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Adidas', Closure: 'Hook-and-Loop Fastener', Material: 'Elastic Polyester' }
    },

    // --- 4. ADIDAS ADICOLOR, HOODIES & STREETWEAR APPAREL (22 Models) ---
    {
      name: 'Adidas Adicolor Classics Firebird Primeblue Track Top',
      slug: 'adidas-adicolor-classics-firebird-track-top',
      description: 'Iconic shiny tricot fabric with full zip and fold-down collar: Embroidered Trefoil logo on the chest, contrast 3-Stripes down both sleeves, Parley Ocean Plastic construction.',
      price: 85,
      discount_price: 72,
      stock: 65,
      image_url: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 1450,
      is_featured: true,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Adidas', Material: '100% Recycled Polyester Tricot', Logo: 'Embroidered Trefoil Chest Mark' }
    },
    {
      name: 'Adidas Adicolor Classics Firebird Track Pants',
      slug: 'adidas-adicolor-classics-firebird-track-pants',
      description: 'Straight-leg relaxed fit track pants in matching glossy tricot fabric: Drawcord on elastic waist, zip pockets, and pintuck pleat details down the front.',
      price: 75,
      discount_price: 64,
      stock: 70,
      image_url: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 1320,
      is_featured: false,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Adidas', Cut: 'Regular Straight Leg with Front Pleat', Fabric: 'Recycled Tricot' }
    },
    {
      name: 'Adidas Adicolor Classics Beckenbauer Tracksuit Jacket',
      slug: 'adidas-adicolor-classics-beckenbauer-tracksuit-jacket',
      description: 'The heavyweight original track top first introduced in 1967: Heavyweight doubleknit cotton-poly blend, ribbed cuffs, and archive retro collar.',
      price: 90,
      discount_price: 79,
      stock: 45,
      image_url: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 780,
      is_featured: true,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Adidas', Heritage: '1967 Franz Beckenbauer Tracksuit', Fabric: 'Heavyweight Cotton-Poly Doubleknit' }
    },
    {
      name: 'Adidas Adicolor Classics Beckenbauer Track Pants',
      slug: 'adidas-adicolor-classics-beckenbauer-track-pants',
      description: 'Slim tailored silhouette in heavyweight doubleknit fabric with front stitched creases, drawcord waist, zip side pockets.',
      price: 85,
      discount_price: 74,
      stock: 50,
      image_url: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 690,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Adidas', Fit: 'Slim Tailored', Fabric: 'Heavyweight Cotton Blend Doubleknit' }
    },
    {
      name: 'Adidas Adicolor SST Superstar Track Jacket',
      slug: 'adidas-adicolor-sst-superstar-track-jacket',
      description: 'Ribbed baseball-style collar, raglan sleeves with 3-Stripes, cotton-blend interlock fabric with embroidered Trefoil.',
      price: 80,
      discount_price: 68,
      stock: 60,
      image_url: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 980,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Adidas', Collar: 'Ribbed Baseball Collar', Sleeves: 'Raglan Sleeves' }
    },
    {
      name: 'Adidas Adicolor SST Superstar Track Pants',
      slug: 'adidas-adicolor-sst-superstar-track-pants',
      description: 'Tapered ribbed cuff track pants in soft interlock: side zip pockets, embroidered Trefoil on thigh.',
      price: 75,
      discount_price: 62,
      stock: 65,
      image_url: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 840,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Adidas', Cuffs: 'Ribbed Ankle Cuffs', Cut: 'Slim Fit' }
    },
    {
      name: 'Adidas Adicolor Trefoil Essentials French Terry Hoodie',
      slug: 'adidas-adicolor-trefoil-essentials-french-terry-hoodie',
      description: 'Heavyweight 100% cotton French terry pullover: Embroidered mini Trefoil logo, kangaroo front pocket, ribbed hem and cuffs, ultra-soft interior.',
      price: 70,
      discount_price: 59,
      stock: 90,
      image_url: 'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1556905055-8f358a7a47b2?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 2100,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Adidas', Material: '100% Cotton French Terry', Pocket: 'Kangaroo Front Pouch' }
    },
    {
      name: 'Adidas Adicolor Trefoil Essentials Crewneck Sweatshirt',
      slug: 'adidas-adicolor-trefoil-essentials-crewneck',
      description: 'Plush organic cotton French terry crewneck with embroidered Trefoil chest crest: raglan seams, ribbed crew collar.',
      price: 65,
      discount_price: 54,
      stock: 75,
      image_url: 'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1556905055-8f358a7a47b2?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 1320,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Adidas', Fabric: '100% Organic Cotton French Terry' }
    },
    {
      name: 'Adidas Adicolor Trefoil Essentials Jogger Sweatpants',
      slug: 'adidas-adicolor-trefoil-essentials-joggers',
      description: 'Everyday comfort joggers in French terry with elastic cuffs, drawcord waist, and dual deep side welt pockets.',
      price: 65,
      discount_price: 54,
      stock: 80,
      image_url: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 1650,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Adidas', Material: 'French Terry Cotton', Fit: 'Relaxed Jogger' }
    },
    {
      name: 'Adidas Z.N.E. Premium Full-Zip Zero-Negative-Energy Hoodie',
      slug: 'adidas-zne-premium-full-zip-hoodie',
      description: 'Engineered for athlete focus pre-competition: 4-way stretch doubleknit fabric, high funnel neck hood blocks distractions, concealed zip pockets.',
      price: 110,
      discount_price: 94,
      stock: 40,
      image_url: 'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1556905055-8f358a7a47b2?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 860,
      is_featured: true,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Adidas', Fabric: '4-Way Stretch Doubleknit', Hood: 'High Funnel Noise-Reducing Neck' }
    },
    {
      name: 'Adidas Z.N.E. Premium Tapered Sweatpants',
      slug: 'adidas-zne-premium-tapered-sweatpants',
      description: 'Structured 4-way stretch doubleknit pants matching the Z.N.E. hoodie: concealed zips, matte rubberized badges.',
      price: 95,
      discount_price: 82,
      stock: 45,
      image_url: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 540,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Adidas', Fabric: '4-Way Stretch Cotton-Poly Doubleknit' }
    },
    {
      name: 'Adidas Techfit Compression Long Sleeve Base Layer Top',
      slug: 'adidas-techfit-compression-long-sleeve-top',
      description: 'Sleek compressive fit focuses muscles for explosive power: AEROREADY sweat-wicking technology, mesh back panel for ventilation, anti-odor polygiene finish.',
      price: 45,
      discount_price: 36,
      stock: 80,
      image_url: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 940,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Adidas', Compression: 'Techfit Muscle-Support Fit', Ventilation: 'Rear Mesh Zone' }
    },
    {
      name: 'Adidas Techfit Compression Short Sleeve Training Tee',
      slug: 'adidas-techfit-compression-short-sleeve-tee',
      description: 'Lightweight compressive crewneck tee with ergonomic cut lines for unrestricted gym mobility: moisture-absorbing AEROREADY.',
      price: 38,
      discount_price: 30,
      stock: 90,
      image_url: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=800&q=80'],
      rating: 4.7,
      num_reviews: 780,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Adidas', Tech: 'Techfit Compression', Fabric: 'AEROREADY Recycled Poly' }
    },
    {
      name: 'Adidas Techfit Compression Full-Length Tights',
      slug: 'adidas-techfit-compression-full-length-tights',
      description: 'Medium compression leggings with 3D sculpted pouch, flatlock seams to prevent chafing, and jacquard branded elastic waistband.',
      price: 50,
      discount_price: 42,
      stock: 75,
      image_url: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 1100,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Adidas', Seams: 'Flatlock Anti-Chafe Seams', Length: 'Full-Length Compressive' }
    },
    {
      name: 'Adidas AEROREADY Designed for Movement 3-Stripes Tee',
      slug: 'adidas-aeroready-designed-for-movement-tee',
      description: 'Breathable workout t-shirt featuring angled side seams for overhead lifts and sweat-wicking AEROREADY fabric.',
      price: 35,
      discount_price: 28,
      stock: 120,
      image_url: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 2400,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Adidas', Cut: 'FreeLift Overhead Mobility Pattern', Fabric: 'AEROREADY Mock Eyelet' }
    },
    {
      name: 'Adidas Own the Run 3-Stripes Running T-Shirt',
      slug: 'adidas-own-the-run-3-stripes-running-tee',
      description: '360-degree reflectivity for low-light visibility, breathable jacquard knit structure, sweat-wicking comfort on long road runs.',
      price: 40,
      discount_price: 32,
      stock: 95,
      image_url: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 1420,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Adidas', Visibility: '360° Reflective Details', Fabric: '100% Recycled Poly Jacquard' }
    },
    {
      name: 'Adidas Own the Run 5-Inch Running Shorts with Liner',
      slug: 'adidas-own-the-run-5-inch-running-shorts',
      description: 'Internal breathable brief liner, sweat-guard zip back pocket for phone/keys, reflective logo, side slit hems.',
      price: 45,
      discount_price: 36,
      stock: 110,
      image_url: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 1980,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Adidas', Inseam: '5 Inch Running Inseam', Liner: 'Built-in Mesh Brief Liner' }
    },
    {
      name: 'Adidas Marathon 20 Women Lightweight Running Shorts',
      slug: 'adidas-marathon-20-women-running-shorts',
      description: 'Iconic dolphin hem running shorts: 3-inch inseam, inner key pocket, 360 reflectivity, breathable mesh side inserts.',
      price: 35,
      discount_price: 28,
      stock: 90,
      image_url: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 1650,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Adidas', Hem: 'Curved Dolphin Hem', Inseam: '3 Inch Inseam' }
    },
    {
      name: 'Adidas Helionic Hooded Down Puffer Jacket',
      slug: 'adidas-helionic-hooded-down-puffer-jacket',
      description: '600-fill duck down insulation with no-stitch Conextbaffles wind and water-repellent design: drawcord hem, elastic hood.',
      price: 160,
      discount_price: 139,
      stock: 35,
      image_url: 'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1556905055-8f358a7a47b2?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 740,
      is_featured: true,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Adidas', Insulation: '80/20 Duck Down (600 Fill Power)', Construction: 'Conextbaffles Stitchless Down Baffles' }
    },
    {
      name: 'Adidas Essentials 3-Stripes Tricot Track Jacket',
      slug: 'adidas-essentials-3-stripes-tricot-track-jacket',
      description: 'Classic everyday track top in recycled polyester tricot: Stand-up collar, slip-in side pockets, ribbed cuffs.',
      price: 55,
      discount_price: 44,
      stock: 80,
      image_url: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=800&q=80'],
      rating: 4.7,
      num_reviews: 2100,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Adidas', Fabric: '100% Recycled Polyester Tricot' }
    },
    {
      name: 'Adidas Adicolor Oversized Trefoil Tee (Wonder White)',
      slug: 'adidas-adicolor-oversized-trefoil-tee',
      description: 'Relaxed loose boxy fit t-shirt in heavyweight single jersey cotton with center-chest flocked Trefoil print.',
      price: 40,
      discount_price: 32,
      stock: 85,
      image_url: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 1120,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Adidas', Fit: 'Oversized Boxy Cut', Material: '100% Heavy Cotton Jersey' }
    },
    {
      name: 'Adidas 3-Stripes Doubleknit Bomber Jacket',
      slug: 'adidas-3-stripes-doubleknit-bomber-jacket',
      description: 'Modern street bomber silhouette: snap-button front, ribbed baseball collar, matte tonal 3-Stripes along arms.',
      price: 85,
      discount_price: 72,
      stock: 45,
      image_url: 'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1556905055-8f358a7a47b2?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 410,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Adidas', Closure: 'Front Snap Buttons', Fabric: 'Doubleknit Polyester-Cotton' }
    },

    // --- 5. ADIDAS TERREX OUTDOOR & ADVENTURE (14 Models) ---
    {
      name: 'Adidas Terrex Free Hiker 2.0 GORE-TEX Hiking Boots',
      slug: 'adidas-terrex-free-hiker-2-0-gore-tex-boots',
      description: 'Next-level trail comfort: Waterproof breathable GORE-TEX membrane, full-length BOOST midsole for rock cushioning, Continental rubber lugged outsole, and sock-like collar.',
      price: 230,
      discount_price: 199,
      stock: 30,
      image_url: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 580,
      is_featured: true,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Adidas', Membrane: 'GORE-TEX Waterproof Extended Comfort', Cushioning: 'Full-Length BOOST Midsole', Grip: 'Continental Rubber Lugged Sole' }
    },
    {
      name: 'Adidas Terrex Free Hiker 2.0 Low GORE-TEX Shoes',
      slug: 'adidas-terrex-free-hiker-2-0-low-gtx-shoes',
      description: 'Low-cut agile fast-hiking shoe: BOOST cushioning, waterproof GORE-TEX lining, external EVA stability frame, Continental rubber.',
      price: 200,
      discount_price: 179,
      stock: 28,
      image_url: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 340,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Adidas', Cut: 'Low-Cut Agile', Cushioning: 'BOOST' }
    },
    {
      name: 'Adidas Terrex Swift R3 GORE-TEX Fast Hiking Shoes',
      slug: 'adidas-terrex-swift-r3-gore-tex-shoes',
      description: 'Speed hiking weapon: Full-length rock protection plate, GORE-TEX lining, Lightstrike EVA midsole, Continental rubber compound with all-terrain climbing zones.',
      price: 160,
      discount_price: 139,
      stock: 35,
      image_url: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 420,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Adidas', Waterproofing: 'GORE-TEX Membrane', Plate: 'Underfoot Rock Protection Plate' }
    },
    {
      name: 'Adidas Terrex Swift R3 Mid GORE-TEX Trail Boots',
      slug: 'adidas-terrex-swift-r3-mid-gore-tex-boots',
      description: 'Mid-cut ankle support speed hiker: Pro-Moderator medial support, molded heel cup, Continental rubber with 4.5mm lugs.',
      price: 180,
      discount_price: 154,
      stock: 25,
      image_url: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 310,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Adidas', Cut: 'Mid-Ankle Support', Protection: 'Pro-Moderator Stability' }
    },
    {
      name: 'Adidas Terrex Techrock GORE-TEX Pro Mountain Jacket',
      slug: 'adidas-terrex-techrock-gore-tex-pro-jacket',
      description: 'Expedition-grade mountaineering shell: 3-layer GORE-TEX Pro most rugged fabric, fully seam-sealed, helmet-compatible hood, pit zips, RECCO rescue reflector.',
      price: 550,
      discount_price: 489,
      stock: 12,
      image_url: 'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1556905055-8f358a7a47b2?auto=format&fit=crop&w=800&q=80'],
      rating: 5.0,
      num_reviews: 95,
      is_featured: true,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Adidas', Shell: '3-Layer GORE-TEX Pro Most Rugged', Safety: 'RECCO Avalanche Rescue Reflector', Hood: 'Helmet-Compatible 3-Way Adjustable' }
    },
    {
      name: 'Adidas Terrex Agravic Speed Ultra Trail Running Shoes',
      slug: 'adidas-terrex-agravic-speed-ultra-shoes',
      description: 'Ultra-trail race winner: Dual Lightstrike Pro foam with Energy Rods, dynamic rocker sole, Continental lightweight rubber with 3.5mm aggressive lugs.',
      price: 220,
      discount_price: 199,
      stock: 25,
      image_url: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 180,
      is_featured: false,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Adidas', Foam: 'Lightstrike Pro Dual-Density', Lugs: '3.5mm Continental Rubber Lugs' }
    },
    {
      name: 'Adidas Terrex Agravic Flow 2.0 Trail Shoes',
      slug: 'adidas-terrex-agravic-flow-2-0-shoes',
      description: 'Versatile road-to-trail shoe: Lightstrike cushioning, abrasion-resistant engineered mesh, mudguard overlays, Continental rubber grip.',
      price: 140,
      discount_price: 119,
      stock: 35,
      image_url: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 290,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Adidas', Use: 'Road-to-Trail Hybrid', Cushioning: 'Lightstrike' }
    },
    {
      name: 'Adidas Terrex Trailmaker 2.0 GORE-TEX Hiking Shoes',
      slug: 'adidas-terrex-trailmaker-2-0-gtx-shoes',
      description: 'Lightweight trail walking shoe combining running shoe comfort with hiking durability: GORE-TEX waterproof membrane, EVA midsole.',
      price: 120,
      discount_price: 99,
      stock: 45,
      image_url: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80'],
      rating: 4.7,
      num_reviews: 410,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Adidas', Lining: 'GORE-TEX Waterproof', Outsole: 'Continental Rubber' }
    },
    {
      name: 'Adidas Terrex Soulstride Flow Long-Distance Trail Runners',
      slug: 'adidas-terrex-soulstride-flow-shoes',
      description: 'Thick REPETITOR foam midsole delivers plush impact protection on rocky ultra-distance trails: Continental rubber outsole.',
      price: 130,
      discount_price: 109,
      stock: 30,
      image_url: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 160,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Adidas', Midsole: 'REPETITOR Ultra-Trail Foam', Rocker: 'Curved Rocker Shape' }
    },
    {
      name: 'Adidas Terrex Multi Rain.Rdy 2.5L Waterproof Shell',
      slug: 'adidas-terrex-multi-rain-rdy-waterproof-shell',
      description: '2.5-layer packable waterproof shell with RAIN.RDY technology: packs into its own pocket, bungee-adjustable hem and hood.',
      price: 120,
      discount_price: 99,
      stock: 50,
      image_url: 'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1556905055-8f358a7a47b2?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 380,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Adidas', Technology: 'RAIN.RDY 10K Waterproofing', Packability: 'Stows in Pocket' }
    },
    {
      name: 'Adidas Terrex Xperior Softshell Wind Pants',
      slug: 'adidas-terrex-xperior-softshell-pants',
      description: 'Wind-resistant front panels and breathable stretch back panels for cross-country skiing, mountaineering, and cold weather trail treks.',
      price: 110,
      discount_price: 94,
      stock: 35,
      image_url: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 210,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Adidas', Windproof: 'GORE-TEX Infinium Windstopper Fabric' }
    },
    {
      name: 'Adidas Terrex Agravic Windweave Pro Lightweight Jacket',
      slug: 'adidas-terrex-agravic-windweave-pro-jacket',
      description: 'Featherlight 70g windbreaker with body-mapped variable air permeability: packs smaller than an energy bar.',
      price: 140,
      discount_price: 119,
      stock: 25,
      image_url: 'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1556905055-8f358a7a47b2?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 140,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Adidas', Weight: '70 Grams Ultra-Light', Tech: 'Windweave Body-Mapped Weave' }
    },
    {
      name: 'Adidas Terrex Primaloft Gold Insulated Puffer Jacket',
      slug: 'adidas-terrex-primaloft-gold-puffer-jacket',
      description: 'Ultralight synthetic insulation performs even when wet: Primaloft Gold synthetic down, Pertex Quantum outer shell.',
      price: 200,
      discount_price: 169,
      stock: 22,
      image_url: 'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1556905055-8f358a7a47b2?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 260,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Adidas', Insulation: 'PrimaLoft Gold Eco 100% Recycled', Shell: 'Pertex Quantum' }
    },
    {
      name: 'Adidas Terrex Trail 12L Hydration Vest Backpack',
      slug: 'adidas-terrex-trail-12l-hydration-vest',
      description: 'Includes dual 500ml HydraPak soft flasks: pole attachment loops, whistle buckle, breathable mesh harness.',
      price: 140,
      discount_price: 119,
      stock: 30,
      image_url: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 175,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Adidas', Capacity: '12 Liters', Flasks: '2x 500ml Soft Flasks Included' }
    },

    // --- 6. ADIDAS ACCESSORIES & EQUIPMENT (10 Models) ---
    {
      name: 'Adidas Classic 3-Stripes 27.5L Everyday Backpack',
      slug: 'adidas-classic-3-stripes-everyday-backpack',
      description: 'Durable recycled polyester plain weave with TPE coated bottom: Padded laptop compartment fits up to 16", dual side water bottle pockets, air-mesh shoulder straps.',
      price: 45,
      discount_price: 36,
      stock: 100,
      image_url: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 2100,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Adidas', Capacity: '27.5 Liters', Compartment: 'Internal Padded 16" Laptop Sleeve', Base: 'TPE Coated Water-Resistant Base' }
    },
    {
      name: 'Adidas Power VI Training Backpack with Loadspring Straps',
      slug: 'adidas-power-vi-training-backpack',
      description: 'Loadspring shock-absorbing shoulder straps, side compression straps, coated base, external padded laptop zip compartment.',
      price: 50,
      discount_price: 42,
      stock: 80,
      image_url: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 1650,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Adidas', Straps: 'Loadspring Shock Absorbers', Capacity: '23.5 Liters' }
    },
    {
      name: 'Adidas Linear Medium 39L Training Duffel Bag',
      slug: 'adidas-linear-medium-training-duffel-bag',
      description: 'Separate ventilated shoe tunnel compartment, padded adjustable shoulder strap, dual carry handles, and end slip-in mesh pocket.',
      price: 40,
      discount_price: 32,
      stock: 80,
      image_url: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 1420,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Adidas', Capacity: '39 Liters', ShoePocket: 'Dedicated Ventilated Footwear Tunnel' }
    },
    {
      name: 'Adidas Defender Large 65L Team Duffel Bag',
      slug: 'adidas-defender-large-65l-team-duffel-bag',
      description: 'Heavyweight team duffel: water-resistant base material, dual zip end pockets, spacious main cavern for equipment.',
      price: 55,
      discount_price: 46,
      stock: 60,
      image_url: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 980,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Adidas', Capacity: '65 Liters', Material: 'Hydro-Shield Water-Resistant Base' }
    },
    {
      name: 'Adidas Tiro League Drawstring Gym Sack',
      slug: 'adidas-tiro-league-gym-sack',
      description: 'Drawstring closure doubles as shoulder straps, side zip pocket for valuables, quick grab-and-go gym storage.',
      price: 20,
      discount_price: 16,
      stock: 150,
      image_url: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 2400,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Adidas', Closure: 'Dual Drawcord Cinch', Pocket: 'Side Zip Stash Pocket' }
    },
    {
      name: 'Adidas Cushioned Crew Socks 3-Pack with Arch Compression',
      slug: 'adidas-cushioned-crew-socks-3-pack',
      description: 'Full footbed heel-to-toe cushioning, linked toe seam for smooth feel, and integrated arch support compression band.',
      price: 20,
      discount_price: 16,
      stock: 150,
      image_url: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 3400,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Adidas', Quantity: '3 Pairs Pack', Cushioning: 'Heel & Toe High-Density Terry Pad' }
    },
    {
      name: 'Adidas Cushioned Low-Cut Ankle Socks 3-Pack',
      slug: 'adidas-cushioned-low-cut-ankle-socks-3-pack',
      description: 'Low-profile silhouette sitting just above athletic sneakers: arch compression, breathable mesh top instep.',
      price: 18,
      discount_price: 14,
      stock: 140,
      image_url: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 2100,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Adidas', Cut: 'Low-Cut Ankle Length', Quantity: '3 Pairs' }
    },
    {
      name: 'Adidas Superlite Performance Running Hat with UPF 50',
      slug: 'adidas-superlite-performance-running-hat',
      description: 'Featherweight 6-panel performance cap: AEROREADY sweatband, laser-perforated side ventilation holes, UPF 50 UV sun protection, hook-and-loop back closure.',
      price: 26,
      discount_price: 22,
      stock: 90,
      image_url: 'https://images.unsplash.com/photo-1588850561407-ed78c282e89b?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1588850561407-ed78c282e89b?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 890,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Adidas', Protection: 'UPF 50 Sun Shield', Sweatband: 'AEROREADY Moisture Wicking' }
    },
    {
      name: 'Adidas Metal Badge Classic Strapback Cap',
      slug: 'adidas-metal-badge-classic-strapback-cap',
      description: 'Curved brim with raised metallic matte Trefoil badge on the crown: adjustable back strap with metal buckle clasp.',
      price: 30,
      discount_price: 25,
      stock: 75,
      image_url: 'https://images.unsplash.com/photo-1588850561407-ed78c282e89b?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1588850561407-ed78c282e89b?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 620,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Adidas', Badge: 'Matte Zinc Metal Trefoil Emblem', Closure: 'Adjustable Buckle' }
    },
    {
      name: 'Adidas 1L Stainless Steel Double-Wall Water Bottle',
      slug: 'adidas-1l-stainless-steel-water-bottle',
      description: 'BPA-free vacuum insulated stainless steel: keeps drinks ice cold for 24 hours or hot for 12 hours, loop lid handle.',
      price: 35,
      discount_price: 29,
      stock: 85,
      image_url: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 1400,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Adidas', Capacity: '1.0 Liter (32 oz)', Insulation: 'Double-Wall Vacuum Insulated' }
    }
  ];
};
