// backend/utils/boseProductsData.js
// 108 Unique, Non-Repeating Official Bose Products (QuietComfort Ultra, Smart Soundbars & Bass Modules, SoundLink Max/Flex, S1 Pro+ PA, Frames & Pro Audio)

export const getBoseProducts = (categoryId) => {
  return [
    // --- 1. BOSE QUIETCOMFORT HEADPHONES & AVIATION (20 Models) ---
    {
      name: 'Bose QuietComfort Ultra Wireless ANC Headphones',
      slug: 'bose-quietcomfort-ultra-wireless-anc-headphones',
      description: 'World-class active noise cancellation with breakthrough Bose Immersive Audio: CustomTune sound calibration tailored to your ear canal, ultra-plush protein leather cushions, Snapdragon Sound lossless audio, and up to 24-hour battery life.',
      price: 429,
      discount_price: 379,
      stock: 50,
      image_url: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80'],
      rating: 5.0,
      num_reviews: 1420,
      is_featured: true,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Bose', ANC: 'World-Class Bose Active Noise Cancelling', Audio: 'Bose Immersive Audio Spatial Tech', Codec: 'Snapdragon Sound / aptX Adaptive / AAC', Battery: '24 Hours (18 Hours with Immersive Audio)' }
    },
    {
      name: 'Bose QuietComfort Wireless Headphones 2024 Edition',
      slug: 'bose-quietcomfort-wireless-headphones-2024-edition',
      description: 'Legendary noise cancelling icon updated: Adjustable Quiet and Aware modes, customizable EQ, plush synthetic leather earcups, multi-point Bluetooth connectivity, and 24 hours of play time.',
      price: 349,
      discount_price: 299,
      stock: 65,
      image_url: 'https://images.unsplash.com/photo-1546435770-a3e426bf472b?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1546435770-a3e426bf472b?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 1890,
      is_featured: true,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Bose', NoiseCancellation: 'Quiet / Aware / Custom Modes', BatteryLife: '24 Hours Playtime with USB-C Fast Charge', Weight: '240g' }
    },
    {
      name: 'Bose Noise Cancelling Headphones 700',
      slug: 'bose-noise-cancelling-headphones-700',
      description: 'Futuristic streamlined steel headband design: 11 levels of controllable active noise cancellation, revolutionary 4-microphone voice pickup array, capacitive touch controls, and audio AR.',
      price: 379,
      discount_price: 329,
      stock: 45,
      image_url: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 2450,
      is_featured: true,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Bose', Headband: 'Streamlined Stainless Steel', ANCLevels: '11 Discrete Noise Cancelling Levels', Microphones: '8 Microphones Total' }
    },
    {
      name: 'Bose QuietComfort 45 SE ANC Headphones',
      slug: 'bose-quietcomfort-45-se-anc-headphones',
      description: 'The benchmark for frequent fliers: TriPort acoustic headphone architecture, volume-optimized Active EQ, soft impact-resistant glass-filled nylon headband, and 22-hour battery.',
      price: 329,
      discount_price: 269,
      stock: 80,
      image_url: 'https://images.unsplash.com/photo-1546435770-a3e426bf472b?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1546435770-a3e426bf472b?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 3100,
      is_featured: false,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Bose', Architecture: 'TriPort Acoustic Headphone Structure', Battery: '22 Hours Battery Life', Charging: 'USB-C Quick Charge (15 min = 3 hrs)' }
    },
    {
      name: 'Bose QuietComfort 35 II Heritage Wireless Headphones',
      slug: 'bose-quietcomfort-35-ii-heritage-wireless-headphones',
      description: 'The golden classic of travel audio: Dual-microphone noise-rejecting system, Alcantara luxury headband wrap, volume-optimized EQ, and physical action button.',
      price: 299,
      discount_price: 239,
      stock: 40,
      image_url: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 4800,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Bose', Material: 'Glass-Filled Nylon & Alcantara', Battery: '20 Hours Wireless Playtime' }
    },
    {
      name: 'Bose A30 Aviation Headset with Dual Plug',
      slug: 'bose-a30-aviation-headset-with-dual-plug',
      description: 'Bose premier aviation headset for pilots: 3 selectable modes of active noise cancellation, 20% less clamping force than A20, FAA TSO and EASA E/TSO-C139a certified, and Bluetooth audio.',
      price: 1299,
      discount_price: 1249,
      stock: 20,
      image_url: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80'],
      rating: 5.0,
      num_reviews: 320,
      is_featured: true,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Bose Aviation', Certification: 'FAA TSO & EASA E/TSO-C139a', PlugType: 'Dual General Aviation Plugs (PJ-068 / PJ-055)', Weight: '404g' }
    },
    {
      name: 'Bose ProFlight Series 2 Aviation Headset',
      slug: 'bose-proflight-series-2-aviation-headset',
      description: 'Lightweight in-ear aviation headset designed for pressurized turbine aircraft: Weighs only 128g, digital active noise cancellation with tap control for talk-through, and Bluetooth.',
      price: 1049,
      discount_price: 999,
      stock: 18,
      image_url: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 180,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Bose Aviation', FormFactor: 'In-Ear Lightweight (128g on head)', TalkThrough: 'Double-Tap Earbud Talk-Through Control' }
    },
    {
      name: 'Bose QuietComfort Ultra Custom Diamond Edition Headphones',
      slug: 'bose-quietcomfort-ultra-custom-diamond-edition-headphones',
      description: '60th anniversary limited edition: Iridescent diamond sheen earcups, polished metal yoke arms, custom embroidered travel case, Immersive Audio spatial engine.',
      price: 479,
      discount_price: 449,
      stock: 25,
      image_url: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80'],
      rating: 5.0,
      num_reviews: 210,
      is_featured: true,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Bose 60th Anniversary', Finish: 'Diamond Sheen Lustre & Polished Aluminum', Feature: 'Bose Spatial Immersive Audio' }
    },
    {
      name: 'Bose SoundLink Around-Ear Wireless Headphones II',
      slug: 'bose-soundlink-around-ear-wireless-headphones-ii',
      description: 'Pure wireless acoustic clarity: Deep immersive sound with TriPort technology and Active EQ, seamless multi-point Bluetooth switching between 2 devices, and 15-hour battery.',
      price: 229,
      discount_price: 179,
      stock: 50,
      image_url: 'https://images.unsplash.com/photo-1546435770-a3e426bf472b?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1546435770-a3e426bf472b?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 1450,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Bose', Audio: 'TriPort Technology & Active EQ', Bluetooth: 'Multi-Point Bluetooth 5.0' }
    },
    {
      name: 'Bose QuietComfort 25 Acoustic Noise Cancelling Headphones',
      slug: 'bose-quietcomfort-25-acoustic-noise-cancelling-headphones',
      description: 'Heritage wired audiophile edition: AAA battery-powered analog active noise reduction, foldable travel design, 3.5mm inline microphone cable, and lightweight comfort.',
      price: 199,
      discount_price: 149,
      stock: 30,
      image_url: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 890,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Bose Heritage', Connectivity: '3.5mm Wired Audio Cable', Power: '1x AAA Battery (Up to 35 Hours ANC)' }
    },
    {
      name: 'Bose QuietComfort 15 Acoustic Noise Cancelling Headphones',
      slug: 'bose-quietcomfort-15-acoustic-noise-cancelling-headphones',
      description: 'The historic aviation classic that revolutionized commercial air travel: Circumaural ear cushions, advanced microphone placement inside and outside earcups.',
      price: 179,
      discount_price: 139,
      stock: 20,
      image_url: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 620,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Bose Classic', Type: 'Wired Active Noise Cancelling Headphones' }
    },
    {
      name: 'Bose QuietPoint Active Studio ANC Monitoring Headphones',
      slug: 'bose-quietpoint-active-studio-anc-monitoring-headphones',
      description: 'Engineered for audio engineers and producers: Neutral flat response monitoring curve with switchable pro-grade ANC, detachable 3-meter coiled cable, and gold 1/4 adapter.',
      price: 349,
      discount_price: 299,
      stock: 35,
      image_url: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 290,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Bose Professional', Response: 'Linear Flat Studio Acoustic Profile', Cable: '3m Detachable Coiled Pro Cable' }
    },
    {
      name: 'Bose SoundTrue Around-Ear II Studio Headphones',
      slug: 'bose-soundtrue-around-ear-ii-studio-headphones',
      description: 'Featherlight wired passive headphones: Engineered for natural vocals and crisp acoustics with padded memory foam ear cushions and slim contour headband.',
      price: 149,
      discount_price: 119,
      stock: 45,
      image_url: 'https://images.unsplash.com/photo-1546435770-a3e426bf472b?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1546435770-a3e426bf472b?auto=format&fit=crop&w=800&q=80'],
      rating: 4.7,
      num_reviews: 730,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Bose', Driver: 'TriPort High-Fidelity Dynamic Drivers', Weight: '185g Ultra-Lightweight' }
    },
    {
      name: 'Bose QuietComfort Ultra Special Edition Cypress Green',
      slug: 'bose-quietcomfort-ultra-special-edition-cypress-green',
      description: 'Nature-inspired deep cypress green finish with brass gold aluminum accents, CustomTune audio tailoring, Immersive Audio, and 24-hour battery.',
      price: 429,
      discount_price: 389,
      stock: 30,
      image_url: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80'],
      rating: 5.0,
      num_reviews: 310,
      is_featured: false,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Bose', Colorway: 'Limited Edition Cypress Green & Brass', Audio: 'Bose Immersive Audio Spatial' }
    },
    {
      name: 'Bose QuietComfort Ultra Moonstone Blue Limited Edition',
      slug: 'bose-quietcomfort-ultra-moonstone-blue-limited-edition',
      description: 'Sleek celestial matte blue colorway: Silver metal yokes, ultra-soft matching ear pads, Immersive Audio spatial sound stage, and 24 hours playtime.',
      price: 429,
      discount_price: 389,
      stock: 28,
      image_url: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80'],
      rating: 5.0,
      num_reviews: 280,
      is_featured: false,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Bose', Colorway: 'Moonstone Blue Matte with Silver Accents', Tech: 'CustomTune Personal Audio' }
    },
    {
      name: 'Bose QuietComfort Sandstone Neutral Edition',
      slug: 'bose-quietcomfort-sandstone-neutral-edition',
      description: 'Warm sandstone earthy aesthetic: Quiet and Aware noise cancellation modes, wind-noise reduction algorithm, and plush ear cushions.',
      price: 349,
      discount_price: 299,
      stock: 40,
      image_url: 'https://images.unsplash.com/photo-1546435770-a3e426bf472b?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1546435770-a3e426bf472b?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 420,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Bose', Color: 'Sandstone Neutral Matte', Battery: '24 Hours Playtime' }
    },
    {
      name: 'Bose OE2 SoundTrue On-Ear Audio Headphones',
      slug: 'bose-oe2-soundtrue-on-ear-audio-headphones',
      description: 'Compact on-ear design: Memory foam ear cushions resting softly on ears, collapsible fold-flat headband, and detailed sound profile.',
      price: 119,
      discount_price: 89,
      stock: 50,
      image_url: 'https://images.unsplash.com/photo-1546435770-a3e426bf472b?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1546435770-a3e426bf472b?auto=format&fit=crop&w=800&q=80'],
      rating: 4.7,
      num_reviews: 350,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Bose', Fit: 'On-Ear (Supra-aural)', Weight: '140g' }
    },
    {
      name: 'Bose Aviation Dual Plug to XLR5 Adapter Cable',
      slug: 'bose-aviation-dual-plug-to-xlr5-adapter-cable',
      description: 'Heavy-duty shielded aviation interface cable converting standard twin GA plugs (PJ-068/PJ-055) to 5-pin XLR5 aircraft power connections with electret mic bias.',
      price: 149,
      discount_price: 129,
      stock: 40,
      image_url: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 110,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Bose Aviation Accessories', Connector: 'Dual GA Plugs to XLR5 Male', Shielding: 'High-Flex Multi-Conductor Shield' }
    },
    {
      name: 'Bose QuietComfort Deluxe Hard Shell Travel Carry Case',
      slug: 'bose-quietcomfort-deluxe-hard-shell-travel-carry-case',
      description: 'Molded EVA shock-absorbing protective case: Ballistic nylon exterior, plush velour interior with cable mesh pocket and airplane adapter slot.',
      price: 39,
      discount_price: 32,
      stock: 90,
      image_url: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 580,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Bose Official Accessory', Compatibility: 'Bose QC Ultra, QC 45, QC 35 II, QC Headphones', Material: 'Molded EVA Hard Shell' }
    },
    {
      name: 'Bose Replacement Protein Leather Ear Cushion Kit QC Ultra',
      slug: 'bose-replacement-protein-leather-ear-cushion-kit-qc-ultra',
      description: 'Factory original replacement ear cushions: Ultra-soft protein leather with acoustic scrim filters, snap-in installation ring, and high-density memory foam.',
      price: 34,
      discount_price: 29,
      stock: 120,
      image_url: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 840,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Bose Official Parts', Includes: '1 Pair Cushions & 1 Pair Scrim Inserts', Material: 'Acoustic Memory Foam & Protein Leather' }
    },

    // --- 2. BOSE QUIETCOMFORT EARBUDS & OPEN AUDIO WEARABLES (20 Models) ---
    {
      name: 'Bose QuietComfort Ultra True Wireless Earbuds',
      slug: 'bose-quietcomfort-ultra-true-wireless-earbuds',
      description: 'The pinnacle of in-ear active noise cancelling: CustomTune audio calibration tailored specifically to your unique ears, spatial Bose Immersive Audio, 9 ear-tip fit combos, IPX4 water resistance.',
      price: 299,
      discount_price: 249,
      stock: 65,
      image_url: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=800&q=80'],
      rating: 5.0,
      num_reviews: 1890,
      is_featured: true,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Bose', ANC: 'CustomTune Personalized Noise Cancellation', Spatial: 'Bose Immersive Audio', Battery: '6 Hours (24 Hours with Case)', WaterResistance: 'IPX4' }
    },
    {
      name: 'Bose Ultra Open Earbuds with OpenAudio Technology',
      slug: 'bose-ultra-open-earbuds-with-openaudio-technology',
      description: 'Fashion cuff meets private sound: Flexible silicone-coated comfort barrel that clips securely to outer ear, OpenAudio dipole transducer that beams sound solely into your ear canal without blocking ambient awareness.',
      price: 299,
      discount_price: 269,
      stock: 55,
      image_url: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 940,
      is_featured: true,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Bose', Design: 'Flexible Ear-Cuff Design', Audio: 'Bose OpenAudio Directional Acoustic System', Battery: '7.5 Hours Playtime (48 Hours Standby)' }
    },
    {
      name: 'Bose QuietComfort Earbuds II CustomTune Sound',
      slug: 'bose-quietcomfort-earbuds-ii-customtune-sound',
      description: 'Personalized noise cancellation that analyzes ear canal shape every time you put them in: Independent stability bands and umbrella silicone tips, active noise reduction microphones.',
      price: 279,
      discount_price: 219,
      stock: 70,
      image_url: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 2680,
      is_featured: false,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Bose', SoundTech: 'CustomTune Sound Calibration', Microphones: '4 Microphones per Earbud', Battery: '6 Hours (24 with Case)' }
    },
    {
      name: 'Bose Sport Earbuds True Wireless Fitness',
      slug: 'bose-sport-earbuds-true-wireless-fitness',
      description: 'Engineered for your best workout: StayHear Max silicone tips that stay locked in during sprints, volume-optimized active EQ, IPX4 sweat and weather resistance, and touch controls.',
      price: 179,
      discount_price: 139,
      stock: 80,
      image_url: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 1950,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Bose Sport', EarTips: 'StayHear Max Umbrella Tips', WaterRating: 'IPX4 Sweat Resistant', Battery: '5 Hours Playtime' }
    },
    {
      name: 'Bose QuietComfort Earbuds 1st Gen Wireless Charging',
      slug: 'bose-quietcomfort-earbuds-1st-gen-wireless-charging',
      description: 'Acoustic noise cancellation in compact earbuds: 11 levels of active noise reduction, Qi wireless charging charging case, and rich lifelike sound.',
      price: 249,
      discount_price: 179,
      stock: 40,
      image_url: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 3200,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Bose', Charging: 'Qi Wireless Charging Case Included', NoiseCancelling: '11 Controllable ANC Presets' }
    },
    {
      name: 'Bose Soundsport Free True Wireless Sport Earbuds',
      slug: 'bose-soundsport-free-true-wireless-sport-earbuds',
      description: 'Rugged wireless workout performance: StayHear+ Sport tips with wing fin grip, volume-optimized EQ, IPX4 rating, and Find My Buds tracking via Bose Connect app.',
      price: 199,
      discount_price: 129,
      stock: 45,
      image_url: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=800&q=80'],
      rating: 4.7,
      num_reviews: 2100,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Bose Sport', WingTip: 'StayHear+ Sport Ergonomic Wings', Tracking: 'Bose Connect Location Tracking' }
    },
    {
      name: 'Bose Soundsport Wireless In-Ear Earphones',
      slug: 'bose-soundsport-wireless-in-ear-earphones',
      description: 'Behind-the-neck cable sport earphones: Hydrophobic acoustic mesh sweat defense, inline 3-button microphone, NFC pairing, and 6-hour battery.',
      price: 129,
      discount_price: 89,
      stock: 60,
      image_url: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=800&q=80'],
      rating: 4.7,
      num_reviews: 1800,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Bose Sport', Pairing: 'NFC One-Touch & Bluetooth', Resistance: 'Sweat-Resistant Hydrophobic Cloth' }
    },
    {
      name: 'Bose QuietControl 30 Wireless Neckband ANC Earphones',
      slug: 'bose-quietcontrol-30-wireless-neckband-anc-earphones',
      description: 'Ergonomic neckband with breakthrough controllable noise cancellation: Adjust noise reduction level continuously on the go, dual-mic rejection system, 10-hour battery.',
      price: 299,
      discount_price: 199,
      stock: 25,
      image_url: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 950,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Bose', FormFactor: 'Ergonomic Lightweight Neckband', NoiseControl: 'Variable Controllable ANC' }
    },
    {
      name: 'Bose Sleepbuds II Noise-Masking Sleep Earbuds',
      slug: 'bose-sleepbuds-ii-noise-masking-sleep-earbuds',
      description: 'Clinically proven sleep aid technology: Tiny ultra-comfortable ear tips designed for side sleepers, clinically engineered soothing noise-masking sound library, alarm clock.',
      price: 249,
      discount_price: 199,
      stock: 45,
      image_url: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 1420,
      is_featured: true,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Bose Wellness', Purpose: 'Noise-Masking Sleep Earbuds', Profiles: '50+ Curated Sleep Sounds & Binaural Tones' }
    },
    {
      name: 'Bose Ultra Open Earbuds Metallic Sunset Edition',
      slug: 'bose-ultra-open-earbuds-metallic-sunset-edition',
      description: 'Lustrous sunset copper metallic finish: Clip-on ear cuff audio styling, spatial Immersive Audio, up to 7.5 hours battery, and complete situational awareness.',
      price: 299,
      discount_price: 269,
      stock: 35,
      image_url: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 310,
      is_featured: false,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Bose Limited', Color: 'Metallic Sunset Copper', AudioTech: 'Bose OpenAudio' }
    },
    {
      name: 'Bose Ultra Open Earbuds Moonstone Blue Limited Edition',
      slug: 'bose-ultra-open-earbuds-moonstone-blue-limited-edition',
      description: 'Soft celestial matte blue cuff earbuds: OpenAudio directional driver, Bose Immersive Audio, SimpleSync TV pairing, and IPX4 rating.',
      price: 299,
      discount_price: 269,
      stock: 30,
      image_url: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 240,
      is_featured: false,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Bose Limited', Colorway: 'Moonstone Blue Matte', Tech: 'OpenAudio Spatial Sound' }
    },
    {
      name: 'Bose QuietComfort Earbuds II Soapstone White',
      slug: 'bose-quietcomfort-earbuds-ii-soapstone-white',
      description: 'Crisp matte soapstone white finish: CustomTune active noise cancellation, Aware mode with ActiveSense auto-transparency, and 24 hours total playtime.',
      price: 279,
      discount_price: 219,
      stock: 50,
      image_url: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 890,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Bose', Color: 'Soapstone White', Features: 'CustomTune & ActiveSense Transparency' }
    },
    {
      name: 'Bose QuietComfort Earbuds II Eclipse Grey',
      slug: 'bose-quietcomfort-earbuds-ii-eclipse-grey',
      description: 'Sophisticated dark graphite eclipse finish: Tailored noise reduction sound waves, capacitive swipe volume controls, and IPX4 water resistance.',
      price: 279,
      discount_price: 219,
      stock: 45,
      image_url: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 620,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Bose', Color: 'Eclipse Grey Metallic', Technology: 'CustomTune Audio' }
    },
    {
      name: 'Bose Sport Open Earbuds True Wireless',
      slug: 'bose-sport-open-earbuds-true-wireless',
      description: 'Over-ear contoured hook open audio earphones: Positioned to rest gently on the ear ridge without entering the canal, pristine open-ear audio, and IPX4 sweatproof.',
      price: 199,
      discount_price: 149,
      stock: 35,
      image_url: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=800&q=80'],
      rating: 4.7,
      num_reviews: 780,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Bose Sport', Hook: 'Ergonomic Molded Over-Ear Hook', Audio: 'OpenAudio Dipole Transducer' }
    },
    {
      name: 'Bose SoundTrue Ultra In-Ear Audio Headphones',
      slug: 'bose-soundtrue-ultra-in-ear-audio-headphones',
      description: 'Small acoustic seal in-ear wired earphones: Proprietary StayHear Ultra tips that seal deep into the ear canal, sweat-resistant T-joint cable construction.',
      price: 129,
      discount_price: 89,
      stock: 40,
      image_url: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=800&q=80'],
      rating: 4.7,
      num_reviews: 520,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Bose', EarTips: 'StayHear Ultra Acoustic Seal Tips', Connectivity: '3.5mm Wired' }
    },
    {
      name: 'Bose QC Ultra Earbuds Wireless Charging Silicone Case Cover',
      slug: 'bose-qc-ultra-earbuds-wireless-charging-silicone-case-cover',
      description: 'Official Bose wireless charging accessory: Form-fitting soft silicone case cover with built-in Qi wireless charging receiver coils and aluminum carabiner clip.',
      price: 49,
      discount_price: 39,
      stock: 90,
      image_url: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 640,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Bose Official', QiCharging: 'Integrated Qi Wireless Charging Coil', Compatibility: 'QC Ultra Earbuds / QC Earbuds II' }
    },
    {
      name: 'Bose Ultra Open Earbuds Fit Kit S/M/L Stability Bands',
      slug: 'bose-ultra-open-earbuds-fit-kit-s-m-l-stability-bands',
      description: 'Complete replacement fit kit: 3 pairs of soft silicone comfort wrap bands in Small, Medium, and Large to ensure perfect clamping tension for all ear sizes.',
      price: 25,
      discount_price: 19,
      stock: 110,
      image_url: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 320,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Bose Accessory', Contents: '3 Sizes (S, M, L) Silicone Comfort Sleeves' }
    },
    {
      name: 'Bose StayHear Max Replacement Silicone Eartip Kit 3 Pairs',
      slug: 'bose-stayhear-max-replacement-silicone-eartip-kit-3-pairs',
      description: 'Factory authentic umbrella-shaped eartips: Soft silicone design distributing contact evenly across your ear, includes Small, Medium, and Large pairs.',
      price: 20,
      discount_price: 15,
      stock: 140,
      image_url: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 950,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Bose Original Part', Compatibility: 'QuietComfort Earbuds / Sport Earbuds', Sizes: '1x Small, 1x Medium, 1x Large' }
    },
    {
      name: 'Bose Sport Earbuds Qi-Certified Fast Wireless Charging Case',
      slug: 'bose-sport-earbuds-qi-certified-fast-wireless-charging-case',
      description: 'Hard protective charging case for Bose Sport Earbuds: Provides 10 extra hours of battery, magnet lock snap closure, LED status indicators, and USB-C port.',
      price: 69,
      discount_price: 55,
      stock: 50,
      image_url: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 410,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Bose Sport', Capacity: '500 mAh (2 Full Recharges)', Input: 'USB-C Fast Charging' }
    },
    {
      name: 'Bose QC Earbuds II Lanyard and Belt Clip Carabiner Holster',
      slug: 'bose-qc-earbuds-ii-lanyard-and-belt-clip-carabiner-holster',
      description: 'Rugged outdoor protection: Hard polycarbonate armor shell with shockproof TPU bumper, detachable wrist lanyard, and anodized aluminum locking carabiner.',
      price: 29,
      discount_price: 22,
      stock: 85,
      image_url: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=800&q=80'],
      rating: 4.7,
      num_reviews: 290,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Bose Accessory', Attachment: 'Locking Carabiner Clip & Lanyard' }
    },

    // --- 3. BOSE SMART SOUNDBARS, BASS MODULES & HOME THEATER (20 Models) ---
    {
      name: 'Bose Smart Ultra Soundbar with Dolby Atmos & AI Dialogue Mode',
      slug: 'bose-smart-ultra-soundbar-with-dolby-atmos-and-ai-dialogue-mode',
      description: 'The pinnacle of home theater immersion: 9 transducers including upward-firing dipole speakers for overhead Dolby Atmos effects, AI Dialogue Mode that dynamically enhances actor speech clarity, ADAPTiQ room calibration, and Wi-Fi/AirPlay 2.',
      price: 899,
      discount_price: 799,
      stock: 40,
      image_url: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80'],
      rating: 5.0,
      num_reviews: 1250,
      is_featured: true,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Bose', AudioFormats: 'Dolby Atmos / TrueSpace / Dolby Digital', AI: 'AI Dialogue Mode Speech Clarification', Transducers: '9 Custom Transducers (Dual Upward-Firing)', Connectivity: 'HDMI eARC / Wi-Fi / AirPlay 2 / Spotify Connect' }
    },
    {
      name: 'Bose Smart Soundbar 900 with Dolby Atmos',
      slug: 'bose-smart-soundbar-900-with-dolby-atmos',
      description: 'Cinema sound in premium tempered glass and metal: Custom upward-firing dipole speakers, PhaseGuide technology for spatial sound beams, ADAPTiQ audio calibration, and SimpleSync.',
      price: 799,
      discount_price: 699,
      stock: 35,
      image_url: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 1890,
      is_featured: true,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Bose', TopPlate: 'Polished Impact-Resistant Glass', Atmos: 'Upward-Firing Dolby Atmos Speakers', Calibration: 'ADAPTiQ Room Acoustic Tuning' }
    },
    {
      name: 'Bose Smart Soundbar 600 Compact Dolby Atmos Soundbar',
      slug: 'bose-smart-soundbar-600-compact-dolby-atmos-soundbar',
      description: 'Small footprint with overhead Atmos: 5 physical transducers with dual upward firing drivers, TrueSpace processing for non-Atmos signals, and voice control.',
      price: 499,
      discount_price: 449,
      stock: 60,
      image_url: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 1420,
      is_featured: true,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Bose', Dimensions: '27.3 inch Compact Width', UpwardDrivers: '2 Dedicated Up-Firing Drivers', Tech: 'TrueSpace Intelligent Spatial Upscaling' }
    },
    {
      name: 'Bose Smart Soundbar 300 Voice-Controlled TV Speaker',
      slug: 'bose-smart-soundbar-300-voice-controlled-tv-speaker',
      description: 'Spacious sound and clear dialogue for movies and music: 4 full-range drivers, central dome tweeter, QuietPort technology to prevent distortion, and Alexa/Google built-in.',
      price: 399,
      discount_price: 349,
      stock: 50,
      image_url: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 1100,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Bose', Drivers: '4 Full-Range Drivers + 1 Center Dome Tweeter', Voice: 'Bose Voice4Video & Alexa/Google' }
    },
    {
      name: 'Bose TV Speaker Compact Bluetooth Soundbar',
      slug: 'bose-tv-speaker-compact-bluetooth-soundbar',
      description: 'Instant television dialogue clarity: Two angled full-range drivers for wide realistic audio spread, center tweeter for crisp vocals, and dedicated Dialogue Mode button on remote.',
      price: 279,
      discount_price: 229,
      stock: 90,
      image_url: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 3450,
      is_featured: false,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Bose', Setup: 'Single Optical or HDMI-ARC Connection', Height: 'Just over 2 inches (5 cm) High' }
    },
    {
      name: 'Bose Bass Module 700 Wireless Subwoofer',
      slug: 'bose-bass-module-700-wireless-subwoofer',
      description: 'Thunderous, distortion-free low end: QuietPort technology with a generous port flared on both ends to eliminate turbulence, glass-top finish, and wireless pairing up to 30 feet.',
      price: 849,
      discount_price: 749,
      stock: 45,
      image_url: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80'],
      rating: 5.0,
      num_reviews: 1680,
      is_featured: true,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Bose', Finish: 'Premium Tempered Glass Top', Subwoofer: 'High-Excursion 10-inch Driver with QuietPort', Wireless: 'Wireless Range 9m (30ft)' }
    },
    {
      name: 'Bose Bass Module 500 Compact Wireless Subwoofer',
      slug: 'bose-bass-module-500-compact-wireless-subwoofer',
      description: 'Compact 10-inch cube delivering deep room-shaking bass: Connects wirelessly to Bose Smart Soundbars, matte textured finish, and easy single-cord power setup.',
      price: 499,
      discount_price: 449,
      stock: 55,
      image_url: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 1240,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Bose', Size: '10-inch Compact Cube', Compatibility: 'Smart Soundbar 600, 300, 900, Ultra, TV Speaker' }
    },
    {
      name: 'Bose Surround Speakers 700 Wireless Rear Speakers',
      slug: 'bose-surround-speakers-700-wireless-rear-speakers',
      description: 'Bose most premium surround speakers: 360-degree omnidirectional aluminum enclosures that disperse cinematic sound across your entire living room wirelessly.',
      price: 599,
      discount_price: 549,
      stock: 35,
      image_url: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 780,
      is_featured: true,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Bose', Dispersion: '360° Omnidirectional Audio', Material: 'Seamless Anodized Extruded Aluminum', Wireless: 'Dual Wireless Receivers Included' }
    },
    {
      name: 'Bose Surround Speakers Compact Wireless Rear Satellite Pair',
      slug: 'bose-surround-speakers-compact-wireless-rear-satellite-pair',
      description: 'Discreet rear channel audio: Standing less than 4 inches tall, these compact satellite speakers blend into any decor while unlocking full 5.1 surround sound.',
      price: 399,
      discount_price: 349,
      stock: 65,
      image_url: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 1420,
      is_featured: false,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Bose', Height: 'Less than 4 inches (10 cm)', Channels: 'Discrete Left and Right Surround' }
    },
    {
      name: 'Bose Lifestyle 650 5.1 Premium Home Theater System',
      slug: 'bose-lifestyle-650-5-1-premium-home-theater-system',
      description: 'Bose flagship 5.1 home entertainment system: 4 OmniJewel 360-degree aluminum speakers, wide OmniJewel center channel, Acoustimass wireless bass module, and 4K HDMI matrix media console.',
      price: 3999,
      discount_price: 3699,
      stock: 12,
      image_url: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80'],
      rating: 5.0,
      num_reviews: 240,
      is_featured: true,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Bose Flagship', Speakers: '4x OmniJewel + 1x OmniJewel Center + 1x Acoustimass 300 Sub', Console: 'Unify 4K 6-HDMI Media Center' }
    },
    {
      name: 'Bose Lifestyle 600 5.1 Home Cinema Entertainment System',
      slug: 'bose-lifestyle-600-5-1-home-cinema-entertainment-system',
      description: 'Jewel Cube direct/reflecting speaker arrays, Acoustimass wireless bass module, intelligent Unify onscreen guidance, and ADAPTiQ room calibration.',
      price: 2999,
      discount_price: 2799,
      stock: 15,
      image_url: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 190,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Bose Home Theater', Satellite: '4x Jewel Cube Direct/Reflecting Arrays', Sound: '5.1 Channel Surround' }
    },
    {
      name: 'Bose Acoustimass 10 Series V Home Theater Speaker System',
      slug: 'bose-acoustimass-10-series-v-home-theater-speaker-system',
      description: 'High-performance component 5.1 system: 4 Direct/Reflecting Series II cube speakers, horizontal center channel speaker, and powered Acoustimass module with dual drivers.',
      price: 999,
      discount_price: 849,
      stock: 25,
      image_url: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 620,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Bose Component Audio', Module: 'Powered Dual-Driver Acoustimass Bass Module', Cubes: 'Direct/Reflecting Series II' }
    },
    {
      name: 'Bose Acoustimass 5 Series V Stereo Speaker System',
      slug: 'bose-acoustimass-5-series-v-stereo-speaker-system',
      description: '2.1 stereo audiophile system: 2 Direct/Reflecting Series II cube speakers deliver spacious stereo imaging, hideaway Acoustimass bass module.',
      price: 449,
      discount_price: 399,
      stock: 30,
      image_url: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 430,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Bose', System: '2.1 Stereo Channel Array', Design: 'Hideaway Passive Bass Module' }
    },
    {
      name: 'Bose Solo 5 TV Sound System Compact Soundbar',
      slug: 'bose-solo-5-tv-sound-system-compact-soundbar',
      description: 'Single-piece soundbar that brings noticeably better sound to all your favorite TV programs: Dialogue mode to make every word stand out, Bluetooth streaming.',
      price: 199,
      discount_price: 159,
      stock: 80,
      image_url: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80'],
      rating: 4.7,
      num_reviews: 2800,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Bose', Remote: 'Universal Remote Included', Inputs: 'Optical, Coaxial, 3.5mm Aux' }
    },
    {
      name: 'Bose Smart Soundbar 900 Arctic White Edition',
      slug: 'bose-smart-soundbar-900-arctic-white-edition',
      description: 'Pristine Arctic White tempered glass and wrap-around metal grille: Dolby Atmos, Voice4Video, ADAPTiQ room calibration, and Wi-Fi streaming.',
      price: 799,
      discount_price: 699,
      stock: 25,
      image_url: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80'],
      rating: 5.0,
      num_reviews: 580,
      is_featured: false,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Bose', Color: 'Arctic White Tempered Glass', Audio: 'Dolby Atmos Spatial Audio' }
    },
    {
      name: 'Bose Bass Module 700 Arctic White Edition',
      slug: 'bose-bass-module-700-arctic-white-edition',
      description: 'Matches the Arctic White Soundbar 900 / Ultra: Pure white tempered glass top plate, QuietPort distortion cancellation, and deep cinematic bass.',
      price: 849,
      discount_price: 749,
      stock: 30,
      image_url: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80'],
      rating: 5.0,
      num_reviews: 420,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Bose', Color: 'Arctic White with Glass Top', Wireless: 'Zero-Latency Wireless Sync' }
    },
    {
      name: 'Bose Soundbar Wall Bracket Heavy Duty Steel Mount',
      slug: 'bose-soundbar-wall-bracket-heavy-duty-steel-mount',
      description: 'Flush wall-mounting kit: Heavy-duty cold-rolled steel bracket engineered specifically to mount Bose Smart Ultra, 900, 600, 300, and TV Speaker directly under wall-mounted TVs.',
      price: 49,
      discount_price: 39,
      stock: 120,
      image_url: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 890,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Bose Official', Material: 'High-Grade Cold-Rolled Steel', Compatibility: 'Smart Ultra, 900, 600, 300, TV Speaker' }
    },
    {
      name: 'Bose OmniJewel Floor Stands Pair',
      slug: 'bose-omnijewel-floor-stands-pair',
      description: 'Extruded aluminum floor stands with tempered glass bases: Slender wire management channels that hide speaker wires completely for Lifestyle 650 / Surround 700.',
      price: 199,
      discount_price: 169,
      stock: 40,
      image_url: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 310,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Bose Accessory', Height: '38.5 inches (97.8 cm)', Base: 'Tempered Glass Heavy Base' }
    },
    {
      name: 'Bose OmniJewel Ceiling Brackets Pair',
      slug: 'bose-omnijewel-ceiling-brackets-pair',
      description: 'Cast aluminum ceiling brackets for flush ceiling installation of Bose OmniJewel satellite speakers with integrated wiring connector plates.',
      price: 119,
      discount_price: 99,
      stock: 45,
      image_url: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 180,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Bose Accessory', Material: 'High-Quality Cast Aluminum', Application: 'Overhead Ceiling Surround Mounting' }
    },
    {
      name: 'Bose Optical & High-Speed eARC HDMI 2.1 Cable Kit',
      slug: 'bose-optical-and-high-speed-earc-hdmi-2-1-cable-kit',
      description: 'Ultra-high bandwidth 48Gbps 2-meter HDMI 2.1 eARC cable with gold-plated connectors and low-loss optical audio cable for flawless Dolby Atmos audio pass-through.',
      price: 39,
      discount_price: 29,
      stock: 130,
      image_url: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 620,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Bose Original Part', Speed: 'HDMI 2.1 eARC 48 Gbps Bandwidth', Length: '2.0 Meters (6.6 ft)' }
    },

    // --- 4. BOSE PORTABLE & OUTDOOR SPEAKERS & SOUNDLINK (20 Models) ---
    {
      name: 'Bose SoundLink Max Portable High-Power Bluetooth Speaker',
      slug: 'bose-soundlink-max-portable-high-power-bluetooth-speaker',
      description: 'Massive party bass in a rugged portable boombox: Three custom transducers with dual passive radiators, silicone-wrapped steel body with climbing-rope carry handle, IP67 waterproof and dustproof, 20-hour battery life, and reverse phone charging via USB-C.',
      price: 399,
      discount_price: 349,
      stock: 55,
      image_url: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80'],
      rating: 5.0,
      num_reviews: 890,
      is_featured: true,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Bose SoundLink', Waterproof: 'IP67 Waterproof & Dustproof (It Floats)', Battery: '20 Hours Battery + USB-C Power Bank Mode', Handle: 'Removable Soft-Rope Grab Handle' }
    },
    {
      name: 'Bose SoundLink Flex Bluetooth Speaker 2nd Gen',
      slug: 'bose-soundlink-flex-bluetooth-speaker-2nd-gen',
      description: 'PositionIQ technology automatically optimizes audio orientation: Powder-coated steel grille with silicone body, IP67 waterproof rating that actually floats in water, and 12 hours playtime.',
      price: 149,
      discount_price: 129,
      stock: 95,
      image_url: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 3200,
      is_featured: true,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Bose SoundLink', Tech: 'PositionIQ Auto-Orientation EQ', Durability: 'IP67 Waterproof, Drop-Proof & Floats', Battery: '12 Hours Playtime' }
    },
    {
      name: 'Bose SoundLink Revolve+ II 360-Degree Bluetooth Speaker',
      slug: 'bose-soundlink-revolve-plus-ii-360-degree-bluetooth-speaker',
      description: 'True 360-degree room-filling acoustic coverage: Downward-firing acoustic transducer with omnidirectional deflector, flexible fabric grab handle, IP55 water resistance, and 17-hour battery.',
      price: 329,
      discount_price: 279,
      stock: 60,
      image_url: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 2150,
      is_featured: true,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Bose SoundLink', Coverage: '360° Omnidirectional Soundfield', Handle: 'Flexible Fabric Carry Handle', Battery: '17 Hours Playtime' }
    },
    {
      name: 'Bose SoundLink Revolve II 360-Degree Bluetooth Speaker',
      slug: 'bose-soundlink-revolve-ii-360-degree-bluetooth-speaker',
      description: 'Compact seamless aluminum 360 acoustic cylinder: Dual-opposing passive radiators, IP55 water resistance rating, and 13-hour battery.',
      price: 219,
      discount_price: 179,
      stock: 75,
      image_url: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 1890,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Bose SoundLink', Body: 'Seamless Single-Piece Aluminum', Battery: '13 Hours Playtime' }
    },
    {
      name: 'Bose SoundLink Micro Rugged Waterproof Bluetooth Speaker',
      slug: 'bose-soundlink-micro-rugged-waterproof-bluetooth-speaker',
      description: 'Pocket-sized powerhouse with tear-resistant silicone strap: Custom transducer with silicone passive radiators, IP67 waterproof, and built-in speakerphone.',
      price: 119,
      discount_price: 99,
      stock: 120,
      image_url: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 4200,
      is_featured: false,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Bose SoundLink', Strap: 'Tear-Resistant Silicone Mounting Strap', Waterproof: 'IP67 Waterproof & Dustproof', Battery: '6 Hours' }
    },
    {
      name: 'Bose SoundLink Mini II Special Edition Bluetooth Speaker',
      slug: 'bose-soundlink-mini-ii-special-edition-bluetooth-speaker',
      description: 'The audiophile compact classic: Single-piece anodized aluminum casing, dual custom drivers with dual opposing passive radiators, USB-C charging, and 12-hour battery.',
      price: 199,
      discount_price: 169,
      stock: 65,
      image_url: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80'],
      rating: 5.0,
      num_reviews: 5800,
      is_featured: true,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Bose SoundLink', Enclosure: 'Anodized Solid Aluminum Monocoque', Battery: '12 Hours with USB-C' }
    },
    {
      name: 'Bose Smart Speaker 500 with LCD Display & Alexa/Google',
      slug: 'bose-smart-speaker-500-with-lcd-display-and-alexa-google',
      description: 'Wall-to-wall stereo from a single speaker: Two custom drivers point in opposite directions to bounce sound off walls, color LCD screen showing album art, Wi-Fi/AirPlay 2.',
      price: 379,
      discount_price: 329,
      stock: 45,
      image_url: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 1420,
      is_featured: true,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Bose Home Audio', Display: 'Color LCD Screen with Album Artwork', Stereo: 'Dual Opposing Drivers for Wall-to-Wall Sound', WiFi: 'Wi-Fi, Bluetooth & Apple AirPlay 2' }
    },
    {
      name: 'Bose Portable Smart Speaker with Built-In Wi-Fi & Handle',
      slug: 'bose-portable-smart-speaker-with-built-in-wi-fi-and-handle',
      description: 'All-in-one home speaker and portable outdoor Bluetooth speaker: 360 degrees of deep bass, built-in voice control, IPX4 splash resistance, 12-hour battery.',
      price: 399,
      discount_price: 349,
      stock: 50,
      image_url: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 1100,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Bose Smart Audio', DualMode: 'Wi-Fi Home Smart Speaker + Outdoor Bluetooth', Battery: '12 Hours with Soft Carry Handle' }
    },
    {
      name: 'Bose Home Speaker 300 Compact Smart Wi-Fi Audio',
      slug: 'bose-home-speaker-300-compact-smart-wi-fi-audio',
      description: 'Compact space-saving design with 360-degree lifelike sound, 6 preset buttons on top plate for one-touch access to playlists and internet radio stations.',
      price: 259,
      discount_price: 199,
      stock: 40,
      image_url: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80'],
      rating: 4.7,
      num_reviews: 820,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Bose', Presets: '6 Physical Instant-Play Buttons', Streaming: 'AirPlay 2, Spotify, Amazon Music' }
    },
    {
      name: 'Bose Wave Music System IV with CD Player and AM/FM Tuner',
      slug: 'bose-wave-music-system-iv-with-cd-player-and-am-fm-tuner',
      description: 'Iconic waveguide acoustic speaker technology: Slot-loading CD/MP3 drive, high-performance digital AM/FM tuner with RDS, touch-top controls, and dual alarms.',
      price: 499,
      discount_price: 449,
      stock: 30,
      image_url: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 1650,
      is_featured: true,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Bose Wave', Technology: 'Dual Tapered Waveguide Acoustic Chamber', Media: 'Slot-Load CD / AM/FM Radio / Aux' }
    },
    {
      name: 'Bose FreeSpace 51 Environmental In-Ground Garden Speakers',
      slug: 'bose-freespace-51-environmental-in-ground-garden-speakers',
      description: '360-degree outdoor dispersion landscape speakers: In-ground or on-ground mounting in garden beds, withstands snow, rain, salt spray and 150°F temperatures.',
      price: 449,
      discount_price: 399,
      stock: 35,
      image_url: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 410,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Bose Outdoor', WeatherRating: 'Sub-Zero to 150°F Extreme Weather Tested', SoundField: '360° Horizontal Radial Dispersion' }
    },
    {
      name: 'Bose 251 Environmental Outdoor Wall-Mount Speakers',
      slug: 'bose-251-environmental-outdoor-wall-mount-speakers',
      description: 'Articulated Array speaker design with full stereo spread on patios and decks: Two 2.5-inch Twiddler drivers and 5.25-inch woofer in multi-chamber enclosure.',
      price: 398,
      discount_price: 349,
      stock: 45,
      image_url: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 920,
      is_featured: false,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Bose Outdoor', Array: 'Articulated Array (2x Twiddlers + 1x 5.25 Woofer)', Brackets: 'Weatherproof Heavy-Duty Mounting Brackets Included' }
    },
    {
      name: 'Bose 151 SE Elegant All-Weather Outdoor Speakers',
      slug: 'bose-151-se-elegant-all-weather-outdoor-speakers',
      description: 'Compact curved outdoor speakers: Three 2.5-inch environmental drivers per speaker, glass-filled polypropylene cabinet resistant to salt fog and UV rays.',
      price: 278,
      discount_price: 239,
      stock: 50,
      image_url: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 640,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Bose Outdoor', Drivers: '3 Full-Range 2.5-inch Environmental Drivers', Mounting: 'Vertical or Horizontal Mounting Brackets' }
    },
    {
      name: 'Bose SoundLink Flex Chilled Lilac Limited Edition',
      slug: 'bose-soundlink-flex-chilled-lilac-limited-edition',
      description: 'Pastel lilac silicone and powder-coated steel finish: PositionIQ auto-orientation audio, IP67 waterproof (floats in pool), and 12-hour battery.',
      price: 149,
      discount_price: 129,
      stock: 60,
      image_url: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 430,
      is_featured: false,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Bose Limited', Color: 'Chilled Lilac Purple', Waterproof: 'IP67 Submersible & Floating' }
    },
    {
      name: 'Bose SoundLink Max Dusk Blue Portable Speaker',
      slug: 'bose-soundlink-max-dusk-blue-portable-speaker',
      description: 'Dusk blue deep tone with contrast orange accent cords: Powerful boombox stereo acoustics, IP67 rating, 20 hours battery, and power bank phone charging.',
      price: 399,
      discount_price: 349,
      stock: 40,
      image_url: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80'],
      rating: 5.0,
      num_reviews: 320,
      is_featured: false,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Bose SoundLink', Color: 'Dusk Blue & Orange Accents', Battery: '20 Hours' }
    },
    {
      name: 'Bose SoundLink Revolve+ Charging Cradle Dock',
      slug: 'bose-soundlink-revolve-plus-charging-cradle-dock',
      description: 'Convenient home base charging: Keeps your SoundLink Revolve or Revolve+ fully charged while playing music uninterrupted, non-slip rubber base.',
      price: 35,
      discount_price: 29,
      stock: 100,
      image_url: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 790,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Bose Official Accessory', Compatibility: 'SoundLink Revolve & Revolve+ I/II', Power: 'Pin Drop-In Fast Charging' }
    },
    {
      name: 'Bose SoundLink Micro Silicone Tear-Resistant Strap Kit',
      slug: 'bose-soundlink-micro-silicone-tear-resistant-strap-kit',
      description: 'Heavy-duty replacement silicone strap with secure hook snap lock for attaching SoundLink Micro to bike handlebars, backpack straps, or coolers.',
      price: 19,
      discount_price: 15,
      stock: 130,
      image_url: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80'],
      rating: 4.7,
      num_reviews: 340,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Bose Official Part', Material: 'High-Tensile Vulcanized Silicone', Compatibility: 'SoundLink Micro' }
    },
    {
      name: 'Bose Wave Bluetooth Music Adapter Kit',
      slug: 'bose-wave-bluetooth-music-adapter-kit',
      description: 'Connects directly to the Bose link port of your Wave Music System IV or Wave SoundTouch to enable wireless high-definition Bluetooth streaming.',
      price: 99,
      discount_price: 79,
      stock: 45,
      image_url: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80'],
      rating: 4.7,
      num_reviews: 290,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Bose Wave Accessory', Interface: 'Proprietary Bose Link Multi-Pin', Bluetooth: 'Bluetooth 4.2 with aptX' }
    },
    {
      name: 'Bose SoundLink Max Heavy-Duty Carrying Rope Shoulder Strap',
      slug: 'bose-soundlink-max-heavy-duty-carrying-rope-shoulder-strap',
      description: 'Braided climbing-grade nylon rope shoulder strap with anodized aluminum carabiner quick-release swivels for comfortable hands-free transport.',
      price: 45,
      discount_price: 36,
      stock: 80,
      image_url: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 210,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Bose Accessory', Material: 'Climbing Grade Braided Rope & Aluminum Swivels' }
    },
    {
      name: 'Bose SoundTouch Wireless Link Smart Wi-Fi Adapter',
      slug: 'bose-soundtouch-wireless-link-smart-wi-fi-adapter',
      description: 'Transform your existing stereo receiver or powered speakers into a wireless Wi-Fi and Bluetooth streaming system with optical and 3.5mm outputs.',
      price: 149,
      discount_price: 119,
      stock: 40,
      image_url: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 540,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Bose SoundTouch', Outputs: 'Optical Digital, 3.5mm Aux, RCA', Connectivity: 'Wi-Fi & Bluetooth' }
    },

    // --- 5. BOSE PROFESSIONAL LIVE AUDIO, BOSE FRAMES & COMMERCIAL (28 Models) ---
    {
      name: 'Bose S1 Pro+ All-In-One Wireless PA System with Battery',
      slug: 'bose-s1-pro-plus-all-in-one-wireless-pa-system-with-battery',
      description: 'The ultimate portable PA for musicians and DJs: 3-channel mixer with OLED displays, integrated wireless RF receivers for wireless mic/instrument transmitters, ToneMatch presets, multi-position auto EQ, and 11 hours of battery life.',
      price: 699,
      discount_price: 649,
      stock: 40,
      image_url: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80'],
      rating: 5.0,
      num_reviews: 1450,
      is_featured: true,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Bose Professional', Channels: '3-Channel Mixer with Dual XLR/Quarter-Inch Combos', Wireless: 'Built-In Wireless RF Receivers for Transmitters', Battery: 'Up to 11 Hours Rechargeable Li-Ion', Weight: '6.5 kg (14.4 lbs)' }
    },
    {
      name: 'Bose L1 Pro8 Portable Line Array PA System',
      slug: 'bose-l1-pro8-portable-line-array-pa-system',
      description: 'C-shaped line array with 8 articulated 2-inch neodymium drivers: 180-degree horizontal coverage, integrated 7x13-inch high-excursion RaceTrack woofer, and built-in 3-channel mixer with ToneMatch presets.',
      price: 1299,
      discount_price: 1199,
      stock: 20,
      image_url: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80'],
      rating: 5.0,
      num_reviews: 620,
      is_featured: true,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Bose Professional', Coverage: '180° Horizontal x 40° Vertical C-Shape', Subwoofer: 'Integrated 7x13 RaceTrack Sub', MaxSPL: '118 dB Peak' }
    },
    {
      name: 'Bose L1 Pro16 High-Output Line Array System',
      slug: 'bose-l1-pro16-high-output-line-array-system',
      description: 'J-shaped line array with 16 articulated neodymium drivers: Balanced blend of power and portability with 10x18-inch neodymium RaceTrack subwoofer and 124 dB peak output.',
      price: 1899,
      discount_price: 1749,
      stock: 15,
      image_url: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80'],
      rating: 5.0,
      num_reviews: 380,
      is_featured: true,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Bose Professional', Array: 'J-Shape 16 Articulated Drivers', Sub: '10x18 High-Excursion RaceTrack Sub', Output: '124 dB SPL Peak' }
    },
    {
      name: 'Bose L1 Pro32 Flagship Line Array with Sub2 Powered Bass Module',
      slug: 'bose-l1-pro32-flagship-line-array-with-sub2-powered-bass-module',
      description: 'Peak portable line array performance: 32 articulated 2-inch drivers in straight line array with 180-degree coverage, paired with Sub2 1000W 10x18 RaceTrack powered bass module via single SubMatch cable.',
      price: 3098,
      discount_price: 2899,
      stock: 10,
      image_url: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80'],
      rating: 5.0,
      num_reviews: 210,
      is_featured: true,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Bose Professional', Drivers: '32 Articulated Neodymium Transducers', Subwoofer: 'Sub2 1000W Powered Bass Module', Connection: 'Proprietary SubMatch Cable' }
    },
    {
      name: 'Bose Sub1 Powered Bass Module 480W',
      slug: 'bose-sub1-powered-bass-module-480w',
      description: 'Slim 7x13-inch high-excursion RaceTrack driver delivering low end down to 40 Hz: Compact footprint, Cardioid Mode setting for directional bass steering.',
      price: 899,
      discount_price: 799,
      stock: 25,
      image_url: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 310,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Bose Professional', Power: '480W Class-D Amplification', Driver: '7x13 inch RaceTrack Transducer', LowEnd: 'Down to 40 Hz' }
    },
    {
      name: 'Bose Sub2 Powered Bass Module 1000W',
      slug: 'bose-sub2-powered-bass-module-1000w',
      description: 'Chest-thumping 1000W powerhouse: 10x18-inch RaceTrack driver reaching down to 37 Hz, pole mount threaded M20 insert, and SubMatch power linking.',
      price: 1199,
      discount_price: 1099,
      stock: 18,
      image_url: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80'],
      rating: 5.0,
      num_reviews: 260,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Bose Professional', Power: '1000W Class-D Amp', Driver: '10x18 inch High-Excursion Neodymium RaceTrack', Bass: 'Down to 37 Hz' }
    },
    {
      name: 'Bose T4S ToneMatch 4-Channel Digital Audio Mixer',
      slug: 'bose-t4s-tonematch-4-channel-digital-audio-mixer',
      description: 'Studio-quality audio processing for live performers: 4 XLR/TRS combo mic/line preamps with phantom power, Bose ToneMatch presets, studio effects processor, and LED illuminated controls.',
      price: 699,
      discount_price: 629,
      stock: 30,
      image_url: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 420,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Bose Professional', Channels: '4 Mic/Line Channels + 2 Aux Sends', Effects: 'Compressor, Limiter, De-Esser, Noise Gate, Chorus, Flanger, Phaser, Delay, Reverb' }
    },
    {
      name: 'Bose T8S ToneMatch 8-Channel Pro Audio Mixer',
      slug: 'bose-t8s-tonematch-8-channel-pro-audio-mixer',
      description: '8-channel digital mixer designed for full bands: High-quality audio preamps, balanced stereo XLR outputs, master EQ, USB interface for recording, and magnetic protective cover.',
      price: 999,
      discount_price: 899,
      stock: 20,
      image_url: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80'],
      rating: 5.0,
      num_reviews: 290,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Bose Professional', Channels: '8 Combo XLR/TRS Audio Preamps', Outputs: 'Stereo Balanced XLR & 1/4-inch TRS Outs' }
    },
    {
      name: 'Bose F1 Model 812 Flexible Array Loudspeaker 1000W',
      slug: 'bose-f1-model-812-flexible-array-loudspeaker-1000w',
      description: 'Adjustable vertical coverage pattern: Push or pull the array to create "Straight", "C", "J", or "Reverse J" dispersion patterns for any auditorium or venue.',
      price: 1099,
      discount_price: 999,
      stock: 16,
      image_url: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80'],
      rating: 5.0,
      num_reviews: 340,
      is_featured: true,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Bose Professional', Power: '1000W Bi-Amplified', Array: 'Flexible Array 8 Mid/High Drivers + 12-inch Woofer', MaxSPL: '132 dB Peak' }
    },
    {
      name: 'Bose F1 Powered Subwoofer 1000W',
      slug: 'bose-f1-powered-subwoofer-1000w',
      description: 'Compact 1000W high-output subwoofer: Dual 10-inch high-excursion woofers with built-in speaker extension stand for the F1 Model 812 loudspeaker.',
      price: 1099,
      discount_price: 999,
      stock: 14,
      image_url: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 280,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Bose Professional', Drivers: '2x 10-inch High-Excursion Woofers', Integration: 'Integrated Extension Stand for F1 812' }
    },
    {
      name: 'Bose DesignMax DM5SE Surface-Mount Commercial Loudspeaker Pair',
      slug: 'bose-designmax-dm5se-surface-mount-commercial-loudspeaker-pair',
      description: 'Commercial background/foreground audio: 5.25-inch woofer and 1-inch coaxially mounted tweeter delivering rich sound, IP55 outdoor rated with QuickHold U-brackets.',
      price: 549,
      discount_price: 499,
      stock: 35,
      image_url: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 210,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Bose Commercial', Driver: 'Coaxial 5.25-inch Woofer & 1-inch Tweeter', Taps: '70V/100V Transformer & 8-Ohm Direct' }
    },
    {
      name: 'Bose FreeSpace DS 40F In-Ceiling Architectural Loudspeaker',
      slug: 'bose-freespace-ds-40f-in-ceiling-architectural-loudspeaker',
      description: 'Flush-mount architectural ceiling speaker: 4.5-inch full-range driver delivering clear speech and background music in retail stores, restaurants, and hotels.',
      price: 249,
      discount_price: 219,
      stock: 60,
      image_url: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 350,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Bose Commercial', Coverage: '125° Conical Dispersion', Transformer: 'Integrated Multi-Tap 70V/100V Transformer' }
    },
    {
      name: 'Bose FreeSpace IZA 250-LZ Integrated Commercial Zone Amplifier',
      slug: 'bose-freespace-iza-250-lz-integrated-commercial-zone-amplifier',
      description: 'Compact commercial power amplifier: 2 x 50W @ 4 Ohms, Opti-voice paging for smooth voice announcements, Dynamic EQ, and front-panel master volume.',
      price: 499,
      discount_price: 449,
      stock: 25,
      image_url: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 180,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Bose Commercial', Output: '2x 50W @ 4 Ohms / 2x 25W @ 8 Ohms', Features: 'Opti-Voice Paging & Dynamic EQ' }
    },
    {
      name: 'Bose PowerShare PS604D 600W 4-Channel Dante Amplifier',
      slug: 'bose-powershare-ps604d-600w-4-channel-dante-amplifier',
      description: 'Patented PowerShare technology allows total 600W power to be shared unequally across all 4 channels, integrated Dante digital audio networking onboard.',
      price: 1799,
      discount_price: 1649,
      stock: 12,
      image_url: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80'],
      rating: 5.0,
      num_reviews: 95,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Bose Professional', Power: '600W Total Asymmetric Power Sharing', Network: 'Integrated Dante Digital Audio Networking' }
    },
    {
      name: 'Bose Frames Tenor Polarized Audio Sunglasses',
      slug: 'bose-frames-tenor-polarized-audio-sunglasses',
      description: 'Rectangular classic sunglasses with soundtrack: Open Ear Audio technology built into temples, polarized shatter-resistant nylon lenses, dual beamforming microphones, and 5.5 hours battery.',
      price: 249,
      discount_price: 199,
      stock: 65,
      image_url: 'https://images.unsplash.com/photo-1511499767150-a48a237f0083?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1511499767150-a48a237f0083?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 1450,
      is_featured: true,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Bose Frames', Lenses: 'Polarized Mirrored Lenses (99% UVA/UVB Block)', Audio: 'Bose Open Ear Audio In-Temple Micro-Acoustics', Battery: '5.5 Hours Continuous Play' }
    },
    {
      name: 'Bose Frames Soprano Cat-Eye Polarized Audio Sunglasses',
      slug: 'bose-frames-soprano-cat-eye-polarized-audio-sunglasses',
      description: 'Glamorous cat-eye styling in high-gloss black: Exclusive Bose acoustic chambers hidden in the temples beam sound to your ears while leaving you aware of your surroundings.',
      price: 249,
      discount_price: 199,
      stock: 50,
      image_url: 'https://images.unsplash.com/photo-1511499767150-a48a237f0083?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1511499767150-a48a237f0083?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 980,
      is_featured: false,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Bose Frames', FrameStyle: 'Cat-Eye Gloss Acetate Frame', Lenses: 'Polarized Rose Gradient (99% UV Block)' }
    },
    {
      name: 'Bose Frames Tempo Sport Audio Sunglasses with Mirrored Lenses',
      slug: 'bose-frames-tempo-sport-audio-sunglasses-with-mirrored-lenses',
      description: 'High-performance sport audio eyewear: TR-90 nylon frame resistant to extreme elements, 22mm custom acoustic drivers for loud clear sound while cycling, IPX4 sweat resistant, 8-hour battery.',
      price: 249,
      discount_price: 199,
      stock: 55,
      image_url: 'https://images.unsplash.com/photo-1511499767150-a48a237f0083?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1511499767150-a48a237f0083?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 1250,
      is_featured: true,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Bose Frames Sport', Drivers: 'High-Volume 22mm Acoustic Drivers', Frame: 'TR-90 Sport Nylon with Silicone Nose Pads', Battery: '8 Hours Battery Life' }
    },
    {
      name: 'Bose Frames Rondo Round Audio Sunglasses',
      slug: 'bose-frames-rondo-round-audio-sunglasses',
      description: 'Distinctive retro rounded silhouette with tinted lenses and miniature Bose speakers directed at your ears, single button control, and gold steel hinges.',
      price: 199,
      discount_price: 149,
      stock: 40,
      image_url: 'https://images.unsplash.com/photo-1511499767150-a48a237f0083?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1511499767150-a48a237f0083?auto=format&fit=crop&w=800&q=80'],
      rating: 4.7,
      num_reviews: 870,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Bose Frames', Shape: 'Retro Rounded Wire/Nylon Blend', Battery: '3.5 Hours' }
    },
    {
      name: 'Bose Frames Alto Classic Square Audio Sunglasses',
      slug: 'bose-frames-alto-classic-square-audio-sunglasses',
      description: 'The original audio sunglasses that started it all: Classic angular square frame, enriched open acoustic sound, built-in microphone for calls and voice assistant.',
      price: 199,
      discount_price: 139,
      stock: 50,
      image_url: 'https://images.unsplash.com/photo-1511499767150-a48a237f0083?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1511499767150-a48a237f0083?auto=format&fit=crop&w=800&q=80'],
      rating: 4.7,
      num_reviews: 1680,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Bose Frames', Style: 'Classic Wayfarer Angular Square', Hinges: 'Gold-Plated Stainless Steel' }
    },
    {
      name: 'Bose Frames Mirrored Rose Gold Replacement Lens Kit',
      slug: 'bose-frames-mirrored-rose-gold-replacement-lens-kit',
      description: 'Interchangeable polarized rose gold mirrored lenses for Bose Frames Soprano / Tenor, blocks up to 99% of UVA/UVB rays and scratch resistant.',
      price: 39,
      discount_price: 32,
      stock: 80,
      image_url: 'https://images.unsplash.com/photo-1511499767150-a48a237f0083?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1511499767150-a48a237f0083?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 310,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Bose Frames Accessory', Tint: 'Mirrored Rose Gold Polarized (VLT 15%)' }
    },
    {
      name: 'Bose Frames Polarized Road Orange Trail Lens Kit',
      slug: 'bose-frames-polarized-road-orange-trail-lens-kit',
      description: 'High-contrast sport replacement lenses engineered for Bose Frames Tempo: Enhances terrain shadows and road details during trail running and cycling.',
      price: 39,
      discount_price: 32,
      stock: 75,
      image_url: 'https://images.unsplash.com/photo-1511499767150-a48a237f0083?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1511499767150-a48a237f0083?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 240,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Bose Frames Accessory', Tint: 'Road Orange High-Contrast (VLT 20%)', Compatibility: 'Frames Tempo' }
    },
    {
      name: 'Bose S1 Pro+ Wireless 1/4-inch Instrument Transmitter',
      slug: 'bose-s1-pro-plus-wireless-1-4-inch-instrument-transmitter',
      description: 'Plugs directly into guitar, keyboard, or instrument output: Pairs wirelessly with S1 Pro+ channel at the press of a button, charges inside the S1 Pro+ dedicated dock.',
      price: 149,
      discount_price: 135,
      stock: 60,
      image_url: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 450,
      is_featured: false,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Bose Professional', Frequency: '2.4 GHz Ultra-Low Latency RF Wireless', Connector: '1/4-inch (6.35 mm) TS/TRS Jack', Battery: '4 Hours Playtime' }
    },
    {
      name: 'Bose S1 Pro+ Wireless XLR Microphone Transmitter',
      slug: 'bose-s1-pro-plus-wireless-xlr-microphone-transmitter',
      description: 'Turns any dynamic XLR microphone wireless: Clips directly to mic base, 2.4 GHz digital RF connection, internal lithium battery charges inside S1 Pro+ speaker chassis.',
      price: 149,
      discount_price: 135,
      stock: 55,
      image_url: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 380,
      is_featured: false,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Bose Professional', Connector: 'Standard 3-Pin Female XLR', Frequency: '2.4 GHz Digital Wireless', Battery: 'Up to 4 Hours' }
    },
    {
      name: 'Bose S1 Pro+ Lithium-Ion Rechargeable Battery Pack',
      slug: 'bose-s1-pro-plus-lithium-ion-rechargeable-battery-pack',
      description: 'Official backup lithium-ion battery for Bose S1 Pro / S1 Pro+: Provides up to 11 hours of performance, quick-charge mode via S1 Pro+ system.',
      price: 129,
      discount_price: 109,
      stock: 70,
      image_url: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 520,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Bose Pro Part', Chemistry: 'Lithium-Ion 14.8V High Capacity', Playtime: 'Up to 11 Hours' }
    },
    {
      name: 'Bose S1 Pro+ Backpack Padded Heavy-Duty Gig Bag',
      slug: 'bose-s1-pro-plus-backpack-padded-heavy-duty-gig-bag',
      description: 'Padded backpack custom-molded to carry the Bose S1 Pro+ system: Ergonomic breathable shoulder straps, top carry handle, and large zippered accessory storage pocket.',
      price: 129,
      discount_price: 109,
      stock: 50,
      image_url: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 460,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Bose Professional Bag', Padding: 'Thick High-Density EPE Foam', Pockets: 'Cable, Mic and Transmitter Pockets' }
    },
    {
      name: 'Bose L1 Pro System Heavy-Duty Padded Roller Bag',
      slug: 'bose-l1-pro-system-heavy-duty-padded-roller-bag',
      description: 'Heavy-duty transport case with smooth-rolling inline skate wheels, telescoping pull handle, and reinforced corner bumpers for L1 Pro line array bases.',
      price: 249,
      discount_price: 219,
      stock: 25,
      image_url: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 190,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Bose Pro Transport', Wheels: 'Heavy-Duty Inline Skate Ball-Bearing Wheels', Handle: 'Retractable Aluminum Telescoping Handle' }
    },
    {
      name: 'Bose ToneMatch Power Supply Unit T4S/T8S',
      slug: 'bose-tonematch-power-supply-unit-t4s-t8s',
      description: 'Dedicated AC power adapter engineered for Bose ToneMatch T4S and T8S digital audio mixers when not connected to an L1 Pro system with ToneMatch cable.',
      price: 49,
      discount_price: 39,
      stock: 65,
      image_url: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 280,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Bose Official', Voltage: '100-240V Universal Input', Compatibility: 'ToneMatch T4S & T8S Mixers' }
    },
    {
      name: 'Bose SS-10 Heavy Duty Speaker Tripod Stand',
      slug: 'bose-ss-10-heavy-duty-speaker-tripod-stand',
      description: 'Telescoping steel PA tripod stand: Supports up to 70 lbs, safety locking pin, standard 35mm top pole mount fitting Bose S1 Pro+, F1 812, and 802 IV.',
      price: 119,
      discount_price: 99,
      stock: 45,
      image_url: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 320,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Bose Pro', HeightRange: '44 to 77 inches (1.1m to 1.95m)', LoadCapacity: '70 lbs (31.8 kg)' }
    }
  ];
};
