// backend/utils/nikeProductsData.js
// 112 Unique, Non-Repeating Official Nike Products (Alphafly, Pegasus 41, Air Jordan, Air Force 1, Dunk Low, Air Max Dn, Mercurial, Tech Fleece & Accessories)

export const getNikeProducts = (categoryId) => {
  return [
    // --- 1. NIKE RUNNING & RACING INNOVATION (25 Models) ---
    {
      name: 'Nike Alphafly 3 Marathon Road Racing Shoes',
      slug: 'nike-alphafly-3-marathon-road-racing-shoes',
      description: 'World marathon record-breaking super shoe: Continuous full-length ZoomX foam bottom, dual forefoot Air Zoom pods, full-length Flyplate carbon-fiber plate, and ultra-breathable Atomknit 3.0 upper.',
      price: 285,
      discount_price: 285,
      stock: 30,
      image_url: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80'],
      rating: 5.0,
      num_reviews: 480,
      is_featured: true,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Nike', Foam: 'Full-Length ZoomX Foam', AirUnits: 'Dual Forefoot Air Zoom Pods', Carbon: 'Flyplate Carbon Fiber Plate', Upper: 'Atomknit 3.0', Weight: '218g' }
    },
    {
      name: 'Nike Vaporfly 3 Road Racing Shoes',
      slug: 'nike-vaporfly-3-road-racing-shoes',
      description: 'The all-distance racing benchmark: Reduced weight Flyplate carbon plate, optimized ZoomX midsole convex geometry, lightweight Flyknit upper, thin-web waffle rubber outsole.',
      price: 260,
      discount_price: 239,
      stock: 35,
      image_url: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80'],
      rating: 5.0,
      num_reviews: 620,
      is_featured: true,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Nike', Carbon: 'Full-Length Carbon Flyplate', Cushioning: 'ZoomX Foam', Distance: '10K to Marathon' }
    },
    {
      name: 'Nike Pegasus 41 Road Running Shoes',
      slug: 'nike-pegasus-41-road-running-shoes',
      description: 'The workhorse with wings upgraded: All-new ReactX foam midsole providing 13% more energy return, dual forefoot and heel Air Zoom units, upgraded engineered mesh upper.',
      price: 140,
      discount_price: 119,
      stock: 90,
      image_url: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 1450,
      is_featured: true,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Nike', Midsole: 'ReactX Foam (+13% Energy Return)', AirUnits: 'Dual Forefoot & Heel Air Zoom Units', Weight: '297g' }
    },
    {
      name: 'Nike Pegasus Plus Lightweight Running Shoes',
      slug: 'nike-pegasus-plus-lightweight-running-shoes',
      description: 'Full-length ZoomX foam meets classic Pegasus DNA: Flyknit upper with midfoot racing stripe, high-response everyday tempo trainer.',
      price: 180,
      discount_price: 159,
      stock: 45,
      image_url: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 310,
      is_featured: false,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Nike', Foam: 'Full-Length ZoomX Superfoam', Upper: 'Flyknit' }
    },
    {
      name: 'Nike Invincible 3 Maximum Cushioning Running Shoes',
      slug: 'nike-invincible-3-maximum-cushioning-running-shoes',
      description: 'Supreme maximum cushioning to protect your legs: Monster stack of ZoomX foam, wider base for stable strides, Flyknit upper, high-density heel clip.',
      price: 190,
      discount_price: 159,
      stock: 50,
      image_url: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 820,
      is_featured: true,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Nike', Cushioning: 'Max-Stack ZoomX Foam', Support: 'High Stability Wide Base Platform' }
    },
    {
      name: 'Nike InfinityRN 4 Supportive Road Running Shoes',
      slug: 'nike-infinityrn-4-supportive-running-shoes',
      description: 'Engineered for smooth, injury-free runs: ReactX foam reducing carbon footprint by 43%, rocker-shaped sole, water-resistant toe membrane, Flyknit upper.',
      price: 160,
      discount_price: 135,
      stock: 60,
      image_url: 'https://images.unsplash.com/photo-1587563871167-1ee9c731aefb?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1587563871167-1ee9c731aefb?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 640,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Nike', Foam: 'ReactX Foam', Shape: 'Curved Rocker Geometry' }
    },
    {
      name: 'Nike Vomero 17 Plush Distance Running Shoes',
      slug: 'nike-vomero-17-plush-running-shoes',
      description: 'Dual-foam indulgence: Soft ZoomX foam layered directly on top of durable Cushlon 3.0 foam, padded tongue and collar, engineered mesh upper.',
      price: 160,
      discount_price: 139,
      stock: 40,
      image_url: 'https://images.unsplash.com/photo-1587563871167-1ee9c731aefb?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1587563871167-1ee9c731aefb?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 410,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Nike', Midsole: 'ZoomX + Cushlon 3.0 Dual Stack', Feel: 'Plush Luxury Comfort' }
    },
    {
      name: 'Nike Streakfly 5K/10K Lightweight Racing Shoes',
      slug: 'nike-streakfly-5k-10k-racing-shoes',
      description: 'Nike’s lightest racing shoe: Full-length ZoomX foam with midfoot Pebax shank plate for snappy agility in 5K and 10K road competitions.',
      price: 170,
      discount_price: 139,
      stock: 30,
      image_url: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 290,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Nike', Weight: '172g Ultra-Featherweight', Shank: 'Pebax Midfoot Plate', Distance: 'Short Road Distances' }
    },
    {
      name: 'Nike Structure 25 Stability Daily Running Shoes',
      slug: 'nike-structure-25-stability-running-shoes',
      description: 'Reliable pronation guidance: Cushlon 3.0 foam with forefoot Zoom Air unit, midfoot support system, accommodating wide toe box.',
      price: 140,
      discount_price: 119,
      stock: 45,
      image_url: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80'],
      rating: 4.7,
      num_reviews: 360,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Nike', Pronation: 'Stability & Overpronation Control', Air: 'Forefoot Zoom Air Unit' }
    },
    {
      name: 'Nike Pegasus Trail 5 All-Terrain Trail Shoes',
      slug: 'nike-pegasus-trail-5-all-terrain-shoes',
      description: 'Hybrid road-to-trail shoe: ReactX foam midsole, All-Terrain compound (ATC) rubber outsole, engineered mesh upper with toe rand.',
      price: 150,
      discount_price: 129,
      stock: 50,
      image_url: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 510,
      is_featured: false,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Nike', Midsole: 'ReactX Foam', Outsole: 'Nike All-Terrain Compound (ATC) Rubber' }
    },
    {
      name: 'Nike Pegasus Trail 5 GORE-TEX Waterproof Shoes',
      slug: 'nike-pegasus-trail-5-gore-tex-shoes',
      description: 'Winterized wet-weather warrior: GORE-TEX waterproof upper, ankle gaiter collar to keep dirt out, storm-tread ATC outsole.',
      price: 170,
      discount_price: 149,
      stock: 35,
      image_url: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 380,
      is_featured: true,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Nike', Waterproofing: 'GORE-TEX Invisible Fit', Collar: 'High Ankle Gaiter' }
    },
    {
      name: 'Nike Ultrafly Trail Carbon Racing Shoes',
      slug: 'nike-ultrafly-trail-carbon-racing-shoes',
      description: 'Nike’s premier trail racing shoe: ZoomX foam encased in fabric wrap, carbon-fiber Flyplate, and Vibram Megagrip Litebase lugged outsole.',
      price: 260,
      discount_price: 239,
      stock: 20,
      image_url: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 190,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Nike', Outsole: 'Vibram Megagrip Litebase with Traction Lugs', Carbon: 'Carbon Flyplate', Foam: 'ZoomX' }
    },
    {
      name: 'Nike Zegama 2 Trail Running Shoes (Vibram Megagrip)',
      slug: 'nike-zegama-2-trail-running-shoes',
      description: 'ZoomX foam cushioned ultra-trail shoe equipped with Vibram Megagrip outsole with Traction Lug design, ankle gaiter, rock plate.',
      price: 180,
      discount_price: 154,
      stock: 30,
      image_url: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 240,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Nike', Sole: 'Vibram Megagrip Traction Lug', Cushioning: 'ZoomX Foam' }
    },
    {
      name: 'Nike Winflo 11 Daily Training Shoes',
      slug: 'nike-winflo-11-daily-training-shoes',
      description: 'Full-length Nike Air unit paired with Cushlon 3.0 foam: spacious forefoot and midfoot, single-layer engineered mesh upper.',
      price: 105,
      discount_price: 89,
      stock: 65,
      image_url: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80'],
      rating: 4.7,
      num_reviews: 580,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Nike', Cushioning: 'Full-Length Nike Air Unit + Cushlon 3.0' }
    },
    {
      name: 'Nike Downshifter 13 Lightweight Running Shoes',
      slug: 'nike-downshifter-13-running-shoes',
      description: 'Accessible road runner with recycled materials: Updated internal fit band, soft foam midsole, durable rubber outsole.',
      price: 75,
      discount_price: 59,
      stock: 80,
      image_url: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80'],
      rating: 4.6,
      num_reviews: 920,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Nike', Upper: 'Breathable Mesh', Sustainability: 'Nike Grind Recycled Rubber' }
    },
    {
      name: 'Nike Metcon 9 Cross Training & Lifting Shoes',
      slug: 'nike-metcon-9-cross-training-shoes',
      description: 'The gold standard for gym cross-training: Enlarged Hyperlift plate in the heel for squat stability, extended rubber rope wrap, lace lock clip, dual-density foam.',
      price: 150,
      discount_price: 129,
      stock: 60,
      image_url: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 1350,
      is_featured: true,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Nike', HeelPlate: 'Enlarged Hyperlift Plate', RopeGrip: 'Extended Lateral Rubber Rope Wrap', Clip: 'Lace Lock Tab' }
    },
    {
      name: 'Nike Free Metcon 5 Gym & Workout Shoes',
      slug: 'nike-free-metcon-5-gym-shoes',
      description: 'Combines Nike Free forefoot flexibility with Metcon heel stability: 7/8-length inner sleeve, wide heel base for heavy lifting.',
      price: 120,
      discount_price: 99,
      stock: 70,
      image_url: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 1890,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Nike', Flexibility: 'Nike Free Forefoot Grooves', Heel: 'Broad Flat Lifting Platform' }
    },
    {
      name: 'Nike Romaleos 4 Professional Weightlifting Shoes',
      slug: 'nike-romaleos-4-weightlifting-shoes',
      description: 'Olympic weightlifting dominance: 20mm heel elevation, rigid TPU midsole, wide dual midfoot lockdown straps, flat rubber traction base.',
      price: 200,
      discount_price: 179,
      stock: 25,
      image_url: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80'],
      rating: 5.0,
      num_reviews: 310,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Nike', HeelDrop: '20 mm Olympic Lifting Drop', Straps: 'Dual Adjustable Midfoot Straps' }
    },
    {
      name: 'Nike Air Zoom Maxfly Track & Field Sprint Spikes',
      slug: 'nike-air-zoom-maxfly-sprint-spikes',
      description: 'World championship sprint spike: Dual Air Zoom forefoot unit, full-length carbon Flyplate, 7 removable spike pins for 100m-400m hurdles and sprints.',
      price: 190,
      discount_price: 170,
      stock: 20,
      image_url: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 160,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Nike', Events: '100m to 400m Sprints & Hurdles', Carbon: 'Full-Length Carbon Plate', Pins: '7 Removable Stainless Steel Spikes' }
    },
    {
      name: 'Nike Dragonfly Track Distance Racing Spikes',
      slug: 'nike-dragonfly-track-distance-spikes',
      description: 'Long-distance track supremacy: Full-length ZoomX foam, curved responsive plate, ultra-breathable engineered mesh upper for 1500m to 10,000m.',
      price: 160,
      discount_price: 144,
      stock: 22,
      image_url: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80'],
      rating: 5.0,
      num_reviews: 210,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Nike', Events: '1,500m to 10,000m Track', Foam: 'ZoomX Cushioning' }
    },
    {
      name: 'Nike Motiva Walking & Light Jogging Shoes',
      slug: 'nike-motiva-walking-shoes',
      description: 'Exaggerated rocker sole with comfort grooves designed specifically for comfortable walking and run-walk intervals: ultra-soft foam.',
      price: 110,
      discount_price: 89,
      stock: 55,
      image_url: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 740,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Nike', Geometry: 'ComfortGroove Rocker Sole', Activity: 'Walking & Run-Walk Fitness' }
    },
    {
      name: 'Nike Juniper Trail 3 Outdoor Running Shoes',
      slug: 'nike-juniper-trail-3-outdoor-shoes',
      description: 'Rugged trail shoe with Flywire cable midfoot lockdown, rubber lugs for uphill and downhill traction, reinforced toe bumper.',
      price: 90,
      discount_price: 74,
      stock: 60,
      image_url: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80'],
      rating: 4.7,
      num_reviews: 420,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Nike', Lockdown: 'Flywire Cables', Traction: 'Tapered Rubber Trail Lugs' }
    },
    {
      name: 'Nike Rival Fly 3 Fast Road Racers',
      slug: 'nike-rival-fly-3-fast-road-racers',
      description: 'Responsive forefoot Air Zoom unit with soft foam, diagonal flex grooves for natural toe-off, durable rubber crash rail.',
      price: 95,
      discount_price: 79,
      stock: 45,
      image_url: 'https://images.unsplash.com/photo-1587563871167-1ee9c731aefb?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1587563871167-1ee9c731aefb?auto=format&fit=crop&w=800&q=80'],
      rating: 4.7,
      num_reviews: 310,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Nike', Air: 'Forefoot Air Zoom Unit', Upper: 'Lightweight Mesh' }
    },
    {
      name: 'Nike Journey Run Road Running Shoes',
      slug: 'nike-journey-run-road-running-shoes',
      description: 'Extra high stack of soft ComfiRide foam, engineered breathable mesh upper, rubber outsole for reliable grip.',
      price: 90,
      discount_price: 74,
      stock: 50,
      image_url: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80'],
      rating: 4.6,
      num_reviews: 290,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Nike', Foam: 'High-Stack ComfiRide Foam' }
    },
    {
      name: 'Nike React Infinity 3 Flyknit Running Shoes',
      slug: 'nike-react-infinity-3-flyknit-shoes',
      description: 'Flyknit breathable upper, wide rocker React foam midsole, supportive heel counter for long marathon training blocks.',
      price: 160,
      discount_price: 119,
      stock: 40,
      image_url: 'https://images.unsplash.com/photo-1587563871167-1ee9c731aefb?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1587563871167-1ee9c731aefb?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 640,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Nike', Upper: 'Flyknit', Foam: 'Nike React' }
    },

    // --- 2. AIR JORDAN & BASKETBALL FOOTWEAR (25 Models) ---
    {
      name: 'Nike Air Jordan 1 Retro High OG (Chicago / Lost & Found)',
      slug: 'nike-air-jordan-1-retro-high-og-chicago-lost-and-found',
      description: 'The sneaker that started it all: Premium cracked leather collar, vintage muslin tongue, encapsulated Air-Sole heel unit, retro 1985 Nike Air box packaging.',
      price: 180,
      discount_price: 180,
      stock: 35,
      image_url: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80'],
      rating: 5.0,
      num_reviews: 5800,
      is_featured: true,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Nike / Jordan', Colorway: 'Varsity Red / Black / Muslin / White', Leather: 'Vintage Aged Cracked Leather', Air: 'Encapsulated Air-Sole Unit' }
    },
    {
      name: 'Nike Air Jordan 4 Retro (Military Blue 2024)',
      slug: 'nike-air-jordan-4-retro-military-blue-2024',
      description: 'Original 1989 OG specification: Off-white leather upper with Military Blue TPU wings, molded mesh quarter panels, visible Air heel window, Nike Air heel badge.',
      price: 215,
      discount_price: 215,
      stock: 30,
      image_url: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80'],
      rating: 5.0,
      num_reviews: 3200,
      is_featured: true,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Nike / Jordan', Heritage: '1989 Original Cut & Nike Air Branding', Cushioning: 'Visible Air-Sole Heel Unit' }
    },
    {
      name: 'Nike Air Jordan 4 Retro (Bred Reimagined Leather)',
      slug: 'nike-air-jordan-4-retro-bred-reimagined',
      description: 'Reimagined in premium black tumbled leather instead of traditional nubuck: Fire Red accents, cement grey eyelets, Nike Air branding on the heel tab.',
      price: 215,
      discount_price: 215,
      stock: 25,
      image_url: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80'],
      rating: 5.0,
      num_reviews: 2900,
      is_featured: true,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Nike / Jordan', Material: 'Premium Tumbled Leather', Colorway: 'Black / Fire Red / Cement Grey' }
    },
    {
      name: 'Nike Air Jordan 3 Retro (White Cement Reimagined)',
      slug: 'nike-air-jordan-3-retro-white-cement-reimagined',
      description: 'Tinker Hatfield’s 1988 masterpiece: Elephant print overlays on toe and heel, soft white tumbled leather, visible Air window, vintage sail midsole.',
      price: 210,
      discount_price: 210,
      stock: 28,
      image_url: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80'],
      rating: 5.0,
      num_reviews: 2400,
      is_featured: true,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Nike / Jordan', Pattern: 'Iconic Elephant Print', Cushioning: 'Visible Air Sole' }
    },
    {
      name: 'Nike Air Jordan 11 Retro (Gratitude / DMP)',
      slug: 'nike-air-jordan-11-retro-gratitude-dmp',
      description: 'Glossy black patent leather wrapped around white tumbled leather: Metallic gold Jumpman emblem, carbon fiber shank plate, milky translucent outsole.',
      price: 230,
      discount_price: 230,
      stock: 20,
      image_url: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80'],
      rating: 5.0,
      num_reviews: 3100,
      is_featured: true,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Nike / Jordan', Mudguard: 'High-Cut Patent Leather', Shank: 'Carbon Fiber Spring Plate' }
    },
    {
      name: 'Nike Air Jordan 1 Low OG (Black Toe / Neutral Grey)',
      slug: 'nike-air-jordan-1-low-og-black-toe',
      description: 'Original low-top 1985 cut: Nike Air tongue tag, leather construction, classic Wings logo stitched on the heel tab.',
      price: 140,
      discount_price: 125,
      stock: 45,
      image_url: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 1850,
      is_featured: false,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Nike / Jordan', Cut: 'Low-Top OG Cut', Branding: 'Wings Logo on Heel' }
    },
    {
      name: 'Nike Air Jordan 1 Mid (Triple White Clean)',
      slug: 'nike-air-jordan-1-mid-triple-white',
      description: 'All-white leather mid-top sneaker with padded collar, perforated toe box, and solid rubber cupsole with encapsulated Air.',
      price: 125,
      discount_price: 109,
      stock: 60,
      image_url: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 2800,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Nike / Jordan', Colorway: 'Triple White', Profile: 'Mid-Top' }
    },
    {
      name: 'Nike LeBron XXI Performance Basketball Shoes',
      slug: 'nike-lebron-xxi-basketball-shoes',
      description: 'King James signature weapon: 360-degree zonal cabling system over dimensional mesh, heel and forefoot Zoom Air cushioning, carbon fiber midfoot shank.',
      price: 200,
      discount_price: 169,
      stock: 35,
      image_url: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 620,
      is_featured: true,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Nike Basketball', Signature: 'LeBron James', Air: 'Heel & Forefoot Zoom Air', Shank: 'Carbon Fiber' }
    },
    {
      name: 'Nike KD 17 Performance Basketball Shoes',
      slug: 'nike-kd-17-basketball-shoes',
      description: 'Kevin Durant 17th signature: Forefoot Air Zoom unit with full-length Nike Air Strobel cushioning, plastic cage wrapping inspired by the Air Max Plus.',
      price: 150,
      discount_price: 129,
      stock: 40,
      image_url: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 480,
      is_featured: false,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Nike Basketball', Signature: 'Kevin Durant', Cushioning: 'Air Dot Weld Strobel + Forefoot Zoom Air' }
    },
    {
      name: 'Nike Book 1 Devin Booker Signature Basketball Shoes',
      slug: 'nike-book-1-devin-booker-shoes',
      description: 'Workwear canvas and leather meet basketball performance: Top-loaded heel Zoom Air unit, Cushlon 2.0 foam midsole, herringbone traction.',
      price: 140,
      discount_price: 140,
      stock: 30,
      image_url: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 520,
      is_featured: true,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Nike Basketball', Signature: 'Devin Booker', Materials: 'Canvas, Nubuck Leather & Suede', Cushioning: 'Heel Zoom Air + Cushlon 2.0' }
    },
    {
      name: 'Nike Ja 1 Ja Morant Signature Basketball Shoes',
      slug: 'nike-ja-1-ja-morant-shoes',
      description: 'Explosive vertical bounce: Forefoot Air Zoom unit, containment lockdown strap system, raised foam collar for ankle support.',
      price: 120,
      discount_price: 105,
      stock: 45,
      image_url: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 790,
      is_featured: false,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Nike Basketball', Signature: 'Ja Morant', Air: 'Forefoot Zoom Air Unit' }
    },
    {
      name: 'Nike Jordan Tatum 2 Jayson Tatum Signature Shoes',
      slug: 'nike-jordan-tatum-2-jayson-tatum-shoes',
      description: 'Jordan brand’s lightest game shoe: Large foam and textile pods for impact relief, full-length Air Strobel cushioning, zero heavy rubber.',
      price: 125,
      discount_price: 109,
      stock: 35,
      image_url: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 410,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Jordan Basketball', Signature: 'Jayson Tatum', Cushioning: 'Full-Length Air Strobel' }
    },
    {
      name: 'Nike Jordan Luka 2 Luka Dončić Signature Basketball Shoes',
      slug: 'nike-jordan-luka-2-luka-doncic-shoes',
      description: 'Engineered for step-backs and deceleration: Formula 23 foam with Cushlon 3.0 wedge, IsoPlate TPU containment frame, lateral cage.',
      price: 130,
      discount_price: 110,
      stock: 40,
      image_url: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 580,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Jordan Basketball', Signature: 'Luka Dončić', Tech: 'IsoPlate + Formula 23 Foam' }
    },
    {
      name: 'Nike G.T. Cut 3 Elite Court Basketball Shoes',
      slug: 'nike-gt-cut-3-elite-shoes',
      description: 'First basketball shoe with full-length ZoomX foam: Modified herringbone traction, TPU lateral containment sidewall for sharp cuts.',
      price: 190,
      discount_price: 169,
      stock: 30,
      image_url: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 340,
      is_featured: true,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Nike Basketball', Foam: 'Full-Length ZoomX Foam', Support: 'TPU Lateral Stability Outrigger' }
    },
    {
      name: 'Nike G.T. Hustle 2 Responsive Basketball Shoes',
      slug: 'nike-gt-hustle-2-shoes',
      description: 'Full-length Zoom Air Strobel stitched directly underfoot: Lightweight engineered mesh, padded collar, responsive energy return.',
      price: 170,
      discount_price: 139,
      stock: 25,
      image_url: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 210,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Nike Basketball', Cushioning: 'Full-Length Zoom Air Strobel' }
    },
    {
      name: 'Nike Zoom Freak 5 Giannis Antetokounmpo Shoes',
      slug: 'nike-zoom-freak-5-giannis-shoes',
      description: 'Built for Euro-steps: Top-loaded forefoot Zoom Air unit, internal containment fit system, Smear Traction multidirectional outsole.',
      price: 130,
      discount_price: 105,
      stock: 45,
      image_url: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 620,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Nike Basketball', Signature: 'Giannis Antetokounmpo', Air: 'Top-Loaded Forefoot Zoom Air' }
    },
    {
      name: 'Nike Air Jordan 5 Retro (Olive / Orange Blaze)',
      slug: 'nike-air-jordan-5-retro-olive-orange-blaze',
      description: 'World War II fighter plane shark-teeth midsole graphics: 3M reflective tongue, lace locks, visible Air unit in the heel.',
      price: 210,
      discount_price: 189,
      stock: 20,
      image_url: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 980,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Nike / Jordan', Heritage: '1990 Fighter Plane Design', Tongue: '3M Reflective Material' }
    },
    {
      name: 'Nike Air Jordan 6 Retro (Gore-Tex Brown Kelp)',
      slug: 'nike-air-jordan-6-retro-gore-tex-brown-kelp',
      description: 'Waterproof GORE-TEX membrane meets the 1991 championship silhouette: Neoprene tongue, rubber pull tab, translucent icy outsole.',
      price: 250,
      discount_price: 220,
      stock: 18,
      image_url: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 450,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Nike / Jordan', Membrane: 'GORE-TEX Waterproof Lining', Year: '1991 First Championship' }
    },
    {
      name: 'Nike Air Jordan 13 Retro (Playoffs / Black Red)',
      slug: 'nike-air-jordan-13-retro-playoffs',
      description: 'Panther paw outsole design with holographic green panther eye emblem on the heel: Quilted leather side walls, Zoom Air cushioning.',
      price: 210,
      discount_price: 195,
      stock: 22,
      image_url: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 1100,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Nike / Jordan', Emblem: 'Holographic Green Cat Eye', Sole: 'Panther Paw Carbon Plate' }
    },
    {
      name: 'Nike Jordan Stadium 90 Lifestyle Sneakers',
      slug: 'nike-jordan-stadium-90-lifestyle-sneakers',
      description: 'Hybrid taking elements from AJ1 and AJ5: Real leather and ripstop upper, Formula 23 cushioning, flame-styled forefoot stitching.',
      price: 140,
      discount_price: 119,
      stock: 35,
      image_url: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80'],
      rating: 4.7,
      num_reviews: 380,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Nike / Jordan', Cushioning: 'Formula 23 Foam', Upper: 'Leather & Suede' }
    },
    {
      name: 'Nike Jordan Spizike Low Hybrid Sneakers',
      slug: 'nike-jordan-spizike-low-hybrid-sneakers',
      description: 'Spike Lee tribute combining AJ3, AJ4, AJ5, AJ6 and AJ20: Elephant print trim, grid mesh quarter, visible Air sole.',
      price: 160,
      discount_price: 139,
      stock: 30,
      image_url: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 490,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Nike / Jordan', Tribute: 'Spike Lee Mars Blackmon', Elements: 'AJ3, AJ4, AJ5, AJ6 Mashup' }
    },
    {
      name: 'Nike Jordan Max Aura 5 Basketball Lifestyle Shoes',
      slug: 'nike-jordan-max-aura-5-shoes',
      description: 'Durable leather and textile upper with visible Max Air heel unit: Embroidered Jumpman emblem, sturdy rubber herringbone outsole.',
      price: 130,
      discount_price: 109,
      stock: 50,
      image_url: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80'],
      rating: 4.7,
      num_reviews: 840,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Nike / Jordan', Air: 'Visible Max Air Heel Bubble' }
    },
    {
      name: 'Nike Jordan Stay Loyal 3 Classic High-Top Shoes',
      slug: 'nike-jordan-stay-loyal-3-shoes',
      description: 'AJ4 inspired heel tab and eyestays with Nike Air cushioning: Full leather overlays, embroidered Jumpman.',
      price: 115,
      discount_price: 94,
      stock: 45,
      image_url: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80'],
      rating: 4.6,
      num_reviews: 620,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Nike / Jordan', Cushioning: 'Nike Air Sole' }
    },
    {
      name: 'Nike Jordan Jumpman Two Trey Basketball Shoes',
      slug: 'nike-jordan-jumpman-two-trey-shoes',
      description: 'Nod to MJ’s championship era in Chicago: Genuine leather and mesh upper, padded collar, Zoom Air cushioning.',
      price: 155,
      discount_price: 129,
      stock: 35,
      image_url: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 710,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Nike / Jordan', Cushioning: 'Forefoot Zoom Air' }
    },
    {
      name: 'Nike Jordan Nu Retro 1 Low Basketball Lifestyle Shoes',
      slug: 'nike-jordan-nu-retro-1-low-shoes',
      description: '2002 early millennium archive return: Oversized embossed Wings logo across the side panel, split rubber cupsole with Nike Air.',
      price: 105,
      discount_price: 89,
      stock: 40,
      image_url: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80'],
      rating: 4.7,
      num_reviews: 390,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Nike / Jordan', Logo: 'Embossed Wings on Leather Side', Year: '2002 Archive' }
    },

    // --- 3. NIKE SPORTSWEAR & AIR MAX ICONS (22 Models) ---
    {
      name: "Nike Air Force 1 '07 Classic (Triple White Leather)",
      slug: 'nike-air-force-1-07-triple-white-leather',
      description: 'The world’s most recognized sneaker: Crisp full-grain leather, perforated toe box, metal AF1 lace dubrae, encapsulated Nike Air cushioning, thick pivot-point rubber cupsole.',
      price: 115,
      discount_price: 115,
      stock: 120,
      image_url: 'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?auto=format&fit=crop&w=800&q=80'],
      rating: 5.0,
      num_reviews: 9800,
      is_featured: true,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Nike', Leather: 'Full-Grain Crisp Leather', Dubrae: 'Metallic AF1 Lace Lock', Air: 'Encapsulated Nike Air-Sole' }
    },
    {
      name: "Nike Air Force 1 '07 (Triple Black Leather)",
      slug: 'nike-air-force-1-07-triple-black-leather',
      description: 'All-black leather edition of the 1982 icon: Stitched leather overlays, padded low-cut collar, durable non-marking rubber outsole.',
      price: 115,
      discount_price: 115,
      stock: 100,
      image_url: 'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 6400,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Nike', Colorway: 'Triple Black', Outsole: 'Pivot Circle Solid Rubber' }
    },
    {
      name: 'Nike Dunk Low Retro (White / Black Panda)',
      slug: 'nike-dunk-low-retro-white-black-panda',
      description: 'The global street-culture phenomenon: Smooth leather upper with contrasting black and white color-blocking, perforated toe, foam midsole, rubber traction outsole.',
      price: 115,
      discount_price: 115,
      stock: 90,
      image_url: 'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?auto=format&fit=crop&w=800&q=80'],
      rating: 5.0,
      num_reviews: 7200,
      is_featured: true,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Nike', Colorway: 'White / Black Panda', Upper: 'Smooth Leather', Outsole: 'Herringbone Pivot Tread' }
    },
    {
      name: 'Nike Dunk Low Retro (Grey Fog / White)',
      slug: 'nike-dunk-low-retro-grey-fog',
      description: 'Subtle clean two-tone grey fog overlays over white leather base: padded low-cut collar, woven Nike tongue label.',
      price: 115,
      discount_price: 105,
      stock: 65,
      image_url: 'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 2100,
      is_featured: false,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Nike', Colorway: 'Grey Fog / White' }
    },
    {
      name: 'Nike Dunk High Retro Basketball Sneakers',
      slug: 'nike-dunk-high-retro-sneakers',
      description: 'Classic high-top basketball cut with padded collar: Leather overlays, perforated toe, lightweight foam cushioning.',
      price: 125,
      discount_price: 109,
      stock: 40,
      image_url: 'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 1450,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Nike', Cut: 'High-Top Ankle Collar', Leather: 'Full Leather' }
    },
    {
      name: 'Nike Air Max Dn Dynamic Air Lifestyle Shoes',
      slug: 'nike-air-max-dn-dynamic-air-shoes',
      description: 'Next generation of Air innovation: Dynamic Air unit system with dual-chamber, four-tubed pressurized Air units that shift air seamlessly with every step, multi-layered mesh upper with haptic texture.',
      price: 160,
      discount_price: 145,
      stock: 50,
      image_url: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80'],
      rating: 5.0,
      num_reviews: 890,
      is_featured: true,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Nike', Innovation: 'Dynamic Air Dual-Chamber 4-Tube System', Upper: 'Multi-Layered Mesh with Haptic Print' }
    },
    {
      name: 'Nike Air Max 90 Classic (Infrared / White / Black)',
      slug: 'nike-air-max-90-classic-infrared',
      description: 'The 1990 running icon: Stitched overlays and classic TPU accents on the heel and eyestays, Max Air heel unit, waffle rubber outsole.',
      price: 130,
      discount_price: 110,
      stock: 70,
      image_url: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 4200,
      is_featured: true,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Nike', Air: 'Visible Max Air Unit', Heritage: '1990 Tinker Hatfield Design' }
    },
    {
      name: "Nike Air Max 1 '86 Original Big Bubble",
      slug: 'nike-air-max-1-86-big-bubble',
      description: 'Recreated using 3D CT scans of the true 1986 prototype: Enlarged four-window Air unit, suede and mesh upper, original sport red colorway.',
      price: 150,
      discount_price: 135,
      stock: 35,
      image_url: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80'],
      rating: 5.0,
      num_reviews: 1400,
      is_featured: true,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Nike', AirUnit: '1986 Enlarged Big Bubble Air Unit', Origin: 'First Visible Air Sneaker' }
    },
    {
      name: 'Nike Air Max 95 (Neon Yellow / Gradient Grey)',
      slug: 'nike-air-max-95-neon-yellow',
      description: 'Human anatomy inspired design by Sergio Lozano: Rib-cage lacing, muscle gradient suede side panels, spine outsole, dual forefoot and heel visible Air.',
      price: 175,
      discount_price: 159,
      stock: 40,
      image_url: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 2800,
      is_featured: false,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Nike', Inspiration: 'Human Anatomy Muscle Fibers & Ribs', Air: 'Dual Forefoot & Heel Visible Air' }
    },
    {
      name: 'Nike Air Max 97 (Silver Bullet / Metallic)',
      slug: 'nike-air-max-97-silver-bullet',
      description: 'Japanese bullet train ripple aesthetics: Full-length visible Air unit, metallic silver leather and mesh upper with 3M reflective wave lines.',
      price: 175,
      discount_price: 159,
      stock: 45,
      image_url: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 3100,
      is_featured: true,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Nike', Air: 'Full-Length Visible Air-Sole', Reflective: '3M 360° Reflective Piping' }
    },
    {
      name: 'Nike Air Max Plus (Tuned 1 / Hyper Blue / Sunset)',
      slug: 'nike-air-max-plus-tuned-1',
      description: 'Iconic street culture TN: Palm tree inspired TPU rib cage, whale-tail midfoot shank arch, Tuned Air (Tuned Air) dual-hemisphere cushioning.',
      price: 180,
      discount_price: 160,
      stock: 45,
      image_url: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 2600,
      is_featured: true,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Nike', Technology: 'Tuned Air (TN) Hemispheres', Shank: 'Whale Tail Arch Support' }
    },
    {
      name: 'Nike Air Max 270 Lifestyle Running Shoes',
      slug: 'nike-air-max-270-shoes',
      description: 'Massive 270-degree visible Air heel unit (32mm tall): Breathable engineered mesh knit upper, bootie construction, dual-density foam forefoot.',
      price: 160,
      discount_price: 129,
      stock: 75,
      image_url: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 4900,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Nike', HeelAir: '32mm Tall 270-Degree Air Unit', Fit: 'Slip-on Bootie' }
    },
    {
      name: 'Nike Zoom Vomero 5 Retro Y2K Running Shoes',
      slug: 'nike-zoom-vomero-5-retro-shoes',
      description: 'The Y2K aesthetic runner taking over global street style: Plastic cage quarter panels, ventilated heel counter, Zoom Air cushioning in forefoot and heel, Bill Bowerman insole portrait.',
      price: 160,
      discount_price: 145,
      stock: 55,
      image_url: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80'],
      rating: 5.0,
      num_reviews: 1980,
      is_featured: true,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Nike', Air: 'Dual Heel & Forefoot Zoom Air Units', Cage: 'Plastic Venting Rib Cage' }
    },
    {
      name: 'Nike P-6000 Retro Metallic Millennium Runners',
      slug: 'nike-p-6000-retro-metallic-runners',
      description: 'Mashup of the Pegasus 25 and Pegasus 2006: Breathable mesh with horizontal and vertical metallic leather overlays, thick foam midsole.',
      price: 110,
      discount_price: 94,
      stock: 50,
      image_url: 'https://images.unsplash.com/photo-1587563871167-1ee9c731aefb?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1587563871167-1ee9c731aefb?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 1420,
      is_featured: false,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Nike', Heritage: '2006 Bowerman Series Runner', Upper: 'Metallic Overlays & Breathable Mesh' }
    },
    {
      name: 'Nike Blazer Mid 77 Vintage High-Top Sneakers',
      slug: 'nike-blazer-mid-77-vintage-sneakers',
      description: 'Old-school basketball styling: Exposed foam tongue, textured suede toe bumper and side panels, solid rubber herringbone cupsole.',
      price: 105,
      discount_price: 89,
      stock: 70,
      image_url: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 3800,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Nike', Tongue: 'Exposed Vintage Foam Tongue', Upper: 'Leather with Suede Overlays' }
    },
    {
      name: 'Nike Cortez Classic Leather Heritage Shoes',
      slug: 'nike-cortez-classic-leather-shoes',
      description: 'Bill Bowerman’s 1972 track masterpiece: Smooth leather upper, iconic sponge EVA wedge midsole, herringbone serrated rubber outsole.',
      price: 90,
      discount_price: 79,
      stock: 65,
      image_url: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 2900,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Nike', Year: '1972 Original Track Silhouette', Midsole: 'Striped Wedge EVA' }
    },
    {
      name: 'Nike Killshot 2 Leather Tennis Shoes (Sail / Midnight Navy)',
      slug: 'nike-killshot-2-leather-tennis-shoes',
      description: 'Low-profile racquet court icon: Textured leather with genuine suede overlays, contrast leather Swoosh, and natural gum rubber outsole.',
      price: 90,
      discount_price: 79,
      stock: 60,
      image_url: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 2100,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Nike', Outsole: 'Natural Gum Rubber', Upper: 'Leather & Suede' }
    },
    {
      name: 'Nike Shox TL Triple Black Mechanical Springs Shoes',
      slug: 'nike-shox-tl-triple-black-shoes',
      description: 'Mechanical shock absorption: Full-length Nike Shox flexible columns, breathable mesh upper, TPU cage overlays.',
      price: 170,
      discount_price: 154,
      stock: 30,
      image_url: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 1200,
      is_featured: true,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Nike', Technology: 'Full-Length Nike Shox Columns', Colorway: 'Triple Black' }
    },
    {
      name: 'Nike Air Max SYSTM Heritage Running Shoes',
      slug: 'nike-air-max-systm-shoes',
      description: '80s-inspired running look with visible Air cushioning: Mixed-material upper combining leather, mesh, and synthetic overlays.',
      price: 100,
      discount_price: 84,
      stock: 55,
      image_url: 'https://images.unsplash.com/photo-1587563871167-1ee9c731aefb?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1587563871167-1ee9c731aefb?auto=format&fit=crop&w=800&q=80'],
      rating: 4.6,
      num_reviews: 780,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Nike', Air: 'Visible Max Air Unit', Style: 'Retro 80s Vibe' }
    },
    {
      name: 'Nike Air Max SC Clean Everyday Shoes',
      slug: 'nike-air-max-sc-clean-shoes',
      description: 'Laid-back track heritage: Visible Air unit, durable leather, and breathable mesh for all-day comfort.',
      price: 90,
      discount_price: 74,
      stock: 80,
      image_url: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80'],
      rating: 4.7,
      num_reviews: 1650,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Nike', Air: 'Air Max Heel Cushioning' }
    },
    {
      name: 'Nike Calm Slide Ergonomic Foam Sandals',
      slug: 'nike-calm-slide-ergonomic-sandals',
      description: 'Seamless minimalist water-friendly slide: Contoured soft foam construction, textured footbed grip, full-length rubber outsole.',
      price: 50,
      discount_price: 42,
      stock: 110,
      image_url: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 2400,
      is_featured: false,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Nike', Foam: 'One-Piece Sculpted Soft Foam', Water: 'Water-Friendly & Quick Drying' }
    },
    {
      name: 'Nike Victori One Sport Slide Sandal',
      slug: 'nike-victori-one-sport-slide',
      description: 'Padded strap and responsive mechanical foam cushioning: Rolled top edge on the strap, traction pattern sole.',
      price: 35,
      discount_price: 29,
      stock: 130,
      image_url: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80'],
      rating: 4.7,
      num_reviews: 3100,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Nike', Strap: 'Padded Synthetic Leather Strap' }
    },

    // --- 4. NIKE FOOTBALL & ATHLETICS (20 Models) ---
    {
      name: 'Nike Mercurial Superfly 10 Elite FG Football Boots',
      slug: 'nike-mercurial-superfly-10-elite-fg-boots',
      description: '3/4-length articulated Air Zoom unit built into the soleplate: Gripknit sticky upper for elite high-speed ball control, Flyknit Dynamic Fit collar, tri-star speed studs.',
      price: 295,
      discount_price: 275,
      stock: 22,
      image_url: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80'],
      rating: 5.0,
      num_reviews: 580,
      is_featured: true,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Nike Football', Air: '3/4-Length Articulated Zoom Air Unit', Upper: 'Nike Gripknit Material', Collar: 'Dynamic Fit High Ankle Sock' }
    },
    {
      name: 'Nike Mercurial Vapor 16 Elite Firm Ground Boots',
      slug: 'nike-mercurial-vapor-16-elite-fg-boots',
      description: 'Low-cut speed weapon: 3/4 Zoom Air plate, Gripknit textured touch, ultra-lightweight chassis engineered for pure acceleration.',
      price: 260,
      discount_price: 240,
      stock: 25,
      image_url: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80'],
      rating: 5.0,
      num_reviews: 490,
      is_featured: true,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Nike Football', Profile: 'Low-Cut Speed Chassis', Sole: '3/4 Zoom Air Plate' }
    },
    {
      name: 'Nike Phantom GX II Elite FG Precision Boots',
      slug: 'nike-phantom-gx-ii-elite-fg-boots',
      description: 'Revolutionary Gripknit yarn covers the strike zone: Cyclone 360 rotational traction stud pattern helps players make quick agility pivots.',
      price: 260,
      discount_price: 239,
      stock: 20,
      image_url: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 320,
      is_featured: false,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Nike Football', Studs: 'Cyclone 360 Rotational Studs', Material: 'Nike Gripknit Yarn' }
    },
    {
      name: 'Nike Phantom Luna II Elite FG High-Collar Boots',
      slug: 'nike-phantom-luna-ii-elite-fg-boots',
      description: 'Anatomical cuff and Cyclone 360 stud system co-created with elite athletes: Gripknit texturing for pinpoint curved passing and finishing.',
      price: 285,
      discount_price: 259,
      stock: 18,
      image_url: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 240,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Nike Football', Collar: 'Anatomical Asymmetric Cuff', Traction: 'Cyclone 360' }
    },
    {
      name: 'Nike Tiempo Legend 10 Elite FG Leather Boots',
      slug: 'nike-tiempo-legend-10-elite-fg-boots',
      description: 'Engineered FlyTouch Plus synthetic leather is softer than natural leather and does not over-absorb water: Microdots amplify ball touch.',
      price: 240,
      discount_price: 219,
      stock: 25,
      image_url: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80'],
      rating: 5.0,
      num_reviews: 380,
      is_featured: true,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Nike Football', Material: 'FlyTouch Plus Synthetic Leather (Water-Repellent)', Touch: '3D Molded Touch Pods' }
    },
    {
      name: 'Nike Premier 3 Firm Ground Classic Leather Boots',
      slug: 'nike-premier-3-fg-leather-boots',
      description: 'Pure kangaroo/cow leather touch: Fold-over tongue with cut line for customization, classic conical studs for reliable pitch grip.',
      price: 110,
      discount_price: 99,
      stock: 40,
      image_url: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 920,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Nike Football', Leather: 'Soft Kangaroo-Touch Leather', Tongue: 'Fold-Over Cut-Line Tongue' }
    },
    {
      name: 'Nike Premier League Flight Official Match Ball',
      slug: 'nike-premier-league-flight-official-match-ball',
      description: 'Aerowsculpt molded grooves disrupt airflow around the ball for 30% truer flight: All Conditions Control (ACC) 3D ink overlay, 4-panel fused construction.',
      price: 170,
      discount_price: 154,
      stock: 30,
      image_url: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=800&q=80'],
      rating: 5.0,
      num_reviews: 410,
      is_featured: true,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Nike Football', Aerodynamics: 'Aerowsculpt Molded Grooves', Tech: 'All Conditions Control (ACC)', Tournament: 'English Premier League Official' }
    },
    {
      name: 'Nike Vapor Grip3 Professional Goalkeeper Gloves',
      slug: 'nike-vapor-grip3-goalkeeper-gloves',
      description: 'Grip3 patented technology wraps foam around thumb, forefinger, and pinky: 4mm Contact Plus latex foam absorbs hardest shots.',
      price: 120,
      discount_price: 105,
      stock: 25,
      image_url: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 210,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Nike Football', Palm: '4mm Contact Plus Latex', Tech: 'Patented Grip3 Wrapped Finger Cut' }
    },
    {
      name: 'Nike Dri-FIT Strike Soccer Drill Top',
      slug: 'nike-dri-fit-strike-soccer-drill-top',
      description: 'Slim streamlined fit with hidden thumb loops: Breathable stretch knit fabric with sweat-wicking Dri-FIT technology.',
      price: 75,
      discount_price: 62,
      stock: 75,
      image_url: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 1100,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Nike', Technology: 'Dri-FIT Moisture Control', Sleeves: 'Invisible Thumb Loops' }
    },
    {
      name: 'Nike Dri-FIT Strike Tapered Soccer Pants',
      slug: 'nike-dri-fit-strike-tapered-pants',
      description: 'Speed-focused slim fit: Lower leg zips make quick changes over cleats effortless, zip pockets secure keys and phone.',
      price: 70,
      discount_price: 58,
      stock: 85,
      image_url: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 1450,
      is_featured: false,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Nike', Fit: 'Slim Tapered Leg with Ankle Zips', Fabric: 'Dri-FIT Stretch Knit' }
    },
    {
      name: 'Nike Academy Pro 24 Training Tracksuit (Set)',
      slug: 'nike-academy-pro-24-training-tracksuit',
      description: 'Full zip jacket and matching tapered pants set in lightweight sweat-wicking knit: mesh paneling for breathability.',
      price: 110,
      discount_price: 94,
      stock: 60,
      image_url: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 820,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Nike', Set: 'Track Jacket + Tapered Pants Set', Tech: 'Dri-FIT' }
    },
    {
      name: 'Nike Charge Hard Shield Soccer Shin Guards',
      slug: 'nike-charge-hard-shield-shin-guards',
      description: 'Anatomical stirrup pull-on design with hard polypropylene shell and molded EVA foam backing: attached ankle guard.',
      price: 22,
      discount_price: 18,
      stock: 95,
      image_url: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=800&q=80'],
      rating: 4.7,
      num_reviews: 940,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Nike Football', Shell: 'High-Density Polypropylene', Ankle: 'Integrated Ankle Sock Padding' }
    },
    {
      name: 'Nike Mercurial Lite Shin Guards with Breathable Sleeves',
      slug: 'nike-mercurial-lite-shin-guards',
      description: 'Low-profile seamless slip-in shin guards: dense foam backing disperses impact, breathable stretchy retention sleeve.',
      price: 28,
      discount_price: 24,
      stock: 90,
      image_url: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 1350,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Nike Football', Profile: 'Low-Profile Mercurial Slip-In', Sleeves: 'Dri-FIT Breathable Sleeves' }
    },
    {
      name: 'Nike Pitch Soccer Ball (Size 5)',
      slug: 'nike-pitch-soccer-ball-size-5',
      description: 'High-contrast graphic visual tracking: 12-panel machine-stitched design, rubber bladder preserves air pressure.',
      price: 25,
      discount_price: 20,
      stock: 120,
      image_url: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=800&q=80'],
      rating: 4.7,
      num_reviews: 2100,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Nike Football', Panels: '12-Panel Machine Stitched', Bladder: 'Reinforced Rubber' }
    },
    {
      name: 'Nike Squad Over-The-Calf Soccer Socks',
      slug: 'nike-squad-over-the-calf-soccer-socks',
      description: 'Zonal cushioning underneath cleat pressure points: dynamic arch support, sweat-wicking Dri-FIT fabric.',
      price: 18,
      discount_price: 15,
      stock: 180,
      image_url: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 1650,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Nike', Length: 'Over-the-Calf', Cushioning: 'Zonal Impact Pods' }
    },

    // --- 5. NIKE TECH FLEECE & ATHLETIC APPAREL (22 Models) ---
    {
      name: 'Nike Tech Fleece Windrunner Full-Zip Hoodie',
      slug: 'nike-tech-fleece-windrunner-hoodie',
      description: 'Premium lightweight warmth without bulk: Smooth on both sides, signature transparent taping highlights chevron chest lines, zippered sleeve pocket.',
      price: 145,
      discount_price: 125,
      stock: 70,
      image_url: 'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1556905055-8f358a7a47b2?auto=format&fit=crop&w=800&q=80'],
      rating: 5.0,
      num_reviews: 3800,
      is_featured: true,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Nike', Material: 'Double-Sided Smooth Tech Fleece (66% Cotton, 34% Poly)', Pocket: 'Bonded Sleeve Zip Pocket' }
    },
    {
      name: 'Nike Tech Fleece Slim-Fit Joggers',
      slug: 'nike-tech-fleece-slim-fit-joggers',
      description: 'The iconic streetwear sweatpants: Tapered fit down to tall ribbed cuffs, large taped zip pocket with interior organizer pouch, drawcord waist.',
      price: 125,
      discount_price: 109,
      stock: 80,
      image_url: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=800&q=80'],
      rating: 5.0,
      num_reviews: 4200,
      is_featured: true,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Nike', Fit: 'Slim Tapered Leg', Cuffs: 'Tall Ribbed Cuffs', Storage: 'Signature Zippered Tech Pocket' }
    },
    {
      name: 'Nike Club Fleece Pullover Brushed-Back Hoodie',
      slug: 'nike-club-fleece-pullover-hoodie',
      description: 'Cozy brushed-back fleece everyday standard: Embroidered Futura logo on left chest, front kangaroo pocket, adjustable drawcord hood.',
      price: 65,
      discount_price: 52,
      stock: 110,
      image_url: 'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1556905055-8f358a7a47b2?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 6400,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Nike', Material: '80% Cotton / 20% Polyester Brushed Fleece' }
    },
    {
      name: 'Nike Club Fleece Cargo Joggers',
      slug: 'nike-club-fleece-cargo-joggers',
      description: 'Soft brushed fleece joggers equipped with dual side cargo flap pockets for versatile utilitarian streetwear styling.',
      price: 70,
      discount_price: 58,
      stock: 85,
      image_url: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 2100,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Nike', Pockets: 'Dual Snap Cargo Flap Pockets', Fabric: 'Brushed Club Fleece' }
    },
    {
      name: 'Nike Solo Swoosh Heavyweight Fleece Crew Sweatshirt',
      slug: 'nike-solo-swoosh-heavyweight-fleece-crew',
      description: 'Premium heavyweight cotton fleece with minimalist embroidered mini Swoosh: dropped shoulders, roomy boxy streetwear fit.',
      price: 95,
      discount_price: 82,
      stock: 45,
      image_url: 'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1556905055-8f358a7a47b2?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 820,
      is_featured: true,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Nike', Line: 'Solo Swoosh Lab Edition', Weight: 'Heavyweight Dense Fleece' }
    },
    {
      name: 'Nike Pro Dri-FIT Compression Long-Sleeve Shirt',
      slug: 'nike-pro-dri-fit-compression-long-sleeve',
      description: 'Tight body-hugging compression fit: Lightweight stretch fabric with Dri-FIT wicking, high-heat zone mesh ventilation.',
      price: 40,
      discount_price: 32,
      stock: 90,
      image_url: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 3100,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Nike Pro', Fit: 'Compression Muscle Lock', Tech: 'Dri-FIT' }
    },
    {
      name: 'Nike Pro Dri-FIT 3/4 Length Compression Tights',
      slug: 'nike-pro-dri-fit-3-4-tights',
      description: 'Calf-length compression tights: jacquard Nike Pro elastic waistband, reinforced knees, flat seams preventing friction.',
      price: 38,
      discount_price: 30,
      stock: 85,
      image_url: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 1750,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Nike Pro', Cut: '3/4 Calf Length', Waist: 'Branded Jacquard Elastic' }
    },
    {
      name: 'Nike Dri-FIT Stride 5-Inch Running Shorts with Brief',
      slug: 'nike-dri-fit-stride-5-inch-running-shorts',
      description: 'Built for unrestricted motion: shallow rise, ergonomic brief liner, zippered rear phone pocket with moisture barrier.',
      price: 55,
      discount_price: 44,
      stock: 95,
      image_url: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 2100,
      is_featured: false,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Nike', Inseam: '5 Inch Inseam', Pocket: 'Sweat-Barrier Zip Phone Pocket' }
    },
    {
      name: 'Nike Windrunner Repel Water-Resistant Running Jacket',
      slug: 'nike-windrunner-repel-running-jacket',
      description: 'Classic 26-degree chevron jacket with UV protection and water-repellent finish: back vent for air flow, packs into hood.',
      price: 115,
      discount_price: 98,
      stock: 50,
      image_url: 'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1556905055-8f358a7a47b2?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 1400,
      is_featured: true,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Nike', Icon: '1978 Chevron 26° Windrunner Angle', Weather: 'UVA/UVB Sun Shield + DWR Repel' }
    },
    {
      name: 'Nike Storm-FIT ADV Down GORE-TEX Parka',
      slug: 'nike-storm-fit-adv-down-parka',
      description: 'Sub-zero extreme winter fortress: GORE-TEX waterproof shell, premium high-fill down insulation, magnetic draft flap.',
      price: 450,
      discount_price: 399,
      stock: 15,
      image_url: 'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1556905055-8f358a7a47b2?auto=format&fit=crop&w=800&q=80'],
      rating: 5.0,
      num_reviews: 110,
      is_featured: true,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Nike', Technology: 'Storm-FIT ADV + GORE-TEX Membrane', Insulation: 'Premium Real Down' }
    },

    // --- 6. NIKE BAGS, HATS & ACCESSORIES (10 Models) ---
    {
      name: 'Nike Brasilia 9.5 Training 30L Backpack',
      slug: 'nike-brasilia-9-5-training-backpack',
      description: 'Spacious 30L volume: Padded internal sleeve for up to 15" laptops, separate ventilated footwear zip compartment, water-resistant coated bottom.',
      price: 50,
      discount_price: 40,
      stock: 120,
      image_url: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 3900,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Nike', Volume: '30 Liters (XL)', Laptop: 'Padded 15" Sleeve', Base: 'Coated Heavy-Duty Floor' }
    },
    {
      name: 'Nike Brasilia Medium 60L Duffel Gym Bag',
      slug: 'nike-brasilia-medium-60l-duffel-bag',
      description: 'Dual-zip main cavern, exterior ventilated shoe storage tunnel, padded shoulder strap with movable cushion.',
      price: 45,
      discount_price: 36,
      stock: 90,
      image_url: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 2450,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Nike', Capacity: '60 Liters', ShoePocket: 'Ventilated Side Shoe Pocket' }
    },
    {
      name: 'Nike Heritage Crossbody Bag (4L)',
      slug: 'nike-heritage-crossbody-bag-4l',
      description: 'Compact hands-free shoulder bag: Adjustable cross-body strap, zippered main compartment with internal slip pockets.',
      price: 30,
      discount_price: 25,
      stock: 140,
      image_url: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 3100,
      is_featured: false,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Nike', Capacity: '4 Liters', Strap: 'Adjustable Buckle Crossbody Strap' }
    },
    {
      name: 'Nike Everyday Cushion Crew Socks 3-Pack',
      slug: 'nike-everyday-cushion-crew-socks-3-pack',
      description: 'Thick terry sole cushioning, ribbed arch support compression band, Dri-FIT sweat management keeps feet dry.',
      price: 22,
      discount_price: 18,
      stock: 200,
      image_url: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 8900,
      is_featured: true,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Nike', Quantity: '3 Pairs', Footbed: 'Thick Terry Cotton Cushion' }
    },
    {
      name: 'Nike Club Curved Brim Featherlight Cap',
      slug: 'nike-club-curved-brim-featherlight-cap',
      description: 'Featherlight Dri-FIT fabric with laser perforations for airflow, metal tri-glide buckle adjuster on the back strap.',
      price: 28,
      discount_price: 24,
      stock: 110,
      image_url: 'https://images.unsplash.com/photo-1588850561407-ed78c282e89b?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1588850561407-ed78c282e89b?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 1650,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Nike', Technology: 'Dri-FIT Featherlight', Closure: 'Metal Tri-Glide Adjuster' }
    },
    {
      name: 'Nike HyperCharge 32oz Straw Stainless Steel Bottle',
      slug: 'nike-hypercharge-32oz-straw-bottle',
      description: 'Double-wall vacuum insulated stainless steel keeps water icy cold: Leak-resistant slider spout, ergonomic carry loop handle.',
      price: 40,
      discount_price: 34,
      stock: 90,
      image_url: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 1100,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Nike', Capacity: '32 oz (946 ml)', Material: 'BPA-Free Vacuum Insulated Stainless Steel' }
    },
    {
      name: 'Nike Push Up Grips 2.0 Ergonomic Training Handles',
      slug: 'nike-push-up-grips-2-0',
      description: 'Elevated push-up handles reduce wrist strain and deepen chest range of motion: non-slip rubberized base.',
      price: 35,
      discount_price: 29,
      stock: 60,
      image_url: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 580,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Nike Training', Base: 'Non-Skid Rubber Base', Ergonomics: 'Contoured Soft-Grip Handles' }
    },
    {
      name: 'Nike Mastery 5mm Yoga & Training Mat',
      slug: 'nike-mastery-5mm-yoga-mat',
      description: 'Engineered natural rubber with cool-stone finish delivers non-slip grip even through sweaty hot vinyasa sessions: 5mm density.',
      price: 90,
      discount_price: 79,
      stock: 40,
      image_url: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 420,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Nike', Thickness: '5 mm High-Density Cushion', Material: 'Natural Rubber with Cool-Touch Grip' }
    },
    {
      name: 'Nike Pro Combat Knee Sleeve 2.0 with Gel Ring',
      slug: 'nike-pro-combat-knee-sleeve-2-0',
      description: 'Targeted compression with breathable Ariaprene mesh and molded patella gel stabilization ring.',
      price: 30,
      discount_price: 25,
      stock: 80,
      image_url: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 790,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Nike Pro', Support: 'Molded Gel Patella Ring', Breathability: 'Ariaprene Air-Mesh' }
    },
    {
      name: 'Nike Printed Dri-FIT Headband 2.0',
      slug: 'nike-printed-dri-fit-headband',
      description: 'Silicone internal grip band keeps hair and sweat out of eyes during intense games: Dri-FIT moisture absorption.',
      price: 18,
      discount_price: 15,
      stock: 140,
      image_url: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=800&q=80'],
      rating: 4.7,
      num_reviews: 1300,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Nike', Grip: 'Internal Non-Slip Silicone Line', Tech: 'Dri-FIT' }
    }
  ];
};
