// backend/utils/pumaProductsData.js
// 108 Unique, Non-Repeating Official Puma Products (Nitro Running, Football Cleats, Palermo/Suede Terrace Classics, Scuderia Ferrari/BMW Motorsport, MB.03 Basketball & Training)

export const getPumaProducts = (categoryId) => {
  return [
    // --- 1. PUMA RUNNING, RACING & TRACK INNOVATION (20 Models) ---
    {
      name: 'Puma Fast-R Nitro Elite 2 Road Racing Shoes',
      slug: 'puma-fast-r-nitro-elite-2-road-racing-shoes',
      description: 'Puma groundbreaking marathon racer: Exposed PWRPLATE carbon-fiber plate extending beyond the toe, two-part decoupled midsole with nitrogen-infused NITROFOAM ELITE, and ultra-breathable ULTRAWEAVE upper.',
      price: 260,
      discount_price: 239,
      stock: 30,
      image_url: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80'],
      rating: 5.0,
      num_reviews: 240,
      is_featured: true,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Puma', Foam: 'NITROFOAM ELITE (Nitrogen-Infused)', Plate: 'PWRPLATE Carbon Fiber', Upper: 'ULTRAWEAVE Monomesh', Outsole: 'PUMAGRIP LT' }
    },
    {
      name: 'Puma Deviate Nitro Elite 3 Marathon Running Shoes',
      slug: 'puma-deviate-nitro-elite-3-marathon-running-shoes',
      description: 'Sub-200g carbon-plated road racing marvel: 100% aliphatic TPU NITROFOAM ELITE for 93% energy return, redesigned full-length scoop carbon PWRPLATE, and featherweight engineered mesh.',
      price: 230,
      discount_price: 209,
      stock: 35,
      image_url: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 410,
      is_featured: true,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Puma', Technology: 'NITROFOAM ELITE + PWRPLATE', Weight: '194g', StackHeight: '40mm / 32mm (8mm drop)' }
    },
    {
      name: 'Puma Deviate Nitro 3 Carbon-Plated Everyday Trainer',
      slug: 'puma-deviate-nitro-3-carbon-plated-everyday-trainer',
      description: 'The super-trainer for high-cadence tempos and long runs: Dual-layer NITROFOAM and NITROFOAM ELITE sandwiching an adaptive carbon PWRPLATE with high-traction PUMAGRIP rubber.',
      price: 160,
      discount_price: 139,
      stock: 50,
      image_url: 'https://images.unsplash.com/photo-1587563871167-1ee9c731aefb?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1587563871167-1ee9c731aefb?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 580,
      is_featured: true,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Puma', Cushioning: 'Dual NITROFOAM + NITROFOAM ELITE', Plate: 'Full Carbon Composite PWRPLATE', Outsole: 'PUMAGRIP Rubber' }
    },
    {
      name: 'Puma Velocity Nitro 3 Daily Road Running Shoes',
      slug: 'puma-velocity-nitro-3-daily-road-running-shoes',
      description: 'Puma flagship neutral daily running shoe: Upgraded nitrogen-injected NITROFOAM top layer, PROFOAMLITE bottom layer for durability, and engineered mesh with PWRTAPE reinforcement.',
      price: 135,
      discount_price: 115,
      stock: 80,
      image_url: 'https://images.unsplash.com/photo-1608231387042-66d1773070a5?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1608231387042-66d1773070a5?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 740,
      is_featured: false,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Puma', Midsole: 'NITROFOAM + PROFOAMLITE', Reinforcement: 'PWRTAPE Targeted Support', Category: 'Daily Neutral Runner' }
    },
    {
      name: 'Puma ForeverRun Nitro Stability Running Shoes',
      slug: 'puma-foreverrun-nitro-stability-running-shoes',
      description: 'Guidance-tuned stability runner engineered with runLAB: Dual-density NITROFOAM midsole with firmer perimeter rim, asymmetric heel counter, and flared rubber outsole.',
      price: 150,
      discount_price: 129,
      stock: 45,
      image_url: 'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 320,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Puma', Stability: 'RUNGUIDE System & Dual-Density NITROFOAM', Drop: '10 mm', Fit: 'Supportive Engineered Mesh' }
    },
    {
      name: 'Puma Magnify Nitro 2 Maximum Cushion Road Shoes',
      slug: 'puma-magnify-nitro-2-maximum-cushion-road-shoes',
      description: 'Maximum plush cushioning: Thickest single-pour NITROFOAM midsole in the Puma line, molded heel collar, breathable knit upper, and all-weather PUMAGRIP rubber.',
      price: 150,
      discount_price: 125,
      stock: 40,
      image_url: 'https://images.unsplash.com/photo-1600185365926-3a2ce3cdb9eb?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1600185365926-3a2ce3cdb9eb?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 290,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Puma', Cushion: '100% NITROFOAM Max Stack', Upper: 'Engineered Knit Upper', Traction: 'Full-Coverage PUMAGRIP' }
    },
    {
      name: 'Puma Electrify Nitro 3 Lightweight Running Shoes',
      slug: 'puma-electrify-nitro-3-lightweight-running-shoes',
      description: 'Dynamic entry performance: NITROFOAM heel pod for soft impact landings paired with durable PROFOAMLITE, breathable mesh, and rolled collar for Achilles comfort.',
      price: 100,
      discount_price: 79,
      stock: 65,
      image_url: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80'],
      rating: 4.7,
      num_reviews: 510,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Puma', HeelPod: 'NITROFOAM Heel Pod', Forefoot: 'PROFOAMLITE', IdealFor: 'Entry Road Running & Gym Workouts' }
    },
    {
      name: 'Puma Fast-FWD Nitro Elite Track Road Racing Shoes',
      slug: 'puma-fast-fwd-nitro-elite-track-road-racing-shoes',
      description: 'Radical undulating geometry designed for 5K/10K speed: Aggressive forefoot undercut, full PWRPLATE carbon spoon, NITROFOAM ELITE, and locked-in monomesh fit.',
      price: 220,
      discount_price: 189,
      stock: 25,
      image_url: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 180,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Puma', Plate: 'Curved Carbon PWRPLATE', Midsole: 'NITROFOAM ELITE', Distance: '5K - 10K Racing & Intervals' }
    },
    {
      name: 'Puma evoSPEED Tokyo Nitro Sprint Track Spikes',
      slug: 'puma-evospeed-tokyo-nitro-sprint-track-spikes',
      description: 'Championship 60m-400m sprint spike: Full-length titanium 8-pin spike plate, full forefoot NITROFOAM ELITE rebound layer, and single-layer ULTRAWEAVE textile.',
      price: 180,
      discount_price: 159,
      stock: 20,
      image_url: 'https://images.unsplash.com/photo-1587563871167-1ee9c731aefb?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1587563871167-1ee9c731aefb?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 140,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Puma', SpikePlate: 'Full-Length Pebax & Carbon with 8 Fixed Pins', Event: '60m to 400m Sprint Events' }
    },
    {
      name: 'Puma evoSPEED Distance Nitro Track & Field Spikes',
      slug: 'puma-evospeed-distance-nitro-track-and-field-spikes',
      description: 'Middle-to-long distance spikes (800m to 10,000m): Internal carbon plate, forefoot NITROFOAM cushioning, 5-pin configuration, and water-repellent monomesh upper.',
      price: 150,
      discount_price: 129,
      stock: 22,
      image_url: 'https://images.unsplash.com/photo-1608231387042-66d1773070a5?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1608231387042-66d1773070a5?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 110,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Puma', Foam: 'NITROFOAM Energy Return', PinLayout: '5 Replaceable Spike Pins', Weight: '145g' }
    },
    {
      name: 'Puma Voyage Nitro 3 Gore-Tex Waterproof Trail Shoes',
      slug: 'puma-voyage-nitro-3-gore-tex-waterproof-trail-shoes',
      description: 'Uncompromising wet trail traction: Waterproof breathable GORE-TEX membrane, dual-layer NITROFOAM cushioning, and aggressive 4.5mm deep PUMAGRIP ATR lugs.',
      price: 160,
      discount_price: 139,
      stock: 35,
      image_url: 'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 310,
      is_featured: false,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Puma', Waterproof: 'GORE-TEX Waterproof Invisible Fit', Outsole: 'PUMAGRIP ATR (All-Terrain Rubber)', Midsole: 'NITROFOAM' }
    },
    {
      name: 'Puma Fast-Trac Nitro 2 All-Terrain Running Shoes',
      slug: 'puma-fast-trac-nitro-2-all-terrain-running-shoes',
      description: 'Hybrid road-to-trail capability: Full-length top layer NITROFOAM, rugged ripstop upper with drainage ports, and hybrid 3.5mm PUMAGRIP ATR lugs.',
      price: 120,
      discount_price: 99,
      stock: 45,
      image_url: 'https://images.unsplash.com/photo-1600185365926-3a2ce3cdb9eb?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1600185365926-3a2ce3cdb9eb?auto=format&fit=crop&w=800&q=80'],
      rating: 4.7,
      num_reviews: 240,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Puma', Terrain: 'Road-to-Trail Hybrid', Upper: 'Ripstop Mesh with PWRTAPE', Cushion: 'NITROFOAM + PROFOAMLITE' }
    },
    {
      name: 'Puma Run XX Nitro Women Specific Running Shoes',
      slug: 'puma-run-xx-nitro-women-specific-running-shoes',
      description: 'Specifically biomechanically shaped for women runners: Narrower heel fit, lower instep arch support, RUNGUIDE firm density rim, and high-rebound NITROFOAM.',
      price: 130,
      discount_price: 109,
      stock: 50,
      image_url: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 490,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Puma', Fit: 'Female Anatomical Last', Midsole: 'NITROFOAM Cushioning', Support: 'RUNGUIDE Alignment Collar' }
    },
    {
      name: 'Puma Deviate Nitro 2 WTR Winterized Running Shoes',
      slug: 'puma-deviate-nitro-2-wtr-winterized-running-shoes',
      description: 'Cold-weather carbon trainer: Water-repellent treated ripstop upper, 360-degree high-visibility reflective overlays, full PWRPLATE carbon spoon, and PUMAGRIP ice rubber.',
      price: 170,
      discount_price: 145,
      stock: 30,
      image_url: 'https://images.unsplash.com/photo-1587563871167-1ee9c731aefb?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1587563871167-1ee9c731aefb?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 210,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Puma', Weatherproofing: 'WTR Water-Repellent Shield', Visibility: '360° Reflective', Plate: 'Composite PWRPLATE' }
    },
    {
      name: 'Puma Velocity Nitro 2 Reflective Running Shoes',
      slug: 'puma-velocity-nitro-2-reflective-running-shoes',
      description: 'Night running essential: Full reflective upper elements, plush nitrogen NITROFOAM step-in, and responsive transitions over all paved distances.',
      price: 140,
      discount_price: 119,
      stock: 40,
      image_url: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 350,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Puma', Technology: 'NITROFOAM Midsole', Reflectivity: 'High-Visibility Prism Coating', Outsole: 'PUMAGRIP' }
    },
    {
      name: 'Puma Scend Pro Lightweight Everyday Running Shoes',
      slug: 'puma-scend-pro-lightweight-everyday-running-shoes',
      description: 'Clean modern performance: PROFOAMLITE lightweight high-rebound EVA midsole, locked-down midfoot cage, and durable full rubber outsole.',
      price: 85,
      discount_price: 69,
      stock: 70,
      image_url: 'https://images.unsplash.com/photo-1608231387042-66d1773070a5?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1608231387042-66d1773070a5?auto=format&fit=crop&w=800&q=80'],
      rating: 4.6,
      num_reviews: 420,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Puma', Midsole: 'PROFOAMLITE Cushioning', Upper: 'Breathable Engineered Mesh', Use: 'Everyday Jogging & Walking' }
    },
    {
      name: 'Puma Softride Enzo Evo Slip-On Running Shoes',
      slug: 'puma-softride-enzo-evo-slip-on-running-shoes',
      description: 'Extreme step-in comfort: Softride EVA compound providing extreme cushioning and all-day comfort, progressive clamshell construction, and TPU jewel piece in heel.',
      price: 80,
      discount_price: 64,
      stock: 85,
      image_url: 'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?auto=format&fit=crop&w=800&q=80'],
      rating: 4.7,
      num_reviews: 860,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Puma', Technology: 'Softride Foam Cushioning + SoftFoam+ Sockliner', Upper: 'Clamshell Slip-On Structure' }
    },
    {
      name: 'Puma Flyer Runner Mesh Training Shoes',
      slug: 'puma-flyer-runner-mesh-training-shoes',
      description: 'Streamlined athletic silhouette: SoftFoam+ optimal comfort dual-density insole, lightweight EVA midsole, and rubber heel/toe pods for traction.',
      price: 65,
      discount_price: 49,
      stock: 100,
      image_url: 'https://images.unsplash.com/photo-1600185365926-3a2ce3cdb9eb?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1600185365926-3a2ce3cdb9eb?auto=format&fit=crop&w=800&q=80'],
      rating: 4.6,
      num_reviews: 1200,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Puma', Insole: 'SoftFoam+ Memory Foam', Midsole: 'Compression-Molded EVA', Upper: 'Breathable Mesh' }
    },
    {
      name: 'Puma Aviator ProFoam Performance Running Shoes',
      slug: 'puma-aviator-profoam-performance-running-shoes',
      description: 'Responsive daily miles: ProFoam high-rebound lightweight EVA, engineered mesh upper with decoupled heel, and center parting line traction outsole.',
      price: 90,
      discount_price: 72,
      stock: 60,
      image_url: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80'],
      rating: 4.7,
      num_reviews: 310,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Puma', Cushioning: 'ProFoam Instant Energy Return', Weight: '260g', Upper: 'Engineered Technical Mesh' }
    },
    {
      name: 'Puma Seasons CoolCELL Trail Running Long Sleeve',
      slug: 'puma-seasons-coolcell-trail-running-long-sleeve',
      description: 'All-weather technical mountain trail top: CoolCELL body temperature regulation, thumbhole cuffs, zippered hip pocket for energy gels, and 360-degree reflectivity.',
      price: 75,
      discount_price: 62,
      stock: 55,
      image_url: 'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1556905055-8f358a7a47b2?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 140,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Puma', Technology: 'CoolCELL Breathability', Material: '88% Recycled Polyester / 12% Elastane', Fit: 'Athletic Slim Fit' }
    },

    // --- 2. PUMA FOOTBALL / SOCCER CLEATS & MATCH GEAR (20 Models) ---
    {
      name: 'Puma Future 7 Ultimate FG/AG Football Boots',
      slug: 'puma-future-7-ultimate-fg-ag-football-boots',
      description: 'Engineered for ultimate playmakers (worn by Neymar Jr & Jack Grealish): FUZIONFIT360 dual-mesh upper with PWRTAPE and PWRPRINT 3D texturing for sensational ball control.',
      price: 240,
      discount_price: 219,
      stock: 40,
      image_url: 'https://images.unsplash.com/photo-1511556532299-8f662fc26c06?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1511556532299-8f662fc26c06?auto=format&fit=crop&w=800&q=80'],
      rating: 5.0,
      num_reviews: 460,
      is_featured: true,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Puma', Upper: 'FUZIONFIT360 + PWRTAPE + PWRPRINT', Soleplate: 'Dynamic Motion System Outsole', Ground: 'Firm Ground / Artificial Grass (FG/AG)' }
    },
    {
      name: 'Puma Ultra 5 Ultimate Carbon FG Football Cleats',
      slug: 'puma-ultra-5-ultimate-carbon-fg-football-cleats',
      description: 'The fastest boot on the pitch: SPEEDSYSTEM carbon-composite outsole, FastTrax stud design for instant acceleration, and featherweight ULTRAWEAVE woven upper.',
      price: 250,
      discount_price: 229,
      stock: 35,
      image_url: 'https://images.unsplash.com/photo-1511556532299-8f662fc26c06?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1511556532299-8f662fc26c06?auto=format&fit=crop&w=800&q=80'],
      rating: 5.0,
      num_reviews: 380,
      is_featured: true,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Puma', Upper: 'ULTRAWEAVE High-Performance Woven Fabric', Outsole: 'SPEEDSYSTEM Carbon Plate', Weight: '175g' }
    },
    {
      name: 'Puma King Ultimate FG/AG Football Boots',
      slug: 'puma-king-ultimate-fg-ag-football-boots',
      description: 'The legendary icon upgraded: 100% animal-free K-BETTER upper material outperforming traditional leather in touch, comfort, and durability with lightweight TPU outsole.',
      price: 200,
      discount_price: 179,
      stock: 45,
      image_url: 'https://images.unsplash.com/photo-1511556532299-8f662fc26c06?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1511556532299-8f662fc26c06?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 520,
      is_featured: true,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Puma', Upper: 'K-BETTER Non-Animal Synthetic Leather', Insole: 'NanoGrip Removable Sockliner', Ground: 'FG/AG' }
    },
    {
      name: 'Puma Future 7 Match MG Multi-Ground Football Boots',
      slug: 'puma-future-7-match-mg-multi-ground-football-boots',
      description: 'Adaptive FUZIONFIT mesh upper, midfoot support band, embossed ball strike zones, and low-profile multi-stud TPU outsole for artificial grass and hard pitches.',
      price: 90,
      discount_price: 75,
      stock: 60,
      image_url: 'https://images.unsplash.com/photo-1511556532299-8f662fc26c06?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1511556532299-8f662fc26c06?auto=format&fit=crop&w=800&q=80'],
      rating: 4.7,
      num_reviews: 310,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Puma', Upper: 'FUZIONFIT Engineered Mesh', Studs: 'Low-Profile Multi-Ground (MG)', Field: 'Artificial Turf & Hard Dirt' }
    },
    {
      name: 'Puma Ultra 5 Match TT Turf Football Shoes',
      slug: 'puma-ultra-5-match-tt-turf-football-shoes',
      description: 'High-speed 5-a-side turf shoe: Lightweight mesh upper reinforced with GripControl skin, EVA midsole cushioning, and multi-studded rubber turf outsole.',
      price: 85,
      discount_price: 69,
      stock: 65,
      image_url: 'https://images.unsplash.com/photo-1511556532299-8f662fc26c06?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1511556532299-8f662fc26c06?auto=format&fit=crop&w=800&q=80'],
      rating: 4.7,
      num_reviews: 290,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Puma', Upper: 'Lightweight Mesh + GripControl Skin', Outsole: 'Multi-Studded Low-Profile TT Rubber', Ground: '2G Turf & Hard Surface' }
    },
    {
      name: 'Puma King Pro IT Indoor Soccer Futsal Shoes',
      slug: 'puma-king-pro-it-indoor-soccer-futsal-shoes',
      description: 'Indoor court precision: Soft K-BETTER upper, low-profile EVA cushioning midsole, reinforced suede toe cap, and non-marking rubber indoor gum outsole.',
      price: 110,
      discount_price: 89,
      stock: 40,
      image_url: 'https://images.unsplash.com/photo-1511556532299-8f662fc26c06?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1511556532299-8f662fc26c06?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 220,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Puma', Upper: 'K-BETTER Synthetic Leather', Sole: 'Non-Marking Indoor IT Rubber', Midsole: 'EVA Foam' }
    },
    {
      name: 'Puma Future 7 Play FG Firm Ground Football Cleats',
      slug: 'puma-future-7-play-fg-firm-ground-football-cleats',
      description: 'Durable and supportive entry boot: Synthetic upper with texture details, regular tongue construction, and lightweight TPU outsole with conical studs.',
      price: 60,
      discount_price: 49,
      stock: 80,
      image_url: 'https://images.unsplash.com/photo-1511556532299-8f662fc26c06?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1511556532299-8f662fc26c06?auto=format&fit=crop&w=800&q=80'],
      rating: 4.6,
      num_reviews: 430,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Puma', Upper: 'Lightweight Synthetic', Outsole: 'Dynamic TPU Firm Ground Cleats' }
    },
    {
      name: 'Puma Attacanto FG Firm Ground Cleats',
      slug: 'puma-attacanto-fg-firm-ground-cleats',
      description: 'Straightforward performance: Low-maintenance synthetic upper with striking graphic print and lightweight TPU outsole for natural firm pitches.',
      price: 50,
      discount_price: 39,
      stock: 90,
      image_url: 'https://images.unsplash.com/photo-1511556532299-8f662fc26c06?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1511556532299-8f662fc26c06?auto=format&fit=crop&w=800&q=80'],
      rating: 4.5,
      num_reviews: 310,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Puma', Upper: 'Soft Synthetic Upper', Outsole: 'Conical Studded FG Plate' }
    },
    {
      name: 'Puma Ultra Match+ Laceless FG/AG Boots',
      slug: 'puma-ultra-match-plus-laceless-fg-ag-boots',
      description: 'Clean strike surface: Laceless high-cut knit collar, lightweight mesh upper with GripControl skin coating, and TPU SPEEDPLATE outsole.',
      price: 110,
      discount_price: 92,
      stock: 50,
      image_url: 'https://images.unsplash.com/photo-1511556532299-8f662fc26c06?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1511556532299-8f662fc26c06?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 260,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Puma', Collar: 'Laceless Knit High-Cut Collar', Outsole: 'TPU SPEEDPLATE FG/AG' }
    },
    {
      name: 'Puma Ultra Play IT Futsal Court Shoes',
      slug: 'puma-ultra-play-it-futsal-court-shoes',
      description: 'Quick transitions on hardwood and indoor courts: Lightweight durable synthetic upper and non-marking low-profile indoor rubber outsole.',
      price: 55,
      discount_price: 44,
      stock: 70,
      image_url: 'https://images.unsplash.com/photo-1511556532299-8f662fc26c06?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1511556532299-8f662fc26c06?auto=format&fit=crop&w=800&q=80'],
      rating: 4.6,
      num_reviews: 190,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Puma', Outsole: 'Non-Marking Indoor Rubber', Upper: 'Synthetic PU' }
    },
    {
      name: 'Puma King Match FG/AG Football Boots',
      slug: 'puma-king-match-fg-ag-football-boots',
      description: 'Classic heritage styling with modern micro-textured microfiber upper, padded ankle collar, and lightweight conical stud configuration.',
      price: 80,
      discount_price: 65,
      stock: 55,
      image_url: 'https://images.unsplash.com/photo-1511556532299-8f662fc26c06?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1511556532299-8f662fc26c06?auto=format&fit=crop&w=800&q=80'],
      rating: 4.7,
      num_reviews: 210,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Puma', Upper: 'Soft Synthetic Leather', Studs: 'Molded Conical FG/AG' }
    },
    {
      name: 'Puma Orbita 1 Serie A Official Match Ball',
      slug: 'puma-orbita-1-serie-a-official-match-ball',
      description: 'Official match ball of the Italian Serie A: 12-panel configuration with equal form panels, 1.2mm 3D textured PU surface with POE foam under-layer, and FIFA Quality Pro certification.',
      price: 140,
      discount_price: 119,
      stock: 45,
      image_url: 'https://images.unsplash.com/photo-1614632537423-1e6c2e7e0aab?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1614632537423-1e6c2e7e0aab?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 320,
      is_featured: true,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Puma', Standard: 'FIFA Quality Pro', Construction: 'High-Frequency Molded 12 Panels', Bladder: 'Rubber Bladder + PAL Valve' }
    },
    {
      name: 'Puma Orbita LaLiga Official FIFA Quality Pro Match Ball',
      slug: 'puma-orbita-laliga-official-fifa-quality-pro-match-ball',
      description: 'Official match ball of Spanish LaLiga: Deep aerodynamic seams, textured polyurethane outer skin, and maximum energy return POE foam backing.',
      price: 140,
      discount_price: 119,
      stock: 40,
      image_url: 'https://images.unsplash.com/photo-1614632537423-1e6c2e7e0aab?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1614632537423-1e6c2e7e0aab?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 280,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Puma', Standard: 'FIFA Quality Pro Official Match Ball', League: 'LaLiga EA Sports' }
    },
    {
      name: 'Puma Ultra Grip 1 Hybrid Pro Goalkeeper Gloves',
      slug: 'puma-ultra-grip-1-hybrid-pro-goalkeeper-gloves',
      description: 'Elite professional match gloves: 4mm Superior Grip latex palm with internal grip dots, hybrid roll-negative cut, and lightweight woven backhand with silicone punch zone.',
      price: 130,
      discount_price: 109,
      stock: 30,
      image_url: 'https://images.unsplash.com/photo-1511556532299-8f662fc26c06?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1511556532299-8f662fc26c06?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 190,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Puma', Latex: '4mm Superior Grip Latex Palm', Cut: 'Hybrid Roll / Negative Cut', Wrist: 'Full-Length Latex Strap' }
    },
    {
      name: 'Puma Future Ultimate NC Hybrid Goalkeeper Gloves',
      slug: 'puma-future-ultimate-nc-hybrid-goalkeeper-gloves',
      description: 'Second-skin fit goalkeeper glove: 4mm ELITE+ dual-grip latex with extra adhesive particles, negative cut for snug finger fit, and 3D knitted backhand with targeted punching silicone.',
      price: 140,
      discount_price: 119,
      stock: 25,
      image_url: 'https://images.unsplash.com/photo-1511556532299-8f662fc26c06?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1511556532299-8f662fc26c06?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 160,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Puma', Palm: '4mm ELITE+ Dual-Grip Latex', Cut: 'Negative Cut (NC)', Backhand: '3D Knitted Fabric' }
    },
    {
      name: 'Puma Ultra Flex Shin Guards',
      slug: 'puma-ultra-flex-shin-guards',
      description: 'Ultra-flexible ergonomic protection: Perforated EVA backing for ventilation and shock absorption, TPU soft-shell construction, and compression sleeve included.',
      price: 30,
      discount_price: 24,
      stock: 80,
      image_url: 'https://images.unsplash.com/photo-1511556532299-8f662fc26c06?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1511556532299-8f662fc26c06?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 420,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Puma', Shell: 'Flexible TPU Composite', Backing: 'Perforated EVA Foam', Includes: 'Compression Compression Sleeves' }
    },
    {
      name: 'Puma King Pro Shin Guards with Ankle Protection',
      slug: 'puma-king-pro-shin-guards-with-ankle-protection',
      description: 'Comprehensive lower leg shielding: Hard polypropylene shell, cushioned EVA foam backing, attached padded ankle sock, and adjustable calf strap.',
      price: 35,
      discount_price: 28,
      stock: 75,
      image_url: 'https://images.unsplash.com/photo-1511556532299-8f662fc26c06?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1511556532299-8f662fc26c06?auto=format&fit=crop&w=800&q=80'],
      rating: 4.7,
      num_reviews: 310,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Puma', Shell: 'High-Impact PP Shell', Ankle: 'Integrated Padded Ankle Guard' }
    },
    {
      name: 'Puma TeamFINAL Football Backpack with Ball Compartment',
      slug: 'puma-teamfinal-football-backpack-with-ball-compartment',
      description: 'Dedicated team sport carrier: Bottom expandable zippered ball/shoe compartment, water-repellent heavy-duty polyester, padded shoulder straps, and laptop sleeve.',
      price: 55,
      discount_price: 44,
      stock: 60,
      image_url: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 350,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Puma', Volume: '32 Liters', Compartments: 'Ball Net / Boot Bottom Compartment, Main Pocket, Dual Bottle Sleeves' }
    },
    {
      name: 'Puma IndividualFINAL Match Day Football Jersey',
      slug: 'puma-individualfinal-match-day-football-jersey',
      description: 'Pro-level match jersey: dryCELL moisture-wicking technology, lightweight jacquard breathable mesh fabric, ergonomic seam placement, and heat-transfer Cat logo.',
      price: 45,
      discount_price: 35,
      stock: 90,
      image_url: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=800&q=80'],
      rating: 4.7,
      num_reviews: 280,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Puma', Technology: 'dryCELL Sweat-Wicking', Fabric: '100% Recycled Polyester Mesh', Fit: 'Slim Performance Fit' }
    },
    {
      name: 'Puma Pro Training Football Bibs Set 10 Pack',
      slug: 'puma-pro-training-football-bibs-set-10-pack',
      description: 'High-visibility training vests for club scrimmages: Lightweight breathable open-hole mesh, reinforced stitching around neck and armholes, set of 10 vests.',
      price: 60,
      discount_price: 48,
      stock: 50,
      image_url: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 140,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Puma', Quantity: '10 Training Bibs', Material: '100% Polyester Open Mesh', Colors: 'Fluorescent Yellow / Orange' }
    },

    // --- 3. PUMA CLASSICS, TERRACE & HERITAGE SNEAKERS (20 Models) ---
    {
      name: 'Puma Palermo Leather Terrace Shoes',
      slug: 'puma-palermo-leather-terrace-shoes',
      description: 'The 1980s football terrace icon returned: Suede and smooth leather upper, signature T-toe construction, classic foil-printed gold Palermo tag, and retro gum rubber outsole.',
      price: 90,
      discount_price: 79,
      stock: 80,
      image_url: 'https://images.unsplash.com/photo-1608231387042-66d1773070a5?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1608231387042-66d1773070a5?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 890,
      is_featured: true,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Puma', Upper: 'Premium Suede & Leather', Outsole: 'Terrace Gum Rubber', Heritage: '1980s Palermo Archive Release' }
    },
    {
      name: 'Puma Suede Classic XXI Sneakers',
      slug: 'puma-suede-classic-xxi-sneakers',
      description: 'The definitive streetwear staple since 1968: Full premium velvety suede upper, tonal Formstrip, comfortable padded collar, and durable rubber cupsole.',
      price: 75,
      discount_price: 65,
      stock: 120,
      image_url: 'https://images.unsplash.com/photo-1608231387042-66d1773070a5?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1608231387042-66d1773070a5?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 2300,
      is_featured: true,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Puma', Upper: '100% Suede Leather', Heritage: 'Original 1968 Silhouette', Midsole: 'Rubber Cupsole' }
    },
    {
      name: 'Puma Suede Triplex Heritage Sneakers',
      slug: 'puma-suede-triplex-heritage-sneakers',
      description: 'Triple-layered Formstrip modern evolution: Premium suede upper with layered multicolor Formstrip branding, gold foil Puma branding, and heritage gum sole.',
      price: 85,
      discount_price: 69,
      stock: 60,
      image_url: 'https://images.unsplash.com/photo-1608231387042-66d1773070a5?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1608231387042-66d1773070a5?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 310,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Puma', Upper: 'Suede with Triplex Layered Formstrip', Outsole: 'Rubber Cupsole' }
    },
    {
      name: 'Puma Clyde OG Walt Frazier Basketball Shoes',
      slug: 'puma-clyde-og-walt-frazier-basketball-shoes',
      description: 'Named after NBA legend Walt "Clyde" Frazier: Supple leather upper, gold foil cursive Clyde signature, padded leather tongue, and herringbone traction sole.',
      price: 110,
      discount_price: 95,
      stock: 45,
      image_url: 'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 490,
      is_featured: true,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Puma', Heritage: '1973 Walt Clyde Frazier OG Spec', Upper: 'Full-Grain Leather', Details: 'Gold Foil Clyde Branding' }
    },
    {
      name: 'Puma Clyde All-Pro Performance Edition',
      slug: 'puma-clyde-all-pro-performance-edition',
      description: 'Modern performance upgrade to the classic: Matryx engineered woven upper with carbon threads, ProFoam+ lightweight cushioning, and high-traction rubber.',
      price: 130,
      discount_price: 109,
      stock: 35,
      image_url: 'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 260,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Puma', Upper: 'Matryx Carbon-Woven Knit', Midsole: 'ProFoam+ High-Rebound EVA' }
    },
    {
      name: 'Puma Super Ligero Terrace Gum Sole Shoes',
      slug: 'puma-super-ligero-terrace-gum-sole-shoes',
      description: 'Slim terrace casual runner: Nylon and soft suede paneling, contrast leather Formstrip, slim profile EVA midsole, and lugged gum traction outsole.',
      price: 80,
      discount_price: 65,
      stock: 55,
      image_url: 'https://images.unsplash.com/photo-1608231387042-66d1773070a5?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1608231387042-66d1773070a5?auto=format&fit=crop&w=800&q=80'],
      rating: 4.7,
      num_reviews: 190,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Puma', Upper: 'Nylon & Suede Overlays', Style: 'Vintage Terrace Runner' }
    },
    {
      name: 'Puma Roma Classic Leather Retro Shoes',
      slug: 'puma-roma-classic-leather-retro-shoes',
      description: '1968 Olympic champion shoe: Smooth synthetic leather upper, thick padded tongue with orthopedic arch supports, and serrated rubber toe bumper.',
      price: 70,
      discount_price: 58,
      stock: 95,
      image_url: 'https://images.unsplash.com/photo-1600185365926-3a2ce3cdb9eb?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1600185365926-3a2ce3cdb9eb?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 1420,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Puma', Upper: 'Synthetic Leather', Toe: 'Reinforced T-Toe Bumper', Support: 'Arch Support EVA Wedge' }
    },
    {
      name: 'Puma Easy Rider Vintage Runner Shoes',
      slug: 'puma-easy-rider-vintage-runner-shoes',
      description: 'Pioneering 1970s jogging silhouette: Suede and nylon upper, slim vintage tongue, dual-layer wedge midsole, and distinctive cone-stud rubber outsole.',
      price: 85,
      discount_price: 70,
      stock: 60,
      image_url: 'https://images.unsplash.com/photo-1608231387042-66d1773070a5?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1608231387042-66d1773070a5?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 380,
      is_featured: false,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Puma', Heritage: '1977 Easy Rider OG', Outsole: 'Cone-Studded Lugged Outsole', Upper: 'Suede & Nylon' }
    },
    {
      name: 'Puma Delphin Archive Suede Sneakers',
      slug: 'puma-delphin-archive-suede-sneakers',
      description: 'Authentic 1970s indoor trainer: Supple oiled suede upper, extended eyelet stay extending to the toe cap, and textured dark gum rubber cupsole.',
      price: 95,
      discount_price: 79,
      stock: 50,
      image_url: 'https://images.unsplash.com/photo-1608231387042-66d1773070a5?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1608231387042-66d1773070a5?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 210,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Puma', Upper: 'Oiled Suede', Sole: 'Textured Dark Gum Sole', Style: '70s Indoor Archive' }
    },
    {
      name: 'Puma Arizona Leather Classic Trainers',
      slug: 'puma-arizona-leather-classic-trainers',
      description: 'Sleek 1970s multi-sport trainer: Premium white leather with contrast navy Formstrip, perforated vamp, low-profile EVA wedge, and razor-tooth rubber tread.',
      price: 85,
      discount_price: 69,
      stock: 40,
      image_url: 'https://images.unsplash.com/photo-1600185365926-3a2ce3cdb9eb?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1600185365926-3a2ce3cdb9eb?auto=format&fit=crop&w=800&q=80'],
      rating: 4.7,
      num_reviews: 170,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Puma', Upper: 'Leather & Suede', Tread: 'Razor-Tooth Grip' }
    },
    {
      name: 'Puma Club II Era Suede Casual Shoes',
      slug: 'puma-club-ii-era-suede-casual-shoes',
      description: 'Casual football-inspired everyday trainer: Rich suede upper, clean stitched Formstrip, SoftFoam+ comfort insert, and durable vulcanized-look cupsole.',
      price: 70,
      discount_price: 55,
      stock: 75,
      image_url: 'https://images.unsplash.com/photo-1608231387042-66d1773070a5?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1608231387042-66d1773070a5?auto=format&fit=crop&w=800&q=80'],
      rating: 4.7,
      num_reviews: 320,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Puma', Insole: 'SoftFoam+ Step-In Comfort', Upper: 'Soft Suede Leather' }
    },
    {
      name: 'Puma Caven 2.0 Retro Court Sneakers',
      slug: 'puma-caven-2-0-retro-court-sneakers',
      description: 'Nostalgic 1980s campus basketball look: Synthetic leather upper with micro-perforations, stacked midsole look, and SoftFoam+ cushioning for all-day wear.',
      price: 65,
      discount_price: 52,
      stock: 90,
      image_url: 'https://images.unsplash.com/photo-1600185365926-3a2ce3cdb9eb?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1600185365926-3a2ce3cdb9eb?auto=format&fit=crop&w=800&q=80'],
      rating: 4.7,
      num_reviews: 640,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Puma', Style: '80s Basketball Court', Insole: 'SoftFoam+' }
    },
    {
      name: 'Puma Smash v2 Leather Low-Top Shoes',
      slug: 'puma-smash-v2-leather-low-top-shoes',
      description: 'Clean tennis court design: Soft leather upper with stitched Formstrip, padded collar, and durable non-marking rubber herringbone cupsole.',
      price: 60,
      discount_price: 48,
      stock: 110,
      image_url: 'https://images.unsplash.com/photo-1600185365926-3a2ce3cdb9eb?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1600185365926-3a2ce3cdb9eb?auto=format&fit=crop&w=800&q=80'],
      rating: 4.7,
      num_reviews: 1850,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Puma', Upper: 'Smooth Leather', Outsole: 'Herringbone Rubber' }
    },
    {
      name: 'Puma Rebound LayUp High-Top Retro Sneakers',
      slug: 'puma-rebound-layup-high-top-retro-sneakers',
      description: 'High-cut retro court silhouette: Padded collar and tongue for ankle support, synthetic leather upper, perforated vamp, and durable rubber outsole.',
      price: 75,
      discount_price: 59,
      stock: 65,
      image_url: 'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 790,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Puma', Cut: 'High-Top Ankle Support', Insole: 'SoftFoam+ Dual-Density' }
    },
    {
      name: 'Puma Carina 2.0 Women Chunky Platform Sneakers',
      slug: 'puma-carina-2-0-women-chunky-platform-sneakers',
      description: 'California 80s beach vibe with a platform lift: Leather upper with perforated vamp, elevated platform rubber sole with vertical textured lines, and SoftFoam+ sockliner.',
      price: 70,
      discount_price: 58,
      stock: 85,
      image_url: 'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 1120,
      is_featured: false,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Puma', Sole: 'Elevated Platform Midsole', Insole: 'SoftFoam+ Sockliner', Upper: 'Leather & Synthetic' }
    },
    {
      name: 'Puma Cali Court Leather Platform Sneakers',
      slug: 'puma-cali-court-leather-platform-sneakers',
      description: 'Effortless street style: Leather upper with suede overlays, chunky exaggerated rubber tooling, gold foil Puma branding, and comfortable padded collar.',
      price: 90,
      discount_price: 75,
      stock: 50,
      image_url: 'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 440,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Puma', Upper: 'Full Grain Leather & Suede', Midsole: 'Thick EVA Platform' }
    },
    {
      name: 'Puma Mayze Stack Leather Women Platform Shoes',
      slug: 'puma-mayze-stack-leather-women-platform-shoes',
      description: 'Dramatic layered sole design: Super-stacked chunky rubber platform outsole, clean leather upper, suede Formstrip, and woven Puma logo label on tongue.',
      price: 100,
      discount_price: 85,
      stock: 45,
      image_url: 'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 580,
      is_featured: false,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Puma', PlatformHeight: '45 mm Chunky Stack Sole', Upper: 'Leather Upper with Suede Formstrip' }
    },
    {
      name: 'Puma Slipstream Leather Retro Basketball Shoes',
      slug: 'puma-slipstream-leather-retro-basketball-shoes',
      description: 'Reinventing the 1987 hardwood monster: Multi-paneled leather and suede upper, deep sculpted midsole walls, and vintage basketball traction rubber outsole.',
      price: 90,
      discount_price: 76,
      stock: 60,
      image_url: 'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 490,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Puma', Heritage: '1987 Slipstream Basketball Archive', Upper: 'Leather & Nubuck' }
    },
    {
      name: 'Puma Army Trainer OG German Indoor Sneakers',
      slug: 'puma-army-trainer-og-german-indoor-sneakers',
      description: 'Authentic 1970s German Armed Forces indoor trainer reproduction: Smooth leather upper, suede T-toe reinforcement, low-profile gum sole, and gold foil branding.',
      price: 100,
      discount_price: 85,
      stock: 50,
      image_url: 'https://images.unsplash.com/photo-1608231387042-66d1773070a5?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1608231387042-66d1773070a5?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 370,
      is_featured: false,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Puma', Style: 'German Indoor Military Trainer OG Spec', Material: 'Premium White Leather & Grey Suede' }
    },
    {
      name: 'Puma GV Special Vintage Tennis Leather Shoes',
      slug: 'puma-gv-special-vintage-tennis-leather-shoes',
      description: 'Grand Slam tennis legend Guillermo Vilas signature shoe: Ultra-thick PU midsole for superior shock absorption, perforated leather upper, and classic court grip.',
      price: 85,
      discount_price: 69,
      stock: 55,
      image_url: 'https://images.unsplash.com/photo-1600185365926-3a2ce3cdb9eb?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1600185365926-3a2ce3cdb9eb?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 420,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Puma', Signature: 'Guillermo Vilas Grand Slam Spec', Midsole: 'Molded Thick Shock-Absorbing PU' }
    },

    // --- 4. PUMA MOTORSPORT COLLECTIONS (Scuderia Ferrari, BMW M Motorsport, Mercedes-AMG & Porsche) (20 Models) ---
    {
      name: 'Puma Scuderia Ferrari Speedcat OG Driving Shoes',
      slug: 'puma-scuderia-ferrari-speedcat-og-driving-shoes',
      description: 'The definitive Formula 1 paddock racing shoe: Ultra-slim silhouette, premium suede upper with embroidered Puma Cat at toe, rounded driver heel, and Scuderia Ferrari shield.',
      price: 110,
      discount_price: 99,
      stock: 50,
      image_url: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80'],
      rating: 5.0,
      num_reviews: 950,
      is_featured: true,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Puma Motorsport', Team: 'Scuderia Ferrari F1 Official', Upper: 'Premium Suede Leather', Heel: 'Rounded Driver Heel Cup' }
    },
    {
      name: 'Puma Scuderia Ferrari Drift Cat Decima Shoes',
      slug: 'puma-scuderia-ferrari-drift-cat-decima-shoes',
      description: 'Sleek aerodynamic motorsport profile: Synthetic leather upper with laser-cut perforation details, Scuderia Ferrari shield on heel, and low-profile tire-tread rubber sole.',
      price: 95,
      discount_price: 79,
      stock: 60,
      image_url: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 620,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Puma Motorsport', Team: 'Scuderia Ferrari', Outsole: 'Tire-Tread Low Profile Rubber' }
    },
    {
      name: 'Puma Scuderia Ferrari Race MT7 Track Jacket',
      slug: 'puma-scuderia-ferrari-race-mt7-track-jacket',
      description: 'Motorsport heritage meets iconic T7 track stripes: Rosso Corsa racing red body, Scuderia Ferrari badge on chest, dryCELL moisture management, and stand-up collar.',
      price: 110,
      discount_price: 89,
      stock: 40,
      image_url: 'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1556905055-8f358a7a47b2?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 430,
      is_featured: true,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Puma Motorsport', Team: 'Scuderia Ferrari Official Merchandise', Technology: 'dryCELL Moisture Wicking' }
    },
    {
      name: 'Puma Scuderia Ferrari Team Polo Shirt',
      slug: 'puma-scuderia-ferrari-team-polo-shirt',
      description: 'Official Formula 1 Grand Prix weekend polo: Classic 3-button placket, authentic sponsor logos, Scuderia Ferrari shield on chest, and breathable cotton-piqué construction.',
      price: 75,
      discount_price: 62,
      stock: 70,
      image_url: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 380,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Puma Motorsport', Material: '100% Breathable Cotton Piqué', Details: 'Authentic Sponsor Heat Transfers' }
    },
    {
      name: 'Puma Scuderia Ferrari T7 Heritage Track Pants',
      slug: 'puma-scuderia-ferrari-t7-heritage-track-pants',
      description: 'Slim tailored motorsport joggers: Contrast red side panel inserts, elastic waistband with internal drawcord, zippered hand pockets, and metallic Ferrari badge.',
      price: 90,
      discount_price: 74,
      stock: 50,
      image_url: 'https://images.unsplash.com/photo-1552902865-b72c031ac5ea?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1552902865-b72c031ac5ea?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 290,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Puma Motorsport', Fit: 'Slim Tapered Cut', Pockets: 'Dual Concealed Zipper Pockets' }
    },
    {
      name: 'Puma Scuderia Ferrari Shield Lightweight Windbreaker',
      slug: 'puma-scuderia-ferrari-shield-lightweight-windbreaker',
      description: 'Trackside weather protection: WindCELL wind-blocking fabric, water-repellent finish, packable hood, and bold Scuderia Ferrari yellow shield on left chest.',
      price: 120,
      discount_price: 99,
      stock: 35,
      image_url: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 210,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Puma Motorsport', Technology: 'windCELL Weatherproof Tech', Details: 'Packable Hood with Drawstrings' }
    },
    {
      name: 'Puma BMW M Motorsport Neo Cat Driving Shoes',
      slug: 'puma-bmw-m-motorsport-neo-cat-driving-shoes',
      description: 'Inspired by early 1980s Bellof racing boots: Clean synthetic leather upper, BMW M Motorsport tricolor woven stripe at heel, and rounded driver rubber heel.',
      price: 95,
      discount_price: 79,
      stock: 55,
      image_url: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 510,
      is_featured: true,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Puma Motorsport', Partner: 'BMW M Motorsport Official', Colors: 'White / Black with M Tri-Color Detailing' }
    },
    {
      name: 'Puma BMW M Motorsport LGND Renegade Sneakers',
      slug: 'puma-bmw-m-motorsport-lgnd-renegade-sneakers',
      description: 'Bulky futuristic street sneaker: Multi-layered mesh and synthetic overlays, sculpted EVA midsole with M Power branding, and rugged rubber tread.',
      price: 115,
      discount_price: 95,
      stock: 45,
      image_url: 'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 320,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Puma Motorsport', Silhouette: 'Chunky Modern Streetwear', Cushioning: 'Sculpted Molded EVA' }
    },
    {
      name: 'Puma BMW M Motorsport SDS Track Jacket',
      slug: 'puma-bmw-m-motorsport-sds-track-jacket',
      description: 'Speed Drivers Series (SDS) design: Color-blocked chevron chest inserts in BMW M racing blue and red, metallic BMW propeller badge, and ribbed collar.',
      price: 110,
      discount_price: 89,
      stock: 40,
      image_url: 'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1556905055-8f358a7a47b2?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 340,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Puma Motorsport', Series: 'Speed Drivers Series (SDS)', Badge: 'M Motorsport Chrome Badge' }
    },
    {
      name: 'Puma BMW M Motorsport Graphic Hoodie',
      slug: 'puma-bmw-m-motorsport-graphic-hoodie',
      description: 'Heavyweight fleece comfort: French terry 330gsm cotton, oversized ///M Motorsport silicone chest graphic, kangaroo pocket, and drawcord hood.',
      price: 85,
      discount_price: 69,
      stock: 65,
      image_url: 'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1556905055-8f358a7a47b2?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 490,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Puma Motorsport', Material: '68% Cotton / 32% Polyester French Terry', Weight: '330 gsm' }
    },
    {
      name: 'Puma BMW M Motorsport Statement Sweatpants',
      slug: 'puma-bmw-m-motorsport-statement-sweatpants',
      description: 'Asymmetric technical track pants: Ergonomic articulated knee cutouts, BMW M tricolor zip pulls, and reflective Puma Cat logo.',
      price: 85,
      discount_price: 69,
      stock: 50,
      image_url: 'https://images.unsplash.com/photo-1552902865-b72c031ac5ea?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1552902865-b72c031ac5ea?auto=format&fit=crop&w=800&q=80'],
      rating: 4.7,
      num_reviews: 260,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Puma Motorsport', Fit: 'Regular Tapered', Details: 'Articulated Knee Seams' }
    },
    {
      name: 'Puma Mercedes-AMG Petronas F1 Tiburion Shoes',
      slug: 'puma-mercedes-amg-petronas-f1-tiburion-shoes',
      description: 'Inspired by Mercedes F1 aerodynamic front wings: Breathable mesh upper with synthetic overlays, EVA midsole, Petronas green accents, and Mercedes star at heel.',
      price: 100,
      discount_price: 84,
      stock: 45,
      image_url: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 370,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Puma Motorsport', Team: 'Mercedes-AMG Petronas Formula One', Accents: 'Petronas Spectra Green' }
    },
    {
      name: 'Puma Mercedes-AMG Petronas F1 Team Rain Jacket',
      slug: 'puma-mercedes-amg-petronas-f1-team-rain-jacket',
      description: 'Official trackside wet weather jacket: 100% waterproof seam-sealed nylon shell, adjustable bungee hood, storm flaps over zips, and official Mercedes-AMG sponsor livery.',
      price: 150,
      discount_price: 129,
      stock: 30,
      image_url: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 180,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Puma Motorsport', Waterproofing: 'Fully Taped Seams (10,000mm)', Team: 'Mercedes-AMG Petronas F1 Team' }
    },
    {
      name: 'Puma Mercedes-AMG Petronas F1 Garage Crew Polo',
      slug: 'puma-mercedes-amg-petronas-f1-garage-crew-polo',
      description: 'Pit crew specification: Lightweight dryCELL moisture management fabric, ribbed collar with contrast Petronas green tipping, and heat-pressed partner graphics.',
      price: 75,
      discount_price: 62,
      stock: 60,
      image_url: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 290,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Puma Motorsport', Fabric: 'dryCELL Poly-Elastane Piqué', Team: 'Mercedes-AMG F1 Crew' }
    },
    {
      name: 'Puma Mercedes-AMG Petronas F1 Speedcat Pro Racing Shoes',
      slug: 'puma-mercedes-amg-petronas-f1-speedcat-pro-racing-shoes',
      description: 'FIA-inspired racing shoe: Ultra-lightweight leather, fire-retardant lining look, carbon fiber heel counter support, and low-profile pedal grip outsole.',
      price: 130,
      discount_price: 109,
      stock: 25,
      image_url: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 140,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Puma Motorsport', Heel: 'Real Carbon Fiber Counter', Sole: 'Ultra-Thin Oil-Resistant Pedal Rubber' }
    },
    {
      name: 'Puma Porsche Legacy RS-X Retro Sneakers',
      slug: 'puma-porsche-legacy-rs-x-retro-sneakers',
      description: 'Honoring the legendary Porsche 911 Turbo: Chunky RS (Running System) cushioning silhouette, turbo yellow accents, debossed Porsche Turbo tongue logo, and mesh upper.',
      price: 125,
      discount_price: 105,
      stock: 40,
      image_url: 'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 410,
      is_featured: true,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Puma Motorsport', Partner: 'Porsche Legacy Turbo 911', Cushioning: 'Puma RS (Running System) Technology' }
    },
    {
      name: 'Puma Porsche Legacy Turbo Statement Jacket',
      slug: 'puma-porsche-legacy-turbo-statement-jacket',
      description: 'Vintage motorsports windbreaker: Water-resistant ripstop nylon, bold retro Porsche 911 Turbo script across back, stand collar, and contrast zip pulls.',
      price: 135,
      discount_price: 110,
      stock: 35,
      image_url: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 230,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Puma Motorsport', Collection: 'Porsche Legacy Statement', Graphic: 'Large Vintage Porsche Turbo Graphic' }
    },
    {
      name: 'Puma Porsche Legacy 911 Turbo Hoodie',
      slug: 'puma-porsche-legacy-911-turbo-hoodie',
      description: 'Cozy brushed fleece hoodie: Minimalist Porsche 911 Turbo chest embroidery, lemon yellow drawstrings, ribbed cuffs, and kangaroo pocket.',
      price: 90,
      discount_price: 74,
      stock: 55,
      image_url: 'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1556905055-8f358a7a47b2?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 310,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Puma Motorsport', Fleece: 'Brushed Cotton-Rich French Terry', Fit: 'Relaxed Street Fit' }
    },
    {
      name: 'Puma Red Bull Racing A3ROcat Sneaker',
      slug: 'puma-red-bull-racing-a3rocat-sneaker',
      description: 'Aerodynamic street shoe in Oracle Red Bull Racing navy & red: Lightweight mesh upper with synthetic reinforcements, low-profile midsole, and team crest.',
      price: 95,
      discount_price: 79,
      stock: 45,
      image_url: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 380,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Puma Motorsport', Team: 'Oracle Red Bull Racing F1 Team', Sole: 'Low-Profile High Grip Rubber' }
    },
    {
      name: 'Puma Motorsport Metal Badge Cap Collection',
      slug: 'puma-motorsport-metal-badge-cap-collection',
      description: 'Premium curved brim structured 6-panel cap: Brushed metal Scuderia Ferrari / BMW M badge on front crown, moisture-wicking sweatband, and metal closure.',
      price: 40,
      discount_price: 32,
      stock: 90,
      image_url: 'https://images.unsplash.com/photo-1588850561407-ed78c282e89b?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1588850561407-ed78c282e89b?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 620,
      is_featured: false,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Puma Motorsport', Material: '100% Woven Cotton Twill', Closure: 'Adjustable Metal Buckle' }
    },

    // --- 5. PUMA BASKETBALL, TRAINING, APPAREL & ACCESSORIES (28 Models) ---
    {
      name: 'Puma MB.03 LaMelo Ball Rare Signature Basketball Shoes',
      slug: 'puma-mb-03-lamelo-ball-rare-signature-basketball-shoes',
      description: 'LaMelo Ball "Not From Here" signature model: Slime claw cutouts with engineered mesh underlay, full-length NITROFOAM cushioning midsole, and high-abrasion non-slip rubber.',
      price: 125,
      discount_price: 110,
      stock: 45,
      image_url: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80'],
      rating: 5.0,
      num_reviews: 840,
      is_featured: true,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Puma Hoops', Signature: 'LaMelo Ball MB.03', Cushion: 'NITROFOAM High-Response Foam', Outsole: 'Multi-Directional Rare Claw Rubber' }
    },
    {
      name: 'Puma MB.04 LaMelo Ball Intergalactic Basketball Shoes',
      slug: 'puma-mb-04-lamelo-ball-intergalactic-basketball-shoes',
      description: 'The fourth evolution of Melo signature line: Seamless 5D printed web upper with Alien Melo graphics, dual-density NITROFOAM, and wrapped traction sidewalls.',
      price: 130,
      discount_price: 119,
      stock: 35,
      image_url: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80'],
      rating: 5.0,
      num_reviews: 420,
      is_featured: true,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Puma Hoops', Signature: 'LaMelo Ball MB.04 Edition', Upper: '5D Molded Web Mesh' }
    },
    {
      name: 'Puma All-Pro NITRO Basketball Shoes Scoot Henderson',
      slug: 'puma-all-pro-nitro-basketball-shoes-scoot-henderson',
      description: 'Engineered for explosive first-step guards: Dual-layer NITROFOAM midsole with soft inner core and firm rim, engineered cord mesh upper, and drop-in rubber cupsole.',
      price: 130,
      discount_price: 109,
      stock: 40,
      image_url: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 350,
      is_featured: false,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Puma Hoops', Foam: 'NITROFOAM Dual-Density', Upper: 'Engineered Cord Lacing Mesh' }
    },
    {
      name: 'Puma Court Rider Chaos Basketball Shoes',
      slug: 'puma-court-rider-chaos-basketball-shoes',
      description: 'Versatile indoor/outdoor hardwood shoe: Dual-density Rider foam midsole, semi-translucent wrap-around lacing cage, and high-abrasion sticky rubber.',
      price: 100,
      discount_price: 79,
      stock: 50,
      image_url: 'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?auto=format&fit=crop&w=800&q=80'],
      rating: 4.7,
      num_reviews: 290,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Puma Hoops', Midsole: 'Full-Length Dual-Density Rider Foam', Outsole: 'Sticky High-Abrasion Rubber' }
    },
    {
      name: 'Puma Fuse 3.0 CrossFit & Strength Training Shoes',
      slug: 'puma-fuse-3-0-crossfit-strength-training-shoes',
      description: 'Built for heavy squats and functional workouts: Wider toe box for foot splay, 4mm low-to-ground drop, TPU heel clip for handstand pushups, and ultra-sticky PUMAGRIP rubber.',
      price: 120,
      discount_price: 99,
      stock: 45,
      image_url: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 430,
      is_featured: true,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Puma Training', Drop: '4 mm Zero-Compromise Stable Drop', Stability: 'TPU Heel Wrap Clip', Upper: 'Abrasion-Resistant Mesh' }
    },
    {
      name: 'Puma PWRFrame TR 3 High-Intensity Training Shoes',
      slug: 'puma-pwrframe-tr-3-high-intensity-training-shoes',
      description: 'Designed for HIIT & agility drills: 3D PWRFRAME targeted support system in forefoot, high-rebound PROFOAM EVA cushioning, and PUMAGRIP rubber.',
      price: 100,
      discount_price: 84,
      stock: 55,
      image_url: 'https://images.unsplash.com/photo-1608231387042-66d1773070a5?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1608231387042-66d1773070a5?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 310,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Puma Training', System: '3D PWRFRAME Agility Matrix', Midsole: 'PROFOAM EVA' }
    },
    {
      name: 'Puma T7 Iconic Velour Track Jacket',
      slug: 'puma-t7-iconic-velour-track-jacket',
      description: 'Luxurious plush streetwear: Premium velvet velour fabric, 7cm signature contrast sleeve stripes, full metal front zipper, and ribbed cuffs and hem.',
      price: 90,
      discount_price: 75,
      stock: 60,
      image_url: 'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1556905055-8f358a7a47b2?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 580,
      is_featured: true,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Puma', Fabric: 'Plush Poly-Cotton Velour', Heritage: 'Iconic 1968 T7 7cm Sleeve Stripes' }
    },
    {
      name: 'Puma T7 Iconic Track Pants Regular Fit',
      slug: 'puma-t7-iconic-track-pants-regular-fit',
      description: 'Timeless lifestyle track pants: 7cm contrast Formstrip side inserts, elasticated waistband with drawstring, zippered ankle cuffs, and French terry interior.',
      price: 75,
      discount_price: 62,
      stock: 80,
      image_url: 'https://images.unsplash.com/photo-1552902865-b72c031ac5ea?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1552902865-b72c031ac5ea?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 940,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Puma', Material: '68% Cotton / 32% Recycled Polyester', Pockets: 'Side Pockets + Back Zipper Pocket' }
    },
    {
      name: 'Puma Downtown Oversized Graphic Hoodie',
      slug: 'puma-downtown-oversized-graphic-hoodie',
      description: 'Street-inspired relaxed fit: Heavy 380gsm unbrushed fleece cotton, embroidered retro Puma Downtown flower badge, dropped shoulders, and roomy hood.',
      price: 85,
      discount_price: 69,
      stock: 50,
      image_url: 'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1556905055-8f358a7a47b2?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 320,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Puma', Fit: 'Oversized Boxy Fit', Weight: '380 gsm Heavy Cotton' }
    },
    {
      name: 'Puma Classics Relaxed French Terry Crewneck',
      slug: 'puma-classics-relaxed-french-terry-crewneck',
      description: 'Effortless everyday layering: Soft French terry cotton, subtle embroidered Puma Archive No. 1 logo on chest, and ribbed collar and hem.',
      price: 65,
      discount_price: 52,
      stock: 75,
      image_url: 'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1556905055-8f358a7a47b2?auto=format&fit=crop&w=800&q=80'],
      rating: 4.7,
      num_reviews: 410,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Puma', Fabric: '100% Sustainable Better Cotton Initiative (BCI)', Style: 'Crewneck Sweatshirt' }
    },
    {
      name: 'Puma Formknit Seamless Compression Training Shirt',
      slug: 'puma-formknit-seamless-compression-training-shirt',
      description: 'Zero friction athletic base: Formknit seamless engineered knit mapping muscle groups for zero chafing, dryCELL moisture control, and 4-way stretch.',
      price: 50,
      discount_price: 39,
      stock: 70,
      image_url: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 260,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Puma Training', Technology: 'Formknit Seamless Construction', Fit: 'Next-to-Skin Compression' }
    },
    {
      name: 'Puma Cloudspun High-Performance Workout Tee',
      slug: 'puma-cloudspun-high-performance-workout-tee',
      description: 'The softest performance tee in sport: Proprietary CLOUDSPUN poly/spandex blend with custom-milled brushed fibers that feels like ultra-soft cotton.',
      price: 40,
      discount_price: 32,
      stock: 90,
      image_url: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 620,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Puma Training', Fabric: 'CLOUDSPUN Ultra-Soft 4-Way Stretch', Features: 'Moisture-Wicking & Anti-Odor' }
    },
    {
      name: 'Puma Ultraform High-Waist Women Running Tights',
      slug: 'puma-ultraform-high-waist-women-running-tights',
      description: 'Squat-proof compression leggings: Ultraform compressive shaping fabric, high-rise waistband with hidden drop-in back pocket, and dryCELL technology.',
      price: 70,
      discount_price: 58,
      stock: 65,
      image_url: 'https://images.unsplash.com/photo-1552902865-b72c031ac5ea?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1552902865-b72c031ac5ea?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 490,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Puma', Waist: 'Bonded High-Rise Ergonomic Waistband', Fabric: 'Ultraform Compression Knit' }
    },
    {
      name: 'Puma Train Favorite 2-in-1 Workout Shorts',
      slug: 'puma-train-favorite-2-in-1-workout-shorts',
      description: 'Dual layer gym versatility: 7-inch woven outer shell with side splits and built-in compression inner tights with phone pocket.',
      price: 50,
      discount_price: 39,
      stock: 80,
      image_url: 'https://images.unsplash.com/photo-1552902865-b72c031ac5ea?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1552902865-b72c031ac5ea?auto=format&fit=crop&w=800&q=80'],
      rating: 4.7,
      num_reviews: 350,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Puma Training', Inseam: '7-inch Woven Outer / Compression Liner', Pocket: 'Internal Phone Pocket' }
    },
    {
      name: 'Puma Studio Foundation Yoga Layer Tank Top',
      slug: 'puma-studio-foundation-yoga-layer-tank-top',
      description: 'Mindful movement apparel: Featherweight Yogini ribbed modal fabric, dropped armholes for maximum range of motion, and moisture-wicking properties.',
      price: 35,
      discount_price: 28,
      stock: 60,
      image_url: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=800&q=80'],
      rating: 4.7,
      num_reviews: 180,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Puma Studio', Fabric: 'Yogini Soft Modal Blend', Use: 'Yoga, Pilates & Barre' }
    },
    {
      name: 'Puma Flawless High-Impact Sports Bra',
      slug: 'puma-flawless-high-impact-sports-bra',
      description: 'Maximum support for running and HIIT: Molded breathable cups, adjustable racerback criss-cross straps, bonded underband, and dryCELL sweat resistance.',
      price: 55,
      discount_price: 44,
      stock: 55,
      image_url: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 310,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Puma', SupportLevel: 'High Impact (Running / Cardio)', Cups: 'Breathable Encapsulated Molded Cups' }
    },
    {
      name: 'Puma Evostripe Hybrid Full-Zip Wind Hoodie',
      slug: 'puma-evostripe-hybrid-full-zip-wind-hoodie',
      description: 'Articulated movement outerwear: Padded windproof chest panels paired with Evostripe articulated knit sleeves for complete freedom of movement.',
      price: 95,
      discount_price: 79,
      stock: 45,
      image_url: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 280,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Puma', Design: 'Evostripe Hybrid Insulation', Cut: 'Drop-Back Hem with Articulated Elbows' }
    },
    {
      name: 'Puma Essentials Padded Winter Parka Jacket',
      slug: 'puma-essentials-padded-winter-parka-jacket',
      description: 'Cold weather winter warmth: warmCELL thermal insulation that traps heat, windCELL protective fabric, water-repellent finish, and cozy fleece-lined collar.',
      price: 130,
      discount_price: 99,
      stock: 40,
      image_url: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 420,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Puma', Insulation: 'warmCELL Thermal Polyfill', Shell: 'Water-Repellent Ripstop' }
    },
    {
      name: 'Puma Classics Archive Duffle Bag 40L',
      slug: 'puma-classics-archive-duffle-bag-40l',
      description: 'Vintage barrel duffle silhouette: Heavy-duty pebbled PU leather, gold metallic Puma Archive No. 1 logo, detachable shoulder strap, and interior zippered organizer.',
      price: 65,
      discount_price: 52,
      stock: 50,
      image_url: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 310,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Puma', Capacity: '40 Liters', Material: 'Pebbled Synthetic Leather', Style: 'Retro Barrel Duffle' }
    },
    {
      name: 'Puma Challenger Gym Sports Duffel Bag S',
      slug: 'puma-challenger-gym-sports-duffel-bag-s',
      description: 'Compact daily gym companion: Side shoe compartment with mesh ventilation panel, durable coated bottom panel, dual top grab handles, and padded shoulder strap.',
      price: 40,
      discount_price: 32,
      stock: 85,
      image_url: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=800&q=80'],
      rating: 4.7,
      num_reviews: 690,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Puma', Capacity: '35 Liters', Features: 'Ventilated Shoe Pocket, Padded Base' }
    },
    {
      name: 'Puma Phase Active Lifestyle Backpack',
      slug: 'puma-phase-active-lifestyle-backpack',
      description: 'All-around daily school and training pack: Two-way zip opening into main compartment, front zip pocket, side mesh water bottle pocket, and reflective Cat loop.',
      price: 35,
      discount_price: 28,
      stock: 120,
      image_url: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=800&q=80'],
      rating: 4.7,
      num_reviews: 1450,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Puma', Volume: '22 Liters', Material: '100% 600D Polyester' }
    },
    {
      name: 'Puma Deck Backpack with Skateboard Straps',
      slug: 'puma-deck-backpack-with-skateboard-straps',
      description: 'Urban commuter with skate functionality: Dual front hook-and-loop board carrying straps, internal padded 15-inch laptop pocket, and airmesh back panel.',
      price: 50,
      discount_price: 42,
      stock: 65,
      image_url: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 430,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Puma', Features: 'Skateboard Board Carry Straps, Laptop Sleeve', Capacity: '26 Liters' }
    },
    {
      name: 'Puma Metal Cat Adjustable Performance Cap',
      slug: 'puma-metal-cat-adjustable-performance-cap',
      description: 'Clean modern athletic headwear: Brushed metallic Puma Cat emblem on left front panel, moisture-absorbing sweatband, and hook-and-loop closure.',
      price: 25,
      discount_price: 19,
      stock: 150,
      image_url: 'https://images.unsplash.com/photo-1588850561407-ed78c282e89b?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1588850561407-ed78c282e89b?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 1890,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Puma', Material: '100% Microfiber Polyester', Emblem: 'Brushed Chrome Metal Cat' }
    },
    {
      name: 'Puma Cushioned Quarter Crew Training Socks 6-Pack',
      slug: 'puma-cushioned-quarter-crew-training-socks-6-pack',
      description: 'Everyday training comfort: Half-terry cushioned footbed for impact absorption, arch compression band for snug support, and flat toe seam to prevent irritation.',
      price: 22,
      discount_price: 18,
      stock: 200,
      image_url: 'https://images.unsplash.com/photo-1586350977771-b3b0abd50c82?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1586350977771-b3b0abd50c82?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 2100,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Puma', PackSize: '6 Pairs', Features: 'Half-Terry Cushioning, Arch Support Band' }
    },
    {
      name: 'Puma TR Gym Water Bottle 750ml',
      slug: 'puma-tr-gym-water-bottle-750ml',
      description: 'BPA-free workout hydration: Spill-proof push-button spout with metal safety locking bar, volume measurement markings, and integrated finger carry loop.',
      price: 18,
      discount_price: 14,
      stock: 140,
      image_url: 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1602143407151-7111542de6e8?auto=format&fit=crop&w=800&q=80'],
      rating: 4.7,
      num_reviews: 580,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Puma', Volume: '750 ml (25 oz)', Material: '100% Eastman Tritan BPA-Free' }
    },
    {
      name: 'Puma Training Resistance Loop Bands Set of 3',
      slug: 'puma-training-resistance-loop-bands-set-of-3',
      description: 'Premium woven fabric glute and leg resistance loops: 3 progressive resistance tiers (Light, Medium, Heavy), non-slip silicone inner ribbing that won’t roll or pinch.',
      price: 28,
      discount_price: 22,
      stock: 90,
      image_url: 'https://images.unsplash.com/photo-1598289431512-b97b0917affc?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1598289431512-b97b0917affc?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 320,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Puma Training', Levels: 'Light, Medium, Heavy', Material: 'Woven Elastic Fabric with Anti-Slip Grip' }
    },
    {
      name: 'Puma Studio Luxe Non-Slip Yoga Mat 5mm',
      slug: 'puma-studio-luxe-non-slip-yoga-mat-5mm',
      description: 'Eco-friendly textured studio mat: 5mm dense cushioning for joint support, alignment center line guide, double-sided textured grip, and matching carry strap.',
      price: 45,
      discount_price: 36,
      stock: 60,
      image_url: 'https://images.unsplash.com/photo-1592432678016-e910b452f9a2?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1592432678016-e910b452f9a2?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 240,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Puma Studio', Thickness: '5 mm Dense Cushioning', Material: 'TPE Eco-Friendly Non-Slip Surface' }
    },
    {
      name: 'Puma Core Pop Women Mini Crossbody Pouch',
      slug: 'puma-core-pop-women-mini-crossbody-pouch',
      description: 'Chic everyday festival essential: Iridescent metallic Puma logo print, top zip compartment, detachable webbing shoulder strap, and front slip pocket.',
      price: 30,
      discount_price: 24,
      stock: 75,
      image_url: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=800&q=80'],
      rating: 4.7,
      num_reviews: 410,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Puma', Strap: 'Adjustable & Detachable Webbing Strap', Dimensions: '18 x 12 x 4.5 cm' }
    }
  ];
};
