// backend/utils/zaraProductsData.js
// 108 Unique, Non-Repeating Official Zara Products (Tailoring Blazers, Manteco Wool Coats, Silk Dresses, 100% Cashmere & Linen, Selvedge Denim, Boots, Leather Bags & Jo Malone / Zara Perfumes)

export const getZaraProducts = (categoryId) => {
  return [
    // --- 1. ZARA TAILORING, BLAZERS, SUITS & FORMALWEAR (20 Models) ---
    {
      name: 'Zara Double-Breasted Wool Blend Blazer',
      slug: 'zara-double-breasted-wool-blend-blazer',
      description: 'Sophisticated architectural tailoring: Structured shoulders, peaked lapels, tortoise-effect six-button front closure, welt chest pocket, and silky viscose lining.',
      price: 139,
      discount_price: 119,
      stock: 40,
      image_url: 'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1591047139829-d91aecb6caea?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 420,
      is_featured: true,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Zara', Composition: '55% Wool / 41% Polyester / 4% Elastane', Fit: 'Tailored Structured Fit', Details: 'Peak Lapels & Flap Pockets' }
    },
    {
      name: 'Zara Structured Tuxedo Blazer with Satin Lapel',
      slug: 'zara-structured-tuxedo-blazer-with-satin-lapel',
      description: 'Refined evening elegance: Contrasting lustrous silk-satin shawl lapels, single satin-covered button fastening, flap jet pockets, and clean rear central vent.',
      price: 159,
      discount_price: 135,
      stock: 35,
      image_url: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 310,
      is_featured: true,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Zara', Occasion: 'Black Tie & Evening Gala', Lapel: 'Satin Shawl Lapel', Fabric: 'Structured Poly-Viscose' }
    },
    {
      name: 'Zara Relaxed Fit Houndstooth Blazer',
      slug: 'zara-relaxed-fit-houndstooth-blazer',
      description: 'Heritage menswear-inspired micro-houndstooth check: Notched lapels, relaxed boyfriend cut, front flap pockets, and horn buttons.',
      price: 129,
      discount_price: 99,
      stock: 50,
      image_url: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 290,
      is_featured: false,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Zara', Pattern: 'Micro Houndstooth Check', Fit: 'Relaxed Boyfriend Fit' }
    },
    {
      name: 'Zara Pleated Tailored Wide-Leg Trousers',
      slug: 'zara-pleated-tailored-wide-leg-trousers',
      description: 'Flowing fluid drape: Double front waist pleats, high-rise silhouette, side slash pockets, back welt pockets, and extended tab hook-and-bar closure.',
      price: 79,
      discount_price: 65,
      stock: 85,
      image_url: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1509631179647-0177331693ae?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 780,
      is_featured: true,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Zara', Rise: 'High-Waist', Leg: 'Wide Straight Leg with Front Pleats', Material: 'Fluid Crepe Fabric' }
    },
    {
      name: 'Zara Cropped Pinstripe Wool Blazer',
      slug: 'zara-cropped-pinstripe-wool-blazer',
      description: 'Contemporary edgy suiting: Cropped waist hem, sharp padded shoulders, charcoal fine chalk pinstripe weave, and crossover single button closure.',
      price: 99,
      discount_price: 79,
      stock: 45,
      image_url: 'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1591047139829-d91aecb6caea?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 340,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Zara', Cut: 'Cropped Waist Silhouette', Pattern: 'Fine Chalk Pinstripe' }
    },
    {
      name: 'Zara High-Waisted Darted Cigarette Trousers',
      slug: 'zara-high-waisted-darted-cigarette-trousers',
      description: 'Sharp Parisian silhouette: Front pressed crease darts, cropped ankle length with subtle side hem vents, and clean concealed zip fly.',
      price: 69,
      discount_price: 55,
      stock: 70,
      image_url: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1509631179647-0177331693ae?auto=format&fit=crop&w=800&q=80'],
      rating: 4.7,
      num_reviews: 510,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Zara', Cut: 'Slim Cigarette Ankle Length', Waist: 'High-Rise Darted' }
    },
    {
      name: 'Zara Italian Fabric 100% Linen Suit Blazer',
      slug: 'zara-italian-fabric-100-linen-suit-blazer',
      description: 'Bespoke summer luxury: 100% pure Italian flax linen, partially lined for airy breathability, natural mother-of-pearl buttons, and notched lapels.',
      price: 169,
      discount_price: 139,
      stock: 35,
      image_url: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 260,
      is_featured: false,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Zara Origins', Material: '100% Italian Linen Flax', Lining: 'Unconstructed Butterfly Viscose' }
    },
    {
      name: 'Zara Italian Fabric 100% Linen Suit Trousers',
      slug: 'zara-italian-fabric-100-linen-suit-trousers',
      description: 'Matches the Italian linen blazer: Side waist adjusters with metal buckles, relaxed straight cut, slant side pockets, and breathable airy weave.',
      price: 89,
      discount_price: 75,
      stock: 45,
      image_url: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1509631179647-0177331693ae?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 210,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Zara Origins', Fabric: '100% Pure Italian Linen', Adjusters: 'Side Buckle Tabs' }
    },
    {
      name: 'Zara Oversized Masculine Silhouette Blazer',
      slug: 'zara-oversized-masculine-silhouette-blazer',
      description: 'Runway-style exaggerated proportions: Strong structured shoulders, wide lapels, longline hem, dual front flap pockets, and satin lining.',
      price: 139,
      discount_price: 115,
      stock: 50,
      image_url: 'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1591047139829-d91aecb6caea?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 620,
      is_featured: true,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Zara', Cut: 'Oversized Masculine Longline', Details: 'Structured Shoulder Pads' }
    },
    {
      name: 'Zara Tailored Vest Waistcoat with Front Buttons',
      slug: 'zara-tailored-vest-waistcoat-with-front-buttons',
      description: 'Sleek standalone or three-piece suiting vest: V-neckline, pointed front hem, contrast tonal back panel with adjustable cinch buckle.',
      price: 59,
      discount_price: 49,
      stock: 80,
      image_url: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 490,
      is_featured: false,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Zara', Closure: '5 Front Horn Buttons', Back: 'Satin Back with Cinch Buckle' }
    },
    {
      name: 'Zara Textured Bouclé Cropped Tweed Jacket',
      slug: 'zara-textured-boucle-cropped-tweed-jacket',
      description: 'French Riviera chic: Rich textured bouclé yarn with woven metallic threads, decorative gold embossed crest buttons, round collarless neckline, and patch pockets.',
      price: 119,
      discount_price: 99,
      stock: 40,
      image_url: 'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1591047139829-d91aecb6caea?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 580,
      is_featured: true,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Zara', Fabric: 'Textured Bouclé Tweed with Metallic Thread', Buttons: 'Embossed Gold Crests' }
    },
    {
      name: 'Zara Bouclé A-Line Mini Skirt',
      slug: 'zara-boucle-a-line-mini-skirt',
      description: 'Pairs perfectly with the cropped bouclé jacket: High waist fit, decorative front gold crest buttons, concealed back zipper, and full lining.',
      price: 69,
      discount_price: 55,
      stock: 55,
      image_url: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1509631179647-0177331693ae?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 320,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Zara', Silhouette: 'A-Line Mini', Details: 'Gold Decorative Crest Buttons' }
    },
    {
      name: 'Zara Velvet Evening Tuxedo Jacket',
      slug: 'zara-velvet-evening-tuxedo-jacket',
      description: 'Deep midnight black plush velvet: Satin peak lapels, jetted pockets, single-breasted closure, and opulent silky interior lining.',
      price: 169,
      discount_price: 139,
      stock: 30,
      image_url: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 190,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Zara Studio', Material: '100% Cotton Velvet with Satin Lapel', Use: 'Black Tie Evening Suiting' }
    },
    {
      name: 'Zara Premium Slim Fit Wool Suit Jacket',
      slug: 'zara-premium-slim-fit-wool-suit-jacket',
      description: 'Made with 100% Super 110s fine wool: Natural stretch, slim tapered silhouette, AMF stitch details along notch lapels, and double back vents.',
      price: 189,
      discount_price: 159,
      stock: 45,
      image_url: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 410,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Zara Man Tailored', Material: '100% Super 110s Wool', Fit: 'Slim Modern Cut' }
    },
    {
      name: 'Zara Premium Slim Fit Wool Suit Pants',
      slug: 'zara-premium-slim-fit-wool-suit-pants',
      description: 'Matching Super 110s wool trousers: Flat front, slim tapered leg, curtain waistband construction, and reinforced heel tape.',
      price: 99,
      discount_price: 85,
      stock: 60,
      image_url: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1509631179647-0177331693ae?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 350,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Zara Man Tailored', Material: '100% Super 110s Fine Wool', Waistband: 'Internal Curtain Grip' }
    },
    {
      name: 'Zara Satin Lapel Peak Collar Dinner Jacket',
      slug: 'zara-satin-lapel-peak-collar-dinner-jacket',
      description: 'Striking ecru ivory dinner jacket: Contrasting black satin peak lapels, single button fastening, ticket pocket, and double back vent.',
      price: 179,
      discount_price: 149,
      stock: 25,
      image_url: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=800&q=80'],
      rating: 5.0,
      num_reviews: 140,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Zara Evening', Color: 'Ecru Ivory with Black Satin Accents', Fit: 'Tailored Dinner Fit' }
    },
    {
      name: 'Zara Double-Breasted Pinstripe Vest',
      slug: 'zara-double-breasted-pinstripe-vest',
      description: 'Sharp sartorial waistcoat: Double-breasted four-button configuration, peaked hem, welt pockets, and back cinch tie.',
      price: 65,
      discount_price: 52,
      stock: 50,
      image_url: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=800&q=80'],
      rating: 4.7,
      num_reviews: 210,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Zara', Pattern: 'Pinstripe Suiting', Buttons: 'Double-Breasted Horn Buttons' }
    },
    {
      name: 'Zara Flared Tailored Suit Trousers',
      slug: 'zara-flared-tailored-suit-trousers',
      description: '70s retro resurgence: High-rise fitted waist that breaks into a floor-grazing flared bootcut leg with sharp front crease.',
      price: 79,
      discount_price: 64,
      stock: 65,
      image_url: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1509631179647-0177331693ae?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 380,
      is_featured: false,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Zara', Cut: 'High-Rise Flared Bootcut', Crease: 'Ironed Sharp Center Crease' }
    },
    {
      name: 'Zara Minimalist Collarless Structured Blazer',
      slug: 'zara-minimalist-collarless-structured-blazer',
      description: 'Clean architectural lines: Collarless round neckline, hidden hook-and-eye closure, clean seamless flapless pockets, and crisp shoulder silhouette.',
      price: 119,
      discount_price: 95,
      stock: 45,
      image_url: 'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1591047139829-d91aecb6caea?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 270,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Zara', Style: 'Collarless Minimalist Tailoring', Closure: 'Concealed Front Hook' }
    },
    {
      name: 'Zara Metallic Thread Jacquard Evening Jacket',
      slug: 'zara-metallic-thread-jacquard-evening-jacket',
      description: 'Opulent baroque floral jacquard with woven silver and gold lurex threads, solid black satin notched lapels, and tailored single button cut.',
      price: 159,
      discount_price: 129,
      stock: 30,
      image_url: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 160,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Zara Studio', Weave: 'Baroque Jacquard with Lurex', Lapel: 'Satin Notched Lapel' }
    },

    // --- 2. ZARA COATS, JACKETS, LEATHER & OUTERWEAR (20 Models) ---
    {
      name: 'Zara Manteco 100% Wool Belted Wrap Coat',
      slug: 'zara-manteco-100-wool-belted-wrap-coat',
      description: 'Iconic Italian Manteco wool outerwear: Generous notch lapels, self-fabric tie belt, deep welt pockets, raglan sleeves, and longline ankle-grazing silhouette.',
      price: 249,
      discount_price: 219,
      stock: 35,
      image_url: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=800&q=80'],
      rating: 5.0,
      num_reviews: 640,
      is_featured: true,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Zara Manteco Edition', Fabric: '100% Italian Manteco Virgin Wool', Closure: 'Self-Tie Belted Wrap', Length: 'Longline Maxi' }
    },
    {
      name: 'Zara Double-Faced Faux Shearling Aviator Jacket',
      slug: 'zara-double-faced-faux-shearling-aviator-jacket',
      description: 'Heavyweight winter statement: Crackled faux leather exterior with plush faux shearling lining, double buckle throat latch collar, and asymmetric front zip.',
      price: 149,
      discount_price: 129,
      stock: 45,
      image_url: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 820,
      is_featured: true,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Zara', Outer: 'Crackled Faux Leather', Lining: 'Plush Faux Shearling Fur', Collar: 'Double Metal Buckle Collar' }
    },
    {
      name: 'Zara Faux Leather Biker Moto Jacket',
      slug: 'zara-faux-leather-biker-moto-jacket',
      description: 'Classic rock-and-roll moto: Snap-down lapels, asymmetric silver zip front, zippered cuffs, belted waist with silver metal buckle, and coin pocket.',
      price: 99,
      discount_price: 79,
      stock: 90,
      image_url: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 1450,
      is_featured: true,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Zara', Hardware: 'Silver Heavy Metal Zippers', Belt: 'Adjustable Hem Buckle Belt' }
    },
    {
      name: 'Zara Water-Repellent Puffer Jacket with High Collar',
      slug: 'zara-water-repellent-puffer-jacket-with-high-collar',
      description: 'Quilted cloud warmth: Windproof and water-repellent shell, high protective funnel collar, adjustable bottom bungee cords, and thermal micro-fleece lined pockets.',
      price: 89,
      discount_price: 69,
      stock: 75,
      image_url: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 930,
      is_featured: false,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Zara Outerwear', Fill: 'Recycled Thermal Polyfill', Features: 'Water-Repellent & Windproof' }
    },
    {
      name: 'Zara Classic Double-Breasted Trench Coat',
      slug: 'zara-classic-double-breasted-trench-coat',
      description: 'Timeless transitional icon: Water-resistant cotton twill gabardine, storm flap, shoulder epaulettes, belted cuffs, buckle waist belt, and deep back vent.',
      price: 149,
      discount_price: 119,
      stock: 60,
      image_url: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 760,
      is_featured: true,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Zara', Material: '100% Water-Resistant Cotton Gabardine', Details: 'Shoulder Epaulettes & Gun Flap' }
    },
    {
      name: 'Zara Oversized Wool Blend Cocoon Coat',
      slug: 'zara-oversized-wool-blend-cocoon-coat',
      description: 'Sculptural rounded cocoon silhouette: Heavyweight brushed wool blend, dropped shoulders, hidden snap button placket, and cozy side seam pockets.',
      price: 179,
      discount_price: 149,
      stock: 40,
      image_url: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 380,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Zara', Composition: '70% Wool / 30% Polyamide', Silhouette: 'Oversized Cocoon' }
    },
    {
      name: 'Zara Distressed Leather Overshirt Jacket',
      slug: 'zara-distressed-leather-overshirt-jacket',
      description: 'Vintage patina washed look: 100% genuine goat suede leather, snap front placket, flap chest pockets, point collar, and relaxed overshirt fit.',
      price: 199,
      discount_price: 169,
      stock: 30,
      image_url: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 290,
      is_featured: false,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Zara Origins', Material: '100% Genuine Distressed Suede', Style: 'Heavyweight Leather Overshirt' }
    },
    {
      name: 'Zara Quilted Hooded Parka with Thermal Fill',
      slug: 'zara-quilted-hooded-parka-with-thermal-fill',
      description: 'Sub-zero warmth: Longline length down to knees, storm cuffs with thumbholes, removable faux fur trim hood, and dual fleece-lined chest handwarmer pockets.',
      price: 169,
      discount_price: 135,
      stock: 40,
      image_url: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 450,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Zara Technical', Insulation: 'Extreme Cold Weather Polyfill', Length: 'Knee-Length Parka' }
    },
    {
      name: 'Zara Short Faux Suede Trench Jacket',
      slug: 'zara-short-faux-suede-trench-jacket',
      description: 'Cropped modern twist on trench styling: Velvety soft faux suede, storm flaps, double-breasted horn buttons, and wide notched collar.',
      price: 89,
      discount_price: 72,
      stock: 65,
      image_url: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=800&q=80'],
      rating: 4.7,
      num_reviews: 320,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Zara', Material: 'Faux Suede Microfiber', Cut: 'Cropped Waist Trench' }
    },
    {
      name: 'Zara Fluffy Faux Fur Longline Winter Coat',
      slug: 'zara-fluffy-faux-fur-longline-winter-coat',
      description: 'Ultra-luxurious teddy texture: Soft dense faux fur, wide lapels, concealed hook closures, side pockets, and satin lining.',
      price: 159,
      discount_price: 129,
      stock: 35,
      image_url: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 510,
      is_featured: false,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Zara', Texture: 'High-Density Plush Faux Fur', Closure: 'Concealed Metal Eyelet Hooks' }
    },
    {
      name: 'Zara Cropped Bomber Jacket with Ribbed Trims',
      slug: 'zara-cropped-bomber-jacket-with-ribbed-trims',
      description: 'Streetwear staple: Satin-sheen nylon shell, ribbed collar and hem, ruched sleeves, utility sleeve zip pocket, and bright contrast orange interior lining.',
      price: 89,
      discount_price: 69,
      stock: 70,
      image_url: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 640,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Zara', Shell: 'Satin Nylon', Details: 'MA-1 Arm Utility Pocket & Ruched Sleeves' }
    },
    {
      name: 'Zara Waxed Finish Hooded Utility Jacket',
      slug: 'zara-waxed-finish-hooded-utility-jacket',
      description: 'Country heritage meets urban utility: Water-resistant waxed cotton shell, corduroy collar lining, four gusseted cargo pockets, and heavy two-way brass zipper.',
      price: 139,
      discount_price: 110,
      stock: 45,
      image_url: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 310,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Zara Man', Finish: 'Waxed Water-Repellent Cotton', Trim: 'Corduroy Collar Facing' }
    },
    {
      name: 'Zara Reversible Quilted Padded Gilet Vest',
      slug: 'zara-reversible-quilted-padded-gilet-vest',
      description: 'Two looks in one: Diamond-quilted water-resistant nylon on one side, soft cozy fleece on the reverse, stand collar, and snap button closure.',
      price: 69,
      discount_price: 55,
      stock: 80,
      image_url: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&w=800&q=80'],
      rating: 4.7,
      num_reviews: 420,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Zara', Design: '100% Reversible Gilet', Sides: 'Diamond Quilted Nylon / Polar Fleece' }
    },
    {
      name: 'Zara Heavyweight Suede Trucker Jacket',
      slug: 'zara-heavyweight-suede-trucker-jacket',
      description: 'Timeless American silhouette in rich goat suede: Metal shank button front, flap chest pockets, adjustable waist tabs, and full lining.',
      price: 189,
      discount_price: 155,
      stock: 35,
      image_url: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 260,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Zara Origins', Material: '100% Goat Suede Leather', Cut: 'Classic Trucker Silhouette' }
    },
    {
      name: 'Zara Wool Blend Car Coat with Concealed Placket',
      slug: 'zara-wool-blend-car-coat-with-concealed-placket',
      description: 'Streamlined minimalist outerwear: Point collar, hidden horn button closure, diagonal welt pockets, and water-resistant wool blend fabric.',
      price: 169,
      discount_price: 139,
      stock: 45,
      image_url: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 340,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Zara Man', Style: 'Minimalist Car Coat', Closure: 'Hidden Fly Button Front' }
    },
    {
      name: 'Zara Contrast Stitching Denim Trucker Jacket',
      slug: 'zara-contrast-stitching-denim-trucker-jacket',
      description: 'Heavy 13oz rigid denim: Contrast white topstitching, copper shank buttons, flap chest pockets with button closure, and boxy vintage fit.',
      price: 79,
      discount_price: 64,
      stock: 85,
      image_url: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&w=800&q=80'],
      rating: 4.7,
      num_reviews: 580,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Zara Denim', Weight: '13 oz Rigid Cotton Denim', Fit: 'Boxy Vintage 90s' }
    },
    {
      name: 'Zara Technical Windproof Anorak with Bungee Cords',
      slug: 'zara-technical-windproof-anorak-with-bungee-cords',
      description: 'Gorpcore aesthetic: Half-zip front with storm flap, large front kangaroo flap pocket, adjustable bungee toggles at hem and hood, and matte water-repellent ripstop.',
      price: 89,
      discount_price: 69,
      stock: 60,
      image_url: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 290,
      is_featured: false,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Zara Technical', Shell: 'Matte Ripstop Nylon', Features: 'Half-Zip Overhead Anorak' }
    },
    {
      name: 'Zara Short Belted Rain Mac Jacket',
      slug: 'zara-short-belted-rain-mac-jacket',
      description: 'Chic rainy day companion: Waterproof polyurethane coated fabric, raglan sleeves, horn buttons, removable belt with buckle, and taped storm hood.',
      price: 99,
      discount_price: 79,
      stock: 50,
      image_url: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=800&q=80'],
      rating: 4.7,
      num_reviews: 210,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Zara', Waterproofing: '100% Sealed PU Coating', Length: 'Hip Length Mac' }
    },
    {
      name: 'Zara Shearling Lined Biker Jacket',
      slug: 'zara-shearling-lined-biker-jacket',
      description: 'Thick faux shearling notched collar and cuffs, matte pebbled faux leather body, silver heavy metal hardware, and warm fleece interior.',
      price: 139,
      discount_price: 110,
      stock: 45,
      image_url: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 370,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Zara', Collar: 'Turn-Down Shearling Lapels', Fit: 'Regular Moto Fit' }
    },
    {
      name: 'Zara Oversized Peacoat with Tortoiseshell Buttons',
      slug: 'zara-oversized-peacoat-with-tortoiseshell-buttons',
      description: 'Nautical-inspired double-breasted coat: Heavy wool blend fabric, oversized convertible notched collar, deep handwarmer pockets, and tortoiseshell buttons.',
      price: 169,
      discount_price: 135,
      stock: 40,
      image_url: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 430,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Zara', Heritage: 'Classic Naval Peacoat Cut', Material: '65% Wool / 35% Synthetic Blend' }
    },

    // --- 3. ZARA DRESSES, SKIRTS & EVENING GLAMOUR (20 Models) ---
    {
      name: 'Zara 100% Mulberry Silk Bias-Cut Slip Dress',
      slug: 'zara-100-mulberry-silk-bias-cut-slip-dress',
      description: 'Effortless 90s minimalism: 100% pure Mulberry silk charmeuse cut on the bias to drape smoothly over curves, delicate adjustable spaghetti straps, and subtle cowl neckline.',
      price: 169,
      discount_price: 139,
      stock: 40,
      image_url: 'https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?auto=format&fit=crop&w=800&q=80'],
      rating: 5.0,
      num_reviews: 580,
      is_featured: true,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Zara Studio', Material: '100% Pure Mulberry Silk Charmeuse', Cut: 'Bias-Cut Slip Silhouette', Length: 'Midi Length' }
    },
    {
      name: 'Zara Draped Asymmetrical Satin Evening Gown',
      slug: 'zara-draped-asymmetrical-satin-evening-gown',
      description: 'Red carpet stunner: One-shoulder neckline with draped cascading sash, gathered waist detailing, high leg side slit, and lustrous heavyweight satin.',
      price: 149,
      discount_price: 125,
      stock: 35,
      image_url: 'https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 420,
      is_featured: true,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Zara Woman', Neckline: 'Asymmetrical One-Shoulder', Detail: 'High Slit & Ruched Waist Draping' }
    },
    {
      name: 'Zara Plissé Pleated Midi Dress with Belt',
      slug: 'zara-plisse-pleated-midi-dress-with-belt',
      description: 'Fluid permanent micro-pleating: Long billowing sleeves with elastic cuffs, V-neckline, self-tie belt with metallic aglets, and flared hem.',
      price: 89,
      discount_price: 69,
      stock: 65,
      image_url: 'https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 690,
      is_featured: false,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Zara', Fabric: 'Plissé Micro-Pleated Crepe', Belt: 'Matching Cinch Belt Included' }
    },
    {
      name: 'Zara Cut-Out Linen Blend Halterneck Dress',
      slug: 'zara-cut-out-linen-blend-halterneck-dress',
      description: 'Sun-drenched summer vacation vibe: Self-tie halterneck strap, side waist cut-outs with elasticated back band, breezy linen-viscose blend, and tier skirt.',
      price: 79,
      discount_price: 62,
      stock: 75,
      image_url: 'https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 510,
      is_featured: false,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Zara', Material: '55% Linen / 45% Viscose', Details: 'Side Midriff Cutouts' }
    },
    {
      name: 'Zara Poplin Tiered Ruffle Maxi Dress',
      slug: 'zara-poplin-tiered-ruffle-maxi-dress',
      description: 'Voluminous breezy 100% crisp cotton poplin: Square neckline, gathered tiered ruffled skirts, hidden side pockets, and low back with tie detail.',
      price: 89,
      discount_price: 72,
      stock: 60,
      image_url: 'https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 430,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Zara', Fabric: '100% Crisp Cotton Poplin', Silhouette: 'Voluminous Tiered Maxi' }
    },
    {
      name: 'Zara Jacquard Floral Slip Midi Dress',
      slug: 'zara-jacquard-floral-slip-midi-dress',
      description: 'Subtle tone-on-tone woven botanical jacquard: Deep V-neckline, lace trim insert along bodice, delicate crossover back straps, and mermaid flared hem.',
      price: 99,
      discount_price: 79,
      stock: 50,
      image_url: 'https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 320,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Zara', Weave: 'Satin Jacquard Floral Pattern', Trim: 'Eyelash Lace Edge' }
    },
    {
      name: 'Zara Sequined Backless Mini Party Dress',
      slug: 'zara-sequined-backless-mini-party-dress',
      description: 'High-octane party glamour: All-over micro sequins that catch the light, round high neck, long sleeves, plunging open back with strap, and full stretch lining.',
      price: 119,
      discount_price: 95,
      stock: 45,
      image_url: 'https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 670,
      is_featured: true,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Zara Party', Details: 'High-Density Micro Sequins & Deep Backless Cut', Length: 'Mini Length' }
    },
    {
      name: 'Zara Ribbed Knit Bodycon Midi Dress',
      slug: 'zara-ribbed-knit-bodycon-midi-dress',
      description: 'Figure-hugging compact knit: Sweetheart neckline with structured bust cups, wide shoulder straps, stretchy ribbed texture, and side hem slit.',
      price: 69,
      discount_price: 52,
      stock: 90,
      image_url: 'https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 840,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Zara Knit', Fabric: 'Viscose Blend Compact Rib', Fit: 'Bodycon Contour Fit' }
    },
    {
      name: 'Zara Embroidered Organza Cocktail Dress',
      slug: 'zara-embroidered-organza-cocktail-dress',
      description: 'Semi-sheer puff sleeve fantasy: Delicately embroidered floral motifs over sheer organza, fitted bodice, A-line skirt, and attached matching slip dress.',
      price: 129,
      discount_price: 105,
      stock: 35,
      image_url: 'https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 240,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Zara Studio', Material: 'Embroidered Semi-Sheer Organza', Sleeves: 'Voluminous Puff Sleeves' }
    },
    {
      name: 'Zara Corset Style Structured Strapless Dress',
      slug: 'zara-corset-style-structured-strapless-dress',
      description: 'Architectural boning in bodice: Strapless straight-across neckline with silicone grip tape, internal supportive boning, gathered wrap tulip skirt, and back zip.',
      price: 99,
      discount_price: 79,
      stock: 50,
      image_url: 'https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 390,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Zara', Bodice: 'Internal Structural Boning', Grip: 'Silicone Non-Slip Tape' }
    },
    {
      name: 'Zara Satin Pleated Wrap Midi Skirt',
      slug: 'zara-satin-pleated-wrap-midi-skirt',
      description: 'Liquid shine finish: High-rise elasticated waistband, asymmetrical overlapping wrap front with soft accordion pleating, and graceful midi hem.',
      price: 65,
      discount_price: 49,
      stock: 80,
      image_url: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1509631179647-0177331693ae?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 530,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Zara', Fabric: 'Lustrous Poly-Satin', Waist: 'Elastic High Waist' }
    },
    {
      name: 'Zara Faux Leather Pencil Skirt with Front Slit',
      slug: 'zara-faux-leather-pencil-skirt-with-front-slit',
      description: 'Modern power dressing: Supple faux leather with matte finish, high-waisted tailored darts, sharp central front slit, and concealed back zipper.',
      price: 69,
      discount_price: 55,
      stock: 65,
      image_url: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1509631179647-0177331693ae?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 410,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Zara', Cut: 'Tailored Pencil Skirt with Center Slit', Material: 'Polyurethane Faux Leather' }
    },
    {
      name: 'Zara Tiered Bohemian Maxi Skirt',
      slug: 'zara-tiered-bohemian-maxi-skirt',
      description: 'Airy romantic tiers: Smocked elastic waistband with drawstring tie, floral botanical woodblock print, and flowing tiered hem.',
      price: 75,
      discount_price: 59,
      stock: 70,
      image_url: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1509631179647-0177331693ae?auto=format&fit=crop&w=800&q=80'],
      rating: 4.7,
      num_reviews: 350,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Zara', Fabric: '100% Lightweight Viscose', Style: 'Boho Tiered Maxi' }
    },
    {
      name: 'Zara Metallic Pleated High-Waist Midi Skirt',
      slug: 'zara-metallic-pleated-high-waist-midi-skirt',
      description: 'Shimmering liquid silver: Permanent accordion sunburst pleats, metallic coated jersey fabric, elastic waistband, and dramatic twirl movement.',
      price: 79,
      discount_price: 62,
      stock: 55,
      image_url: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1509631179647-0177331693ae?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 480,
      is_featured: false,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Zara Woman', Finish: 'Liquid Silver Foil Coating', Pleats: 'Sunburst Accordion Pleats' }
    },
    {
      name: 'Zara Denim Maxi Column Skirt with Raw Hem',
      slug: 'zara-denim-maxi-column-skirt-with-raw-hem',
      description: 'Streetwear favorite: Heavyweight washed cotton denim, five classic pockets, high center front vent for easy walking, and raw distressed hem.',
      price: 69,
      discount_price: 55,
      stock: 85,
      image_url: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1509631179647-0177331693ae?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 910,
      is_featured: true,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Zara Denim', Cut: 'Maxi Column Skirt with Front Slit', Hem: 'Frayed Raw Edge' }
    },
    {
      name: 'Zara Velvet Draped One-Shoulder Evening Dress',
      slug: 'zara-velvet-draped-one-shoulder-evening-dress',
      description: 'Rich emerald green plush velvet: Single long sleeve, gathered diagonal ruching across the hips, bodycon fit, and concealed side zipper.',
      price: 119,
      discount_price: 95,
      stock: 40,
      image_url: 'https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 310,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Zara Evening', Fabric: 'Stretch Poly-Velvet', Color: 'Deep Emerald Green' }
    },
    {
      name: 'Zara Off-The-Shoulder Ruched Mesh Midi Dress',
      slug: 'zara-off-the-shoulder-ruched-mesh-midi-dress',
      description: 'Contour sculpting: Double-layered stretch tulle mesh, flattering all-over horizontal ruching, Bardot off-the-shoulder neckline, and full lining.',
      price: 79,
      discount_price: 64,
      stock: 60,
      image_url: 'https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 440,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Zara', Neckline: 'Bardot Off-The-Shoulder', Fabric: 'Double-Layered Ruching Mesh' }
    },
    {
      name: 'Zara Belted Utility Shirt Dress with Pockets',
      slug: 'zara-belted-utility-shirt-dress-with-pockets',
      description: 'Safari utility chic: Crisp cotton twill, button-up front, point collar, flap chest pockets, removable D-ring buckle belt, and roll-tab long sleeves.',
      price: 89,
      discount_price: 69,
      stock: 70,
      image_url: 'https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?auto=format&fit=crop&w=800&q=80'],
      rating: 4.7,
      num_reviews: 520,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Zara Woman', Style: 'Utility Cargo Shirt Dress', Belt: 'Matching Belt with Metal D-Ring' }
    },
    {
      name: 'Zara Smocked Bodice Floral Chiffon Dress',
      slug: 'zara-smocked-bodice-floral-chiffon-dress',
      description: 'Whimsical garden floral: Stretchy smocked elastic bodice that hugs comfortably, sweetheart neckline with self-tie, semi-sheer chiffon puff sleeves, and tiered skirt.',
      price: 85,
      discount_price: 68,
      stock: 65,
      image_url: 'https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 390,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Zara', Bodice: 'Smocked Elastic Stretch', Fabric: 'Printed Airy Chiffon' }
    },
    {
      name: 'Zara Halterneck Column Gown with Slit',
      slug: 'zara-halterneck-column-gown-with-slit',
      description: 'Sleek statuesque black tie column dress: High halter neckline with button fastening at back neck, open back, floor-skimming hem, and thigh-high side slit.',
      price: 139,
      discount_price: 110,
      stock: 35,
      image_url: 'https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 280,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Zara Evening', Cut: 'Sleek Column Maxi Gown', Slit: 'Thigh-High Side Slit' }
    },

    // --- 4. ZARA KNITWEAR, SHIRTS, BLOUSES & PREMIUM DENIM (20 Models) ---
    {
      name: 'Zara 100% Cashmere Crewneck Sweater',
      slug: 'zara-100-cashmere-crewneck-sweater',
      description: 'Supreme softness: 100% pure premium Inner Mongolian cashmere, ribbed crewneck collar, cuffs and hem, regular relaxed fit, and ultra-lightweight warmth.',
      price: 159,
      discount_price: 129,
      stock: 40,
      image_url: 'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1556905055-8f358a7a47b2?auto=format&fit=crop&w=800&q=80'],
      rating: 5.0,
      num_reviews: 540,
      is_featured: true,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Zara Origins', Material: '100% Pure Grade-A Mongolian Cashmere', Gauge: '12-Gauge Fine Knit' }
    },
    {
      name: 'Zara 100% Pure Extrafine Merino Wool Turtleneck',
      slug: 'zara-100-pure-extrafine-merino-wool-turtleneck',
      description: 'Essential layering piece: Spun from 19.5-micron Italian extrafine Merino wool, snug roll neck, seamless tubular knit torso, and ribbed trim.',
      price: 79,
      discount_price: 64,
      stock: 80,
      image_url: 'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1556905055-8f358a7a47b2?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 790,
      is_featured: false,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Zara Man', Material: '100% Extrafine Italian Merino Wool', Neck: 'Foldover Roll Turtleneck' }
    },
    {
      name: 'Zara Cable-Knit Chunky Wool Blend Cardigan',
      slug: 'zara-cable-knit-chunky-wool-blend-cardigan',
      description: 'Rustic cozy charm: Intricate traditional cable and honeycomb knit pattern, V-neckline, faux horn oversized buttons, and dropped shoulders.',
      price: 99,
      discount_price: 79,
      stock: 55,
      image_url: 'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1556905055-8f358a7a47b2?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 620,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Zara Knit', Stitch: 'Heavy Cable & Honeycomb Stitch', Buttons: 'Large Faux Horn Buttons' }
    },
    {
      name: 'Zara Ribbed Polo Collar Knit Sweater',
      slug: 'zara-ribbed-polo-collar-knit-sweater',
      description: 'Modern preppy aesthetic: Open Johnny collar with no buttons, fine ribbed modal-cotton knit, slim tailored fit, and long sleeves.',
      price: 65,
      discount_price: 49,
      stock: 70,
      image_url: 'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1556905055-8f358a7a47b2?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 430,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Zara', Collar: 'Open V-Polo Collar', Fabric: 'Ribbed Cotton-Modal Blend' }
    },
    {
      name: 'Zara Fuzzy Mohair Blend V-Neck Pullover',
      slug: 'zara-fuzzy-mohair-blend-v-neck-pullover',
      description: 'Cloud-like brushed texture: Rich mohair and wool blend with a soft fuzzy halo, deep ribbed V-neckline, and relaxed slouchy body.',
      price: 89,
      discount_price: 72,
      stock: 45,
      image_url: 'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1556905055-8f358a7a47b2?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 310,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Zara Studio', Yarn: 'Brushed Mohair & Wool Blend', Cut: 'Slouchy V-Neck' }
    },
    {
      name: 'Zara 100% French Linen Relaxed Button-Down Shirt',
      slug: 'zara-100-french-linen-relaxed-button-down-shirt',
      description: 'Breathable Mediterranean essential: 100% Normandy French flax linen, garment-washed for lived-in softness, point collar, and mother-of-pearl buttons.',
      price: 69,
      discount_price: 55,
      stock: 100,
      image_url: 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 1240,
      is_featured: true,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Zara Origins', Material: '100% French Flax Linen', Finish: 'Garment Enzyme Washed' }
    },
    {
      name: 'Zara Poplin Oversized Boyfriend Shirt',
      slug: 'zara-poplin-oversized-boyfriend-shirt',
      description: 'Effortless classic tailoring: Crisp 100% cotton poplin, dropped shoulders, long sleeves with double button cuffs, chest patch pocket, and curved shirttail hem.',
      price: 59,
      discount_price: 45,
      stock: 120,
      image_url: 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 1680,
      is_featured: true,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Zara Woman', Fabric: '100% Cotton Poplin', Fit: 'Oversized Boyfriend Silhouette' }
    },
    {
      name: 'Zara Silk Satin Tie-Neck Bow Blouse',
      slug: 'zara-silk-satin-tie-neck-bow-blouse',
      description: 'Feminine retro polish: Lustrous silk-blend satin, dramatic lavallière tie neck bow, gathered shoulder seams, and concealed front button fastening.',
      price: 79,
      discount_price: 64,
      stock: 60,
      image_url: 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 380,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Zara Woman', Neckline: 'Lavallière Tie-Neck Bow', Fabric: 'Silk Blend Satin' }
    },
    {
      name: 'Zara Ruffled Victorian High-Neck Romantic Blouse',
      slug: 'zara-ruffled-victorian-high-neck-romantic-blouse',
      description: 'Vintage romance: Ruffled stand collar, delicate pintuck pleating along chest bib, lace ladder inserts, balloon sleeves, and covered buttons.',
      price: 69,
      discount_price: 52,
      stock: 55,
      image_url: 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 290,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Zara', Collar: 'Ruffled Victorian Stand Collar', Details: 'Pintuck Pleating & Lace Insets' }
    },
    {
      name: 'Zara Striped Oxford Cotton Classic Shirt',
      slug: 'zara-striped-oxford-cotton-classic-shirt',
      description: 'Timeless smart-casual staple: Heavyweight yarn-dyed Oxford weave cotton in light blue and white Bengal stripe, button-down collar, and box pleat back.',
      price: 59,
      discount_price: 48,
      stock: 90,
      image_url: 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 840,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Zara Man', Fabric: '100% Yarn-Dyed Oxford Cotton', Pattern: 'Bengal Blue Stripe' }
    },
    {
      name: 'Zara Crochet Open-Knit Resort Top',
      slug: 'zara-crochet-open-knit-resort-top',
      description: 'Artisanal beachside crochet: Hand-crafted look geometric open-work stitching, cotton yarn, camp collar, and wooden front button closure.',
      price: 65,
      discount_price: 52,
      stock: 65,
      image_url: 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 420,
      is_featured: false,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Zara Origins', Knit: 'Open Geometric Cotton Crochet', Collar: 'Camp Resort Collar' }
    },
    {
      name: 'Zara Selvedge Rigid High-Rise Straight Jeans',
      slug: 'zara-selvedge-rigid-high-rise-straight-jeans',
      description: 'Authentic redline shuttle-loom denim: 100% 14oz non-stretch Japanese selvedge denim, copper rivets, classic button fly, and straight leg profile.',
      price: 99,
      discount_price: 85,
      stock: 60,
      image_url: 'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1541099649105-f69ad21f3246?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 730,
      is_featured: true,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Zara Selvedge Denim', Denim: '14 oz Redline Shuttle Loom Denim', Cut: 'High-Rise Straight Leg' }
    },
    {
      name: 'Zara Wide-Leg Marine Flare Denim Jeans',
      slug: 'zara-wide-leg-marine-flare-denim-jeans',
      description: 'The viral high-waisted favorite: Sailor-style front patch pockets, high rise waist, fitted through hip with dramatic wide flare leg, and raw hem.',
      price: 69,
      discount_price: 52,
      stock: 110,
      image_url: 'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1541099649105-f69ad21f3246?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 2150,
      is_featured: true,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Zara Denim', Style: 'Marine Straight Wide-Leg', Pockets: 'Sailor Front Patch Pockets' }
    },
    {
      name: 'Zara Relaxed Baggy 90s Low-Rise Jeans',
      slug: 'zara-relaxed-baggy-90s-low-rise-jeans',
      description: 'Nostalgic Y2K skateboard denim: Loose relaxed fit through thigh and leg, low-slung waist, heavy stone-washed treatment, and vintage fading.',
      price: 65,
      discount_price: 49,
      stock: 95,
      image_url: 'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1541099649105-f69ad21f3246?auto=format&fit=crop&w=800&q=80'],
      rating: 4.7,
      num_reviews: 840,
      is_featured: false,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Zara Denim', Rise: 'Low-Slung Waist', Fit: 'Baggy 90s Skate Cut' }
    },
    {
      name: 'Zara Slim Fit Comfort Stretch Denim Jeans',
      slug: 'zara-slim-fit-comfort-stretch-denim-jeans',
      description: 'All-day flexible comfort: 98% cotton with 2% elastane for maximum recovery, clean dark indigo wash, zip fly, and tailored slim leg.',
      price: 59,
      discount_price: 45,
      stock: 130,
      image_url: 'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1541099649105-f69ad21f3246?auto=format&fit=crop&w=800&q=80'],
      rating: 4.7,
      num_reviews: 1420,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Zara Man Denim', Stretch: '2% Elastane Comfort Stretch', Wash: 'Clean Dark Indigo' }
    },
    {
      name: 'Zara Cargo Denim Trousers with Utility Pockets',
      slug: 'zara-cargo-denim-trousers-with-utility-pockets',
      description: 'Street utilitarian: Sturdy washed denim with multiple 3D bellowed cargo pockets along side legs, hammer loop, and straight baggy cut.',
      price: 75,
      discount_price: 59,
      stock: 75,
      image_url: 'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1541099649105-f69ad21f3246?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 620,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Zara TRF', Pockets: '6 Multi-Cargo Utility Pockets', Style: 'Cargo Utility Pants' }
    },
    {
      name: 'Zara Ecru Barrel Leg High-Waist Jeans',
      slug: 'zara-ecru-barrel-leg-high-waist-jeans',
      description: 'Modern sculptural denim: Curved horseshoe barrel leg silhouette that curves outward at the knee and tapers at ankle in unbleached ecru denim.',
      price: 69,
      discount_price: 55,
      stock: 65,
      image_url: 'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1541099649105-f69ad21f3246?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 490,
      is_featured: false,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Zara', Cut: 'Horseshoe Barrel Leg', Color: 'Natural Ecru Cotton' }
    },
    {
      name: 'Zara Heavyweight Supima Cotton Minimalist T-Shirt',
      slug: 'zara-heavyweight-supima-cotton-minimalist-t-shirt',
      description: 'The ultimate luxury tee: 280gsm long-staple American Supima cotton, dense rib knit collar that will never bacon, and clean boxy cut.',
      price: 35,
      discount_price: 28,
      stock: 180,
      image_url: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 1950,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Zara Origins', Cotton: '100% Heavyweight American Supima (280 gsm)', Fit: 'Boxy Heavy Tee' }
    },
    {
      name: 'Zara Fluid Modal Long Sleeve Base Layer Top',
      slug: 'zara-fluid-modal-long-sleeve-base-layer-top',
      description: 'Second-skin softness: Micro-modal fabric with 4-way stretch, crewneck neckline, raw-cut seamless cuffs, and silky smooth drape.',
      price: 29,
      discount_price: 22,
      stock: 140,
      image_url: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 860,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Zara Basic', Material: '95% Micro-Modal / 5% Elastane', Feel: 'Buttery Ultra-Soft' }
    },
    {
      name: 'Zara Striped Nautical Breton Sailor Top',
      slug: 'zara-striped-nautical-breton-sailor-top',
      description: 'French maritime classic: Heavyweight carded cotton, boat neckline, yarn-dyed navy and white horizontal stripes, and 3/4 sleeves.',
      price: 39,
      discount_price: 29,
      stock: 100,
      image_url: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 730,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Zara', Neckline: 'Boat Bateau Neckline', Pattern: 'Authentic Breton Navy Stripe' }
    },

    // --- 5. ZARA FOOTWEAR, HANDBAGS, FRAGRANCES & ACCESSORIES (28 Models) ---
    {
      name: 'Zara 100% Leather Pointed Toe Stiletto Boots',
      slug: 'zara-100-leather-pointed-toe-stiletto-boots',
      description: 'Dramatic high-fashion statement: 100% supple goat leather, sharp pointed toe, 9cm sleek stiletto heel, inner zipper, and cushioned insole.',
      price: 169,
      discount_price: 139,
      stock: 45,
      image_url: 'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1543163521-1bf539c55dd2?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 490,
      is_featured: true,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Zara Woman', Material: '100% Supple Goat Leather', Heel: '9 cm Slim Stiletto', Toe: 'Sharp Pointed' }
    },
    {
      name: 'Zara Leather Chunky Lug Sole Chelsea Boots',
      slug: 'zara-leather-chunky-lug-sole-chelsea-boots',
      description: 'Rugged urban essential: 100% cowhide leather upper, elastic side gores, pull tabs, and exaggerated 5cm lightweight lugged rubber platform sole.',
      price: 129,
      discount_price: 99,
      stock: 75,
      image_url: 'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1543163521-1bf539c55dd2?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 1320,
      is_featured: true,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Zara Shoes', Upper: '100% Cowhide Leather', Sole: '5 cm Lightweight Lug Platform Rubber' }
    },
    {
      name: 'Zara Knee-High Supple Leather Riding Boots',
      slug: 'zara-knee-high-supple-leather-riding-boots',
      description: 'Equestrian grace: Smooth burnished cow leather shaft that hits just below the knee, low 3cm block heel, clean pull-on fit, and rounded toe.',
      price: 199,
      discount_price: 169,
      stock: 35,
      image_url: 'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1543163521-1bf539c55dd2?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 380,
      is_featured: false,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Zara Studio', Shaft: 'Knee-High Burnished Leather', Heel: '3 cm Stacked Block Heel' }
    },
    {
      name: 'Zara Suede Square-Toe Block Heel Ankle Boots',
      slug: 'zara-suede-square-toe-block-heel-ankle-boots',
      description: '60s Mod silhouette: Velvety calf suede leather, structured modern square toe, 6cm sturdy geometric block heel, and side zip fastening.',
      price: 119,
      discount_price: 95,
      stock: 50,
      image_url: 'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1543163521-1bf539c55dd2?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 420,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Zara Shoes', Material: '100% Calf Suede Leather', Toe: 'Square Toe Box', Heel: '6 cm Block' }
    },
    {
      name: 'Zara Metallic Strappy Heeled Evening Sandals',
      slug: 'zara-metallic-strappy-heeled-evening-sandals',
      description: 'Barely-there party elegance: Delicate metallic foil tubular criss-cross straps, adjustable ankle buckle, and 8.5cm slim flared stiletto heel.',
      price: 79,
      discount_price: 62,
      stock: 60,
      image_url: 'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1543163521-1bf539c55dd2?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 580,
      is_featured: false,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Zara Party', Finish: 'Mirrored Gold / Silver Metallic', Heel: '8.5 cm Slim Heel' }
    },
    {
      name: 'Zara Minimalist Leather Slingback Kitten Heels',
      slug: 'zara-minimalist-leather-slingback-kitten-heels',
      description: '90s corporate chic: Pointed toe silhouette, supple leather upper, elasticated slingback strap, and 4.5cm comfortable kitten heel.',
      price: 89,
      discount_price: 69,
      stock: 70,
      image_url: 'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1543163521-1bf539c55dd2?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 640,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Zara Shoes', Heel: '4.5 cm Kitten Heel', Strap: 'Elastic Slingback' }
    },
    {
      name: 'Zara Woven Leather Fisherman Sandals',
      slug: 'zara-woven-leather-fisherman-sandals',
      description: 'Summer trendsetter: Interlocking wide leather cage straps, adjustable side metal buckle, padded leather footbed, and flexible lug sole.',
      price: 89,
      discount_price: 69,
      stock: 65,
      image_url: 'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1543163521-1bf539c55dd2?auto=format&fit=crop&w=800&q=80'],
      rating: 4.7,
      num_reviews: 370,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Zara', Style: 'Interlocking Fisherman Cage', Material: '100% Leather' }
    },
    {
      name: 'Zara Chunky Retro Leather Loafers with Buckle',
      slug: 'zara-chunky-retro-leather-loafers-with-buckle',
      description: 'Academic polish: Polished black leather upper, decorative metallic silver horsebit buckle across vamp, and thick 4cm cleated commando sole.',
      price: 99,
      discount_price: 79,
      stock: 80,
      image_url: 'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1543163521-1bf539c55dd2?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 980,
      is_featured: true,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Zara Woman', Upper: '100% Polished Leather', Buckle: 'Silver Metal Horsebit', Sole: '4 cm Cleated Commando Sole' }
    },
    {
      name: 'Zara Braided Leather Penny Loafers',
      slug: 'zara-braided-leather-penny-loafers',
      description: 'Classic menswear profile: Hand-braided leather band across penny cutout strap, leather lining, and leather sole with rubber heel injection.',
      price: 119,
      discount_price: 95,
      stock: 50,
      image_url: 'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1543163521-1bf539c55dd2?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 410,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Zara Man', Craft: 'Hand-Braided Saddle Detail', Material: '100% Burnished Calf Leather' }
    },
    {
      name: 'Zara Suede Mules with Shearling Lining',
      slug: 'zara-suede-mules-with-shearling-lining',
      description: 'Cozy slip-on luxury: Soft taupe suede upper with adjustable buckle strap, natural shearling fleece lining, and cork/EVA footbed.',
      price: 89,
      discount_price: 69,
      stock: 60,
      image_url: 'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1543163521-1bf539c55dd2?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 520,
      is_featured: false,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Zara', Upper: '100% Cow Suede', Lining: 'Genuine Shearling Fleece' }
    },
    {
      name: 'Zara Leather Slouchy Hobo Shoulder Bag',
      slug: 'zara-leather-slouchy-hobo-shoulder-bag',
      description: 'Effortless crescent silhouette: Buttery soft washed cowhide leather that molds naturally, wide comfortable shoulder strap, magnetic snap closure, and interior zip pouch.',
      price: 149,
      discount_price: 119,
      stock: 55,
      image_url: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1548036328-c9fa89d128fa?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 890,
      is_featured: true,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Zara Leather Collection', Material: '100% Genuine Washed Cowhide Leather', Shape: 'Slouchy Crescent Hobo' }
    },
    {
      name: 'Zara Rigid Box Leather Crossbody Bag',
      slug: 'zara-rigid-box-leather-crossbody-bag',
      description: 'Architectural structured minimalism: Smooth box calf leather, gold-toned magnetic clasp, adjustable crossbody strap, and dual interior accordion compartments.',
      price: 99,
      discount_price: 79,
      stock: 70,
      image_url: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1548036328-c9fa89d128fa?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 620,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Zara Accessories', Structure: 'Rigid Box Construction', Hardware: 'Brushed Gold-Plated Brass' }
    },
    {
      name: 'Zara Woven Raffia Beach Basket Tote',
      slug: 'zara-woven-raffia-beach-basket-tote',
      description: 'Handcrafted natural fiber basket: Woven natural palm raffia, contrast leather shoulder handles and leather logo patch, and drawstring fabric liner.',
      price: 69,
      discount_price: 52,
      stock: 80,
      image_url: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1548036328-c9fa89d128fa?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 740,
      is_featured: false,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Zara Summer', Body: '100% Hand-Woven Natural Raffia', Handles: '100% Cowhide Leather Handles' }
    },
    {
      name: 'Zara Quilted Leather Shoulder Flap Bag with Chain',
      slug: 'zara-quilted-leather-shoulder-flap-bag-with-chain',
      description: 'Parisian chic: Chevron quilted lambskin leather, sliding gold gourmette metal chain strap (wear single crossbody or double on shoulder), and turnlock clasp.',
      price: 129,
      discount_price: 99,
      stock: 65,
      image_url: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1548036328-c9fa89d128fa?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 1120,
      is_featured: true,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Zara Woman', Material: '100% Quilted Lambskin Leather', Strap: 'Sliding Dual-Length Gourmette Chain' }
    },
    {
      name: 'Zara Minimalist Soft Leather Shopper Tote',
      slug: 'zara-minimalist-soft-leather-shopper-tote',
      description: 'Generous everyday work bag: Fits 15-inch laptop and daily essentials, soft grain leather, reinforced flat handles, and removable zippered internal clutch pouch.',
      price: 139,
      discount_price: 110,
      stock: 50,
      image_url: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1548036328-c9fa89d128fa?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 590,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Zara Leather', Capacity: 'Accommodates 15-inch Laptop', Includes: 'Removable Leather Zipper Pouch' }
    },
    {
      name: 'Zara Metallic Evening Clutch with Detachable Strap',
      slug: 'zara-metallic-evening-clutch-with-detachable-strap',
      description: 'Hard-shell evening minaudière: Mirrored metallic chrome finish, top push-clasp closure, satin-lined interior, and detachable fine chain strap.',
      price: 59,
      discount_price: 45,
      stock: 75,
      image_url: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1548036328-c9fa89d128fa?auto=format&fit=crop&w=800&q=80'],
      rating: 4.7,
      num_reviews: 380,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Zara Evening', Structure: 'Minaudière Hard-Shell Frame', Strap: 'Removable Gold Chain' }
    },
    {
      name: 'Zara Red Vanilla Eau de Toilette 100ml',
      slug: 'zara-red-vanilla-eau-de-toilette-100ml',
      description: 'Bestselling sophisticated gourmand fragrance: Elegant bouquet of raspberry, blackcurrant, praline, and warm Madagascar bourbon vanilla notes.',
      price: 29,
      discount_price: 22,
      stock: 150,
      image_url: 'https://images.unsplash.com/photo-1547887537-6158d64c35b3?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1547887537-6158d64c35b3?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 2450,
      is_featured: true,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Zara Fragrances', Volume: '100 ml (3.4 fl oz)', Notes: 'Raspberry, Blackcurrant, Praline, Bourbon Vanilla' }
    },
    {
      name: 'Zara Black Amber Eau de Parfum 100ml',
      slug: 'zara-black-amber-eau-de-parfum-100ml',
      description: 'Warm, intoxicating and sensual: Vibrant top notes of juicy tangerine blended with passionfruit, tiaré flower, and deep rich amber and vanilla musk.',
      price: 32,
      discount_price: 25,
      stock: 130,
      image_url: 'https://images.unsplash.com/photo-1547887537-6158d64c35b3?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1547887537-6158d64c35b3?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 1890,
      is_featured: false,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Zara Fragrances', Volume: '100 ml EDP', Notes: 'Tangerine, Tiaré Flower, Black Amber, Vanilla' }
    },
    {
      name: 'Zara Vibrant Leather Men Eau de Parfum 100ml',
      slug: 'zara-vibrant-leather-men-eau-de-parfum-100ml',
      description: 'The cult favorite niche-level creation by Master Perfumer Jérôme Epinette: Sparkling Bergamot citrus opening, bamboo heart, and smoky leather/patchouli dry-down.',
      price: 39,
      discount_price: 29,
      stock: 160,
      image_url: 'https://images.unsplash.com/photo-1547887537-6158d64c35b3?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1547887537-6158d64c35b3?auto=format&fit=crop&w=800&q=80'],
      rating: 5.0,
      num_reviews: 3200,
      is_featured: true,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Zara Man Fragrances', Perfumer: 'Jérôme Epinette', Volume: '100 ml EDP', Family: 'Woody Smoky Citrus Leather' }
    },
    {
      name: 'Zara Tobacco Collection Rich Warm Addictive EDP 100ml',
      slug: 'zara-tobacco-collection-rich-warm-addictive-edp-100ml',
      description: 'Intimate cold-weather masterpiece: Honeyed tobacco accords blended with creamy coconut, tonka bean, sandalwood, and sweet white cedarwood.',
      price: 35,
      discount_price: 27,
      stock: 140,
      image_url: 'https://images.unsplash.com/photo-1547887537-6158d64c35b3?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1547887537-6158d64c35b3?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 2180,
      is_featured: false,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Zara Man Fragrances', Volume: '100 ml EDP', Notes: 'Rum, White Honey, Coconut, Tobacco Leaf, Tonka' }
    },
    {
      name: 'Zara Ebony Wood Jo Malone Fragrance 75ml',
      slug: 'zara-ebony-wood-jo-malone-fragrance-75ml',
      description: 'Created by Jo Malone CBE (Zara Emotions Collection): Notes of pink peppercorn, clove, and ebony wood evoke the feeling of a cozy wood-paneled library.',
      price: 49,
      discount_price: 39,
      stock: 90,
      image_url: 'https://images.unsplash.com/photo-1547887537-6158d64c35b3?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1547887537-6158d64c35b3?auto=format&fit=crop&w=800&q=80'],
      rating: 5.0,
      num_reviews: 1750,
      is_featured: true,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Zara Emotions by Jo Malone CBE', Volume: '75 ml EDP', Olfactory: 'Pink Pepper, Clove, Ebony Wood' }
    },
    {
      name: 'Zara 100% Mulberry Silk Printed Square Scarf',
      slug: 'zara-100-mulberry-silk-printed-square-scarf',
      description: 'Artisanal print accessories: 100% pure Mulberry silk twill (70 x 70 cm), hand-rolled edges, baroque medallion motif, and lustrous sheen.',
      price: 49,
      discount_price: 38,
      stock: 85,
      image_url: 'https://images.unsplash.com/photo-1601924994987-69e26d50dc26?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1601924994987-69e26d50dc26?auto=format&fit=crop&w=800&q=80'],
      rating: 4.9,
      num_reviews: 430,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Zara Studio', Material: '100% Pure Mulberry Silk Twill', Dimensions: '70 x 70 cm', Finish: 'Hand-Rolled Edges' }
    },
    {
      name: 'Zara Oversized Fringe Brushed Alpaca Wool Scarf',
      slug: 'zara-oversized-fringe-brushed-alpaca-wool-scarf',
      description: 'Super plush oversized blanket wrap: Ultra-soft brushed alpaca and wool blend, multi-color check tartan print, and chunky twisted fringe tassels.',
      price: 59,
      discount_price: 45,
      stock: 70,
      image_url: 'https://images.unsplash.com/photo-1601924994987-69e26d50dc26?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1601924994987-69e26d50dc26?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 620,
      is_featured: false,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Zara', Material: 'Alpaca & Wool Blend', Dimensions: '220 x 45 cm Blanket Size' }
    },
    {
      name: 'Zara Leather Western Buckle Waist Belt',
      slug: 'zara-leather-western-buckle-waist-belt',
      description: 'Statement accessory: 100% cowhide leather strap, engraved antique silver western buckle, matching metal keeper, and engraved tip.',
      price: 39,
      discount_price: 29,
      stock: 95,
      image_url: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 590,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Zara', Material: '100% Full-Grain Cowhide Leather', Hardware: 'Antique Engraved Silver Metal' }
    },
    {
      name: 'Zara 100% Leather Thin Gold-Tone Dress Belt',
      slug: 'zara-100-leather-thin-gold-tone-dress-belt',
      description: 'Delicate polish for trousers and dresses: Slim 2cm smooth calfskin leather strap with minimalist polished geometric gold-tone square buckle.',
      price: 35,
      discount_price: 26,
      stock: 110,
      image_url: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=800&q=80'],
      rating: 4.7,
      num_reviews: 470,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Zara', Width: '2 cm Slim Profile', Buckle: 'Polished Gold Plated' }
    },
    {
      name: 'Zara Tortoiseshell Rectangular Sunglasses',
      slug: 'zara-tortoiseshell-rectangular-sunglasses',
      description: '90s runway styling: Thick acetate rectangular frame in vintage tortoiseshell, 100% UV400 category 3 dark tinted protective lenses, with protective case.',
      price: 39,
      discount_price: 29,
      stock: 90,
      image_url: 'https://images.unsplash.com/photo-1511499767150-a48a237f0083?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1511499767150-a48a237f0083?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 680,
      is_featured: false,
      is_trending: true,
      category_id: categoryId,
      specifications: { Brand: 'Zara Eyewear', Protection: '100% UV400 Cat. 3 Protection', Material: 'High-Gloss Cellulose Acetate' }
    },
    {
      name: 'Zara Chunky Ribbed Wool Blend Beanie',
      slug: 'zara-chunky-ribbed-wool-blend-beanie',
      description: 'Winter warmth staple: Chunky wide-ribbed knit with folded cuff brim, stretchy soft hand-feel, and snug comfortable fit.',
      price: 25,
      discount_price: 19,
      stock: 130,
      image_url: 'https://images.unsplash.com/photo-1576871337632-b9aef4c17ab9?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1576871337632-b9aef4c17ab9?auto=format&fit=crop&w=800&q=80'],
      rating: 4.7,
      num_reviews: 840,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Zara', Material: 'Wool Blend Wide Rib', Style: 'Foldover Cuff Beanie' }
    },
    {
      name: 'Zara 100% Soft Leather Touchscreen Gloves',
      slug: 'zara-100-soft-leather-touchscreen-gloves',
      description: 'Smart winter luxury: Butter-soft 100% nappa sheepskin leather with conductive touchscreen fingertips on thumb and index, and warm fleece interior lining.',
      price: 49,
      discount_price: 39,
      stock: 80,
      image_url: 'https://images.unsplash.com/photo-1586350977771-b3b0abd50c82?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1586350977771-b3b0abd50c82?auto=format&fit=crop&w=800&q=80'],
      rating: 4.8,
      num_reviews: 390,
      is_featured: false,
      is_trending: false,
      category_id: categoryId,
      specifications: { Brand: 'Zara Man', Material: '100% Nappa Sheepskin Leather', Tech: 'Smart Touchscreen Conductive Fingertips' }
    }
  ];
};
